import {resolvePersonDisplayAwards} from '../people/certification-evidence';
import type {CertificationRecord} from '../offline/dive-planning';
import {API_RESOURCES,type ApiResource,type ApiKeyInput,type ApiKeyMetadata,type ApiConsent} from '../sharing/readonly-api';
import {opaqueId} from '../sharing/public-profile';
import {sha256,sharingJson,tableExists,sharingHeaders} from './sharing-access';
type KeyRow={id:string;owner_user_id:string;client:ApiKeyInput['client'];verifier:string;scopes_json:string;selection_json:string;created_at:number;expires_at:number;revoked_at:number|null;last_used_at:number|null};
type ObjectRow={record_id:string;public_id:string;data_json:string};
const kindFor={dives:'dive',awards:'certification',equipment:'equipment','equipment-usage':'dive'} as const;
export async function ensureApiSchema(db:D1Database){await db.batch([
  db.prepare('CREATE TABLE IF NOT EXISTS dive_api_keys (id TEXT PRIMARY KEY,owner_user_id TEXT NOT NULL,client TEXT NOT NULL,verifier TEXT NOT NULL,scopes_json TEXT NOT NULL,selection_json TEXT NOT NULL,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,revoked_at INTEGER,last_used_at INTEGER,replaces_id TEXT UNIQUE)'),
  db.prepare('CREATE TABLE IF NOT EXISTS dive_api_objects (key_id TEXT NOT NULL,resource TEXT NOT NULL,record_id TEXT NOT NULL,public_id TEXT NOT NULL UNIQUE,PRIMARY KEY(key_id,resource,record_id))'),
  db.prepare('CREATE TABLE IF NOT EXISTS dive_api_rate (key_id TEXT NOT NULL,window_start INTEGER NOT NULL,request_count INTEGER NOT NULL,PRIMARY KEY(key_id,window_start))'),
]);}
function metadata(row:KeyRow):ApiKeyMetadata{const selection=JSON.parse(row.selection_json) as ApiConsent;return {id:row.id,client:row.client,scopes:JSON.parse(row.scopes_json),createdAt:new Date(row.created_at).toISOString(),expiresAt:new Date(row.expires_at).toISOString(),revoked:row.revoked_at!==null,lastUsedAt:row.last_used_at===null?null:new Date(row.last_used_at).toISOString(),selectedCounts:Object.fromEntries(API_RESOURCES.filter(resource=>selection[resource]).map(resource=>[resource,selection[resource]!.ids.length]))};}
export async function apiKeyMetadata(db:D1Database,owner:string){if(!await tableExists(db,'dive_api_keys'))return [];const rows=await db.prepare('SELECT * FROM dive_api_keys WHERE owner_user_id=? ORDER BY created_at DESC LIMIT 100').bind(owner).all<KeyRow>();return rows.results.map(metadata);}
function data(value:string){if(value.length>1024*1024)throw new Error('Evidence unavailable.');const object=JSON.parse(value);if(!object||typeof object!=='object'||Array.isArray(object))throw new Error('Evidence unavailable.');return object as Record<string,unknown>;}
async function ownerPersonId(db:D1Database,owner:string){const people=await db.prepare("SELECT id,data_json FROM dive_records WHERE user_id=? AND kind='person' AND deleted_at IS NULL ORDER BY id LIMIT 1001").bind(owner).all<{id:string;data_json:string}>();if(people.results.length>1000)throw new Error('Evidence too large.');const selected=people.results.filter(row=>{const roles=data(row.data_json).roles;return roles&&typeof roles==='object'&&(roles as {ownerProfile?:boolean}).ownerProfile===true;});if(selected.length>1)throw new Error('Owner evidence ambiguous.');return selected[0]?.id??null;}
function ownedAward(record:Record<string,unknown>,ownerPerson:string|null){return !record.personId||typeof record.personId==='string'&&record.personId===ownerPerson;}
export async function integrationRecordChoices(db:D1Database,owner:string,resource:ApiResource,after:string,search:string){
  const ownerPerson=resource==='awards'?await ownerPersonId(db,owner):null;
  const title=resource==='awards'?"json_extract(data_json,'$.certification')":resource==='equipment'?"json_extract(data_json,'$.name')":"json_extract(data_json,'$.site')";
  const where=resource==='awards'?" AND (json_extract(data_json,'$.personId') IS NULL OR json_extract(data_json,'$.personId')='' OR json_extract(data_json,'$.personId')=?)":'';
  const statement=db.prepare(`SELECT id,data_json FROM dive_records WHERE user_id=? AND kind=? AND deleted_at IS NULL AND id>? AND json_valid(data_json) AND LOWER(COALESCE(${title},'')) LIKE ? ESCAPE '\\'${where} ORDER BY id LIMIT 101`);
  const pattern=`%${search.toLowerCase().replace(/[\\%_]/g,value=>`\\${value}`)}%`;
  const result=await statement.bind(owner,kindFor[resource],after,pattern,...(resource==='awards'?[ownerPerson??'']:[])).all<{id:string;data_json:string}>();
  const selected=result.results.slice(0,100);return {items:selected.map(row=>{const record=data(row.data_json);const label=resource==='awards'?record.certification||record.level:resource==='equipment'?record.name:`${text(record.date,64)??'Undated'} Â· ${text(record.site)??'Dive'}`;return {id:row.id,label:text(label)||'Record'};}),nextAfter:result.results.length>100?selected[selected.length-1]!.id:null};
}
export async function validateConsentRecords(db:D1Database,owner:string,input:ApiKeyInput){
  const ownerPerson=input.scopes.includes('awards')?await ownerPersonId(db,owner):null;
  for(const resource of input.scopes){
    const awardClause=resource==='awards'?" AND (json_extract(r.data_json,'$.personId') IS NULL OR json_extract(r.data_json,'$.personId')='' OR json_extract(r.data_json,'$.personId')=?)":'';
    const title=resource==='awards'?"COALESCE(json_extract(r.data_json,'$.certification'),json_extract(r.data_json,'$.level'))":resource==='equipment'?"json_extract(r.data_json,'$.name')":"json_extract(r.data_json,'$.site')";
    const result=await db.prepare(`SELECT COUNT(*) AS n FROM json_each(?) selected JOIN dive_records r ON r.id=selected.value WHERE r.user_id=? AND r.kind=? AND r.deleted_at IS NULL AND json_valid(r.data_json) AND ${title} IS NOT NULL${awardClause}`).bind(JSON.stringify(input.selection[resource]!.ids),owner,kindFor[resource],...(resource==='awards'?[ownerPerson??'']:[])).first<{n:number}>();
    if(result?.n!==input.selection[resource]!.ids.length)throw new Error('Selected owner evidence unavailable.');
  }
}
function randomSecret(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),byte=>byte.toString(16).padStart(2,'0')).join('');}
function equalDigest(a:string,b:string){if(a.length!==64||b.length!==64)return false;let difference=0;for(let index=0;index<64;index++)difference|=a.charCodeAt(index)^b.charCodeAt(index);return difference===0;}
export async function issueApiKey(db:D1Database,owner:string,input:ApiKeyInput,rotateId?:string){
  await validateConsentRecords(db,owner,input);await ensureApiSchema(db);
  const id=crypto.randomUUID(),secret=randomSecret(),verifier=await sha256(secret),now=Date.now();const statements=[];
  if(rotateId)statements.push(db.prepare('UPDATE dive_api_keys SET revoked_at=? WHERE id=? AND owner_user_id=? AND revoked_at IS NULL').bind(now,rotateId,owner));
  statements.push(db.prepare('INSERT INTO dive_api_keys (id,owner_user_id,client,verifier,scopes_json,selection_json,created_at,expires_at,revoked_at,last_used_at,replaces_id) SELECT ?,?,?,?,?,?,?,?,NULL,NULL,? WHERE (SELECT COUNT(*) FROM dive_api_keys WHERE owner_user_id=? AND revoked_at IS NULL AND expires_at>?)<20').bind(id,owner,input.client,verifier,JSON.stringify(input.scopes),JSON.stringify(input.selection),now,Date.parse(input.expiresAt),rotateId??null,owner,now));
  for(const resource of input.scopes){const objects=input.selection[resource]!.ids.map(recordId=>({recordId,publicId:crypto.randomUUID()}));statements.push(db.prepare("INSERT INTO dive_api_objects (key_id,resource,record_id,public_id) SELECT ?,?,json_extract(value,'$.recordId'),json_extract(value,'$.publicId') FROM json_each(?) WHERE EXISTS (SELECT 1 FROM dive_api_keys WHERE id=?)").bind(id,resource,JSON.stringify(objects),id));}
  await db.batch(statements);const row=await db.prepare('SELECT * FROM dive_api_keys WHERE id=? AND owner_user_id=?').bind(id,owner).first<KeyRow>();if(!row)throw new Error('Revoke an unused key first.');return {key:`ZT1.${id}.${secret}`,metadata:metadata(row)};
}
export async function ownedApiKey(db:D1Database,owner:string,id:string){if(!await tableExists(db,'dive_api_keys'))return null;return db.prepare('SELECT * FROM dive_api_keys WHERE id=? AND owner_user_id=?').bind(id,owner).first<KeyRow>();}
export function rotationInput(row:KeyRow,expiresAt:string):ApiKeyInput{return {client:row.client,expiresAt,scopes:JSON.parse(row.scopes_json),selection:JSON.parse(row.selection_json)};}
async function authenticate(db:D1Database,request:Request){const match=/^Bearer ZT1\.([a-f0-9-]{36})\.([a-f0-9]{64})$/.exec(request.headers.get('authorization')??'');if(!match||!opaqueId(match[1])||!await tableExists(db,'dive_api_keys'))return null;const row=await db.prepare('SELECT * FROM dive_api_keys WHERE id=?').bind(match[1]).first<KeyRow>();const supplied=await sha256(match[2]!);if(!row||!equalDigest(row.verifier,supplied)||row.revoked_at!==null||row.expires_at<=Date.now())return null;return row;}
async function hmac(verifier:string,message:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(verifier),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(message))),byte=>byte.toString(16).padStart(2,'0')).join('');}
async function cursorFor(row:KeyRow,resource:ApiResource,last:string){const payload=btoa(JSON.stringify({version:1,key:row.id,owner:await hmac(row.verifier,`owner:${row.owner_user_id}`),resource,last,expires:row.expires_at})).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');return `${payload}.${await hmac(row.verifier,payload)}`;}
async function cursorLast(value:string,row:KeyRow,resource:ApiResource){if(value.length>1000)throw new Error('Invalid cursor.');const [payload,signature,...extra]=value.split('.');if(extra.length||!payload||!signature||!equalDigest(signature,await hmac(row.verifier,payload)))throw new Error('Invalid cursor.');const object=JSON.parse(atob(payload.replaceAll('-','+').replaceAll('_','/')));if(object.version!==1||object.key!==row.id||object.owner!==await hmac(row.verifier,`owner:${row.owner_user_id}`)||object.resource!==resource||object.expires!==row.expires_at||!opaqueId(object.last))throw new Error('Invalid cursor.');return object.last as string;}
const text=(value:unknown,max=512)=>typeof value==='string'?value.slice(0,max):undefined;
const number=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)&&value>=0?value:undefined;
function awardTrack(record:Record<string,unknown>){const personId=typeof record.personId==='string'?record.personId:undefined;const resolved=resolvePersonDisplayAwards({...(personId?{entityId:personId}:{}),roles:{ownerProfile:true}},[record as unknown as CertificationRecord]);return resolved.pro.record?'professional-display':resolved.tec.record?'technical-display':resolved.rec.record?'recreational-display':'unclassified';}
function project(resource:Exclude<ApiResource,'equipment-usage'>,record:Record<string,unknown>,id:string,fields:string[]){const values=resource==='dives'?{date:text(record.date,64),site:text(record.site),depthM:number(record.maxDepthM),durationMin:number(record.totalElapsedMin??record.bottomTimeMin),mode:text(record.diveMode,120)}:resource==='awards'?{title:text(record.certification||record.level,180),agency:text(record.agency,180),date:text(record.issuedAt,64),track:awardTrack(record)}:{name:text(record.name),category:text(record.category,180),maker:text(record.manufacturer,180),model:text(record.model)};const names:Record<string,string>={depth:'depthM',duration:'durationMin'};return {id,...Object.fromEntries(fields.map(field=>names[field]??field).filter(field=>values[field as keyof typeof values]!==undefined).map(field=>[field,values[field as keyof typeof values]]))};}
function savedEquipment(record:Record<string,unknown>){if(Array.isArray(record.equipmentIds))return {ids:[...new Set(record.equipmentIds.filter((id):id is string=>typeof id==='string'&&id.length<=180))],provenance:'saved-equipment-ids'};const applications=Array.isArray(record.equipmentSetApplications)?record.equipmentSetApplications:[];const ids=new Set<string>();for(const application of applications.slice(0,100)){if(!application||typeof application!=='object')continue;const value=application as {slots?:unknown;overrideSlots?:unknown};const combined={...(value.slots&&typeof value.slots==='object'&&!Array.isArray(value.slots)?value.slots:{}),...(value.overrideSlots&&typeof value.overrideSlots==='object'&&!Array.isArray(value.overrideSlots)?value.overrideSlots:{})};for(const slot of Object.values(combined)){for(const id of Array.isArray(slot)?slot:[slot])if(typeof id==='string'&&id.length<=180)ids.add(id);}}return {ids:[...ids],provenance:applications.length?'saved-loadout-snapshot':'no-saved-evidence'};}
export function methodNotAllowed(){return new Response(JSON.stringify({error:'This API is read-only.'}),{status:405,headers:{...sharingHeaders,'content-type':'application/json',allow:'GET, HEAD'}});}
export async function serveApi(db:D1Database,request:Request,resource:ApiResource){
  if(!['GET','HEAD'].includes(request.method))return methodNotAllowed();
  const url=new URL(request.url);if(url.protocol!=='https:'&&!(process.env.NODE_ENV==='development'&&['localhost','127.0.0.1'].includes(url.hostname)))return sharingJson({error:'Use HTTPS.'},400);
  const allowed=['limit','cursor'];if([...url.searchParams.keys()].some(key=>!allowed.includes(key))||allowed.some(key=>url.searchParams.getAll(key).length>1))return sharingJson({error:'Unsupported query.'},400);const rawLimit=url.searchParams.get('limit')??'25';if(!/^\d{1,3}$/.test(rawLimit)||Number(rawLimit)<1||Number(rawLimit)>100)return sharingJson({error:'Limit must be between 1 and 100.'},400);const limit=Number(rawLimit);
  try {const row=await authenticate(db,request);if(!row)return sharingJson({error:'Valid integration key required.'},401);const scopes=JSON.parse(row.scopes_json) as ApiResource[];if(!scopes.includes(resource))return sharingJson({error:'This resource is outside the keyâ€™s scope.'},403);let last='';try {if(url.searchParams.has('cursor'))last=await cursorLast(url.searchParams.get('cursor')!,row,resource);}catch{return sharingJson({error:'Invalid pagination cursor.'},400);}
    const now=Date.now(),window=Math.floor(now/60000)*60000;const rate=await db.prepare('INSERT INTO dive_api_rate (key_id,window_start,request_count) VALUES (?,?,1) ON CONFLICT(key_id,window_start) DO UPDATE SET request_count=request_count+1 WHERE request_count<60 RETURNING request_count').bind(row.id,window).first<{request_count:number}>();if(!rate)return Response.json({error:'Request limit reached. Retry after this minute.'},{status:429,headers:{...sharingHeaders,'retry-after':String(Math.max(1,Math.ceil((window+60000-now)/1000)))}});
    await db.batch([db.prepare('UPDATE dive_api_keys SET last_used_at=? WHERE id=?').bind(now,row.id),db.prepare('DELETE FROM dive_api_rate WHERE key_id=? AND window_start<?').bind(row.id,window-60000)]);
    const result=await db.prepare('SELECT o.record_id,o.public_id,r.data_json FROM dive_api_objects o JOIN dive_records r ON r.id=o.record_id WHERE o.key_id=? AND o.resource=? AND r.user_id=? AND r.kind=? AND r.deleted_at IS NULL AND o.public_id>? ORDER BY o.public_id LIMIT ?').bind(row.id,resource,row.owner_user_id,kindFor[resource],last,limit+1).all<ObjectRow>();
    const selected=result.results.slice(0,limit),consent=JSON.parse(row.selection_json) as ApiConsent;let gear=new Map<string,string>();if(resource==='equipment-usage'&&scopes.includes('equipment')){const records=await db.prepare("SELECT o.record_id,o.public_id FROM dive_api_objects o JOIN dive_records r ON r.id=o.record_id WHERE o.key_id=? AND o.resource='equipment' AND r.user_id=? AND r.kind='equipment' AND r.deleted_at IS NULL LIMIT 1001").bind(row.id,row.owner_user_id).all<{record_id:string;public_id:string}>();gear=new Map(records.results.map(item=>[item.record_id,item.public_id]));}
    let linkedDives=new Map<string,string>();
    if(resource==='equipment-usage'&&scopes.includes('dives')){const records=await db.prepare("SELECT o.record_id,o.public_id FROM dive_api_objects o JOIN dive_records r ON r.id=o.record_id WHERE o.key_id=? AND o.resource='dives' AND r.user_id=? AND r.kind='dive' AND r.deleted_at IS NULL LIMIT 1001").bind(row.id,row.owner_user_id).all<{record_id:string;public_id:string}>();linkedDives=new Map(records.results.map(item=>[item.record_id,item.public_id]));}
    const ownerPerson=resource==='awards'?await ownerPersonId(db,row.owner_user_id):null;const items=[];
    for(const object of selected){const record=data(object.data_json);const shape=resource==='awards'?record.certification||record.level:resource==='equipment'?record.name:record.site;if(typeof shape!=='string')throw new Error('Evidence unavailable.');if(resource==='awards'&&!ownedAward(record,ownerPerson))continue;if(resource==='equipment-usage'){const evidence=savedEquipment(record),included=evidence.ids.filter(id=>gear.has(id)),withheld=evidence.ids.length-included.length;items.push({id:object.public_id,...(linkedDives.has(object.record_id)?{diveId:linkedDives.get(object.record_id)!}:{}),status:included.length?'confirmed':record.hireGear?'hire':'unknown',provenance:evidence.provenance,equipment:included.map(id=>({id:gear.get(id)!,provenance:evidence.provenance})),withheldEvidenceCount:withheld});}else items.push(project(resource,record,object.public_id,consent[resource]!.fields));}
    const body={version:'1',resource,units:resource==='dives'?{depth:'metres',duration:'minutes'}:{},provenance:'Current owner-consented canonical records; display awards grant no permissions',items,nextCursor:result.results.length>limit&&selected.length?await cursorFor(row,resource,selected[selected.length-1]!.public_id):null};
    return request.method==='HEAD'?new Response(null,{headers:sharingHeaders}):sharingJson(body);
  }catch{return sharingJson({error:'Selected data is temporarily unavailable.'},503);}
}
