import {getChatGPTUser} from '@/app/chatgpt-auth';
import {OWNER_EMAIL,isLocalPreviewUser} from './household';
export const sharingHeaders={'cache-control':'private, no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','referrer-policy':'no-referrer'};
export const sharingJson=(value:unknown,status=200)=>Response.json(value,{status,headers:sharingHeaders});
export async function sharingOwner(request?:Request){const user=await getChatGPTUser();if(!user)return {error:sharingJson({error:'Authentication required.'},401)} as const;if(user.email.toLowerCase()!==OWNER_EMAIL&&!isLocalPreviewUser(user))return {error:sharingJson({error:'Only the owner can manage publication and integration keys.'},403)} as const;if(request&&request.headers.get('origin')!==new URL(request.url).origin)return {error:sharingJson({error:'Use the owner settings on this site.'},403)} as const;return {user,slot:isLocalPreviewUser(user)?'local-preview':'landing'} as const;}
export async function tableExists(db:D1Database,name:string){return Boolean(await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(name).first());}
export async function boundedBytes(request:Request,max:number){const reader=request.body?.getReader();if(!reader)return new Uint8Array();const parts:Uint8Array[]=[];let size=0;try {while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>max){await reader.cancel();throw new Error('Request too large.');}parts.push(value);}}finally {reader.releaseLock();}const output=new Uint8Array(size);let cursor=0;for(const part of parts){output.set(part,cursor);cursor+=part.length;}return output;}
export async function boundedJson(request:Request,max=32*1024){if(!request.headers.get('content-type')?.startsWith('application/json'))throw new Error('Use JSON.');return JSON.parse(new TextDecoder().decode(await boundedBytes(request,max))) as unknown;}
export async function sha256(value:string|Uint8Array){const bytes=typeof value==='string'?new TextEncoder().encode(value):value;return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes))),byte=>byte.toString(16).padStart(2,'0')).join('');}
