import {describe,expect,it,vi} from 'vitest';
import {collectMatchingRecordIds} from '../lib/sharing/api-record-selection';
describe('explicit bounded Select all matching API consent',()=>{
  it('includes all matching pages, retains prior selected records and deduplicates',async()=>{const read=vi.fn().mockResolvedValueOnce({items:[{id:'a',label:'A'},{id:'b',label:'B'}],nextAfter:'b'}).mockResolvedValueOnce({items:[{id:'c',label:'C'}],nextAfter:null});const prior=['a','outside-filter'];expect(await collectMatchingRecordIds(prior,new AbortController().signal,read)).toEqual(['a','outside-filter','b','c']);expect(prior).toEqual(['a','outside-filter']);expect(read.mock.calls.map(call=>call[0])).toEqual(['','b']);});
  it('accepts1000 matching records and rejects1001 atomically, retaining original selections',async()=>{const prior=['old'];const pages=Array.from({length:10},(_,page)=>({items:Array.from({length:100},(_,n)=>({id:`${page}-${n}`,label:'Dummy'})),nextAfter:page<9?`page-${page+1}`:null}));let index=0;expect(await collectMatchingRecordIds([],new AbortController().signal,async()=>pages[index++]!)).toHaveLength(1000);index=0;await expect(collectMatchingRecordIds(prior,new AbortController().signal,async()=>pages[index++]!)).rejects.toThrow(/1000/);expect(prior).toEqual(['old']);});
  it('cancels before a request and after an in-flight response without applying partial records',async()=>{const first=new AbortController();first.abort();const read=vi.fn();await expect(collectMatchingRecordIds([],first.signal,read)).rejects.toMatchObject({name:'AbortError'});expect(read).not.toHaveBeenCalled();const second=new AbortController();await expect(collectMatchingRecordIds([],second.signal,async()=>{second.abort();return {items:[{id:'a',label:'A'}],nextAfter:null};})).rejects.toMatchObject({name:'AbortError'});});
  it('rejects cycling/repeated cursors and malformed/private responses',async()=>{await expect(collectMatchingRecordIds([],new AbortController().signal,async()=>({items:[{id:'a',label:'A'}],nextAfter:'same'}))).rejects.toThrow(/changed|again/);for(const page of [{items:[{id:'',label:'Bad'}],nextAfter:null},{items:[],nextAfter:'x'},{items:Array.from({length:101},(_,i)=>({id:String(i),label:'Dummy'})),nextAfter:null},{items:[{id:'a',label:'A'}],nextAfter:42}])await expect(collectMatchingRecordIds([],new AbortController().signal,async()=>page)).rejects.toThrow(/choices|changed/);});
  it('propagates request failure without replacing the reviewed draft',async()=>{const prior=['keep'];await expect(collectMatchingRecordIds(prior,new AbortController().signal,async()=>{throw new Error('Fixture unavailable');})).rejects.toThrow('Fixture unavailable');expect(prior).toEqual(['keep']);});
});
