import 'fake-indexeddb/auto';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {configureDiveStore,listLocalDiveRecords,saveLocalRecord} from '../lib/offline/dive-store';
import {zeustekDb} from '../lib/offline/db';
import {saveCalendarPlanFromDraft,savePlanDraftWithConnections} from '../lib/planning/calendar-plan-creation';
import {calendarPlanDestination,planDraftForBooking} from '../lib/planning/planning-start-context';
import {parseWorkflowDestination} from '../lib/workflow/workflow-destination';
import {readCalendarSources,type CalendarBooking} from '../lib/planning/calendar-booking-workflow';
import type {EnrichedDivePlan} from '../lib/offline/dive-planning-centre';
import {normaliseReusableLoadout,type ReusableLoadoutRecord} from '../lib/offline/loadouts-gas';
import type {Stored} from '../lib/offline/dive-planning';
type RawPlanningRecord={entityId:string;modifiedAt:string;notes?:string;[key:string]:unknown};
beforeEach(async()=>{vi.stubGlobal('window',new EventTarget());vi.stubGlobal('navigator',{onLine:false});vi.stubGlobal('fetch',vi.fn());configureDiveStore('event-plan-test');await zeustekDb.open();for(const table of zeustekDb.tables)await table.clear();});
afterEach(()=>vi.unstubAllGlobals());
async function seed(){await saveLocalRecord('trip',{entityId:'event',name:'Boat day',bookingKind:'dive',bookingStatus:'confirmed',startDate:'2026-10-10',endDate:'2026-10-10',startAt:'2026-10-10T08:30',siteId:'site',siteName:'Harbour',notes:'Private source notes',futureField:{keep:true}});return (await listLocalDiveRecords<CalendarBooking>('trip'))[0]!;}
const draft=(entry:CalendarBooking)=>planDraftForBooking({name:'',startDate:'today',endDate:'today',siteName:'',buddy:'',status:'planned',lifecycleStatus:'draft',planTeam:[],gasPlanLinks:[],conditions:{},humanFactors:{},emergency:{},checklist:[]} as unknown as EnrichedDivePlan,entry);
describe('Calendar event → reviewed new Dive Plan',()=>{
 it('normal Plan Save rejects stale selected Trip evidence without creating a Plan',async()=>{await saveLocalRecord('dive-trip',{entityId:'holiday',name:'Trip',planIds:[],notes:'Old'});const reviewed=await listLocalDiveRecords<RawPlanningRecord>('dive-trip');await saveLocalRecord('dive-trip',{...reviewed[0],notes:'New'});const input={...draft({name:'Event'} as CalendarBooking),tripId:'holiday'};await expect(savePlanDraftWithConnections(input,[],[],reviewed)).rejects.toThrow(/Trip.*changed/i);expect(await listLocalDiveRecords<RawPlanningRecord>('trip')).toHaveLength(0);expect((await listLocalDiveRecords<RawPlanningRecord>('dive-trip'))[0]!.notes).toBe('New');});
 it('moves an existing Plan between reviewed Trips atomically while preserving their notes and other Plans',async()=>{await saveLocalRecord('trip',{entityId:'plan',name:'Plan',tripId:'old'});await saveLocalRecord('dive-trip',{entityId:'old',name:'Old Trip',notes:'Old Trip notes',planIds:['plan','keep']});await saveLocalRecord('dive-trip',{entityId:'new',name:'New Trip',notes:'New Trip notes',planIds:['other']});const reviewedPlan=(await listLocalDiveRecords<RawPlanningRecord>('trip'))[0]!,trips=await listLocalDiveRecords<RawPlanningRecord>('dive-trip');await savePlanDraftWithConnections({...draft({name:'Plan'} as CalendarBooking),entityId:'plan',tripId:'new'},[],[],trips,reviewedPlan);const saved=await listLocalDiveRecords<RawPlanningRecord>('dive-trip');expect(saved.find(t=>t.entityId==='old')).toMatchObject({notes:'Old Trip notes',planIds:['keep']});expect(saved.find(t=>t.entityId==='new')).toMatchObject({notes:'New Trip notes',planIds:['other','plan']});});
 it('a failing inverse Trip write rolls back Plan, event association and all pending revisions',async()=>{const entry=await seed();await saveLocalRecord('dive-trip',{entityId:'holiday',name:'Trip',planIds:[],notes:'Keep'});const trips=await listLocalDiveRecords<RawPlanningRecord>('dive-trip'),before=await Promise.all([listLocalDiveRecords<RawPlanningRecord>('trip'),listLocalDiveRecords<RawPlanningRecord>('dive-trip')]),original=zeustekDb.events.add.bind(zeustekDb.events);const spy=vi.spyOn(zeustekDb.events,'add').mockImplementationOnce(original).mockImplementationOnce(original).mockRejectedValueOnce(new Error('Fixture inverse failure'));await expect(saveCalendarPlanFromDraft(entry,{...draft(entry),tripId:'holiday'},[],[],trips)).rejects.toThrow('Fixture inverse failure');spy.mockRestore();expect(await Promise.all([listLocalDiveRecords<RawPlanningRecord>('trip'),listLocalDiveRecords<RawPlanningRecord>('dive-trip')])).toEqual(before);});
 it('rejects a selected Trip with an unresolved sync conflict',async()=>{const entry=await seed();await saveLocalRecord('dive-trip',{entityId:'holiday',name:'Trip',planIds:[]});const trips=await listLocalDiveRecords<RawPlanningRecord>('dive-trip'),key='pending:dive:event-plan-test:holiday',pending=(await zeustekDb.settings.get(key))!;await zeustekDb.settings.put({...pending,value:{...pending.value as object,state:'conflict'}});await expect(saveCalendarPlanFromDraft(entry,{...draft(entry),tripId:'holiday'},[],[],trips)).rejects.toThrow(/Trip.*review/i);expect(await listLocalDiveRecords<RawPlanningRecord>('trip')).toHaveLength(1);});

 it('writes the Trip inverse in the same transaction from reviewed current data',async()=>{const entry=await seed();await saveLocalRecord('dive-trip',{entityId:'holiday',name:'Holiday',planIds:[],notes:'Owner notes',itinerary:[{id:'s',notes:'Keep itinerary'}],futureField:{keep:true}});const trips=await listLocalDiveRecords<RawPlanningRecord>('dive-trip');const result=await saveCalendarPlanFromDraft(entry,{...draft(entry),tripId:'holiday'},[],[],trips);expect((await listLocalDiveRecords<RawPlanningRecord>('dive-trip'))[0]).toMatchObject({planIds:[result.id],notes:'Owner notes',itinerary:[{id:'s',notes:'Keep itinerary'}],futureField:{keep:true}});});
 it('rejects a newer Trip revision before Plan/event writes and preserves its owner data',async()=>{const entry=await seed();await saveLocalRecord('dive-trip',{entityId:'holiday',name:'Holiday',planIds:[],notes:'Old notes',itinerary:[]});const reviewed=await listLocalDiveRecords<RawPlanningRecord>('dive-trip');await saveLocalRecord('dive-trip',{...reviewed[0],notes:'New owner notes',itinerary:[{id:'s',notes:'New owner itinerary'}]});await expect(saveCalendarPlanFromDraft(entry,{...draft(entry),tripId:'holiday'},[],[],reviewed)).rejects.toThrow(/Trip.*changed|Trip.*review/i);expect(await listLocalDiveRecords<RawPlanningRecord>('trip')).toHaveLength(1);expect((await listLocalDiveRecords<RawPlanningRecord>('dive-trip'))[0]).toMatchObject({notes:'New owner notes',planIds:[],itinerary:[{id:'s',notes:'New owner itinerary'}]});});

 it('ordinary booking opens new explicit context and linked Plan still opens exact record',()=>{expect(parseWorkflowDestination(calendarPlanDestination({entityId:'event',bookingKind:'dive'},false))).toMatchObject({params:{newPlanForBooking:'event'}});expect(parseWorkflowDestination(calendarPlanDestination({entityId:'event',linkedDivePlanId:'plan',bookingKind:'dive'},false))).toMatchObject({recordId:'plan'});expect(parseWorkflowDestination(calendarPlanDestination({entityId:'legacy',bookingKind:'dive'},true))).toMatchObject({recordId:'legacy'});});
 it('creates no record while building a reviewable event/date/Site draft',async()=>{const entry=await seed(),before=structuredClone(entry);expect(draft(entry)).toMatchObject({name:'Boat day — Dive Plan',startDate:'2026-10-10',startAt:'2026-10-10T08:30',siteId:'site',siteName:'Harbour',lifecycleStatus:'draft'});expect(draft(entry)).not.toHaveProperty('entityId');expect(draft(entry)).not.toHaveProperty('bookingKind');expect(await listLocalDiveRecords<RawPlanningRecord>('trip')).toEqual([before]);});
 it('saves distinct canonical Plan and event link atomically, retaining source fields and history',async()=>{const entry=await seed();const result=await saveCalendarPlanFromDraft(entry,draft(entry),[],[]);const rows=await listLocalDiveRecords<CalendarBooking>('trip');expect(result.id).not.toBe('event');expect(rows.find(r=>r.entityId==='event')).toMatchObject({notes:'Private source notes',futureField:{keep:true},linkedDivePlanId:result.id});expect(rows.find(r=>r.entityId===result.id)).not.toHaveProperty('bookingKind');expect((await readCalendarSources()).canonicalPlanIds).toContain(result.id);expect(fetch).not.toHaveBeenCalled();});
 it('rejects a stale source before creating any Plan or overwriting its newer notes',async()=>{const entry=await seed();await saveLocalRecord('trip',{...entry,notes:'New notes'});await expect(saveCalendarPlanFromDraft(entry,draft(entry),[],[])).rejects.toThrow(/changed|reopen/i);expect(await listLocalDiveRecords<RawPlanningRecord>('trip')).toHaveLength(1);});
 it('refuses duplicate creation after another Plan is linked',async()=>{const entry=await seed();await saveCalendarPlanFromDraft(entry,draft(entry),[],[]);const current=(await listLocalDiveRecords<CalendarBooking>('trip')).find(r=>r.entityId==='event')!;await expect(saveCalendarPlanFromDraft(current,draft(current),[],[])).rejects.toThrow(/already|linked/i);expect(await listLocalDiveRecords<RawPlanningRecord>('trip')).toHaveLength(2);});
 it('rolls back the new Plan if saving its booking association fails',async()=>{const entry=await seed();const add=vi.spyOn(zeustekDb.events,'add');const original=zeustekDb.events.add.bind(zeustekDb.events);add.mockRestore();const spy=vi.spyOn(zeustekDb.events,'add').mockImplementationOnce(original).mockRejectedValueOnce(new Error('Fixture link failure'));await expect(saveCalendarPlanFromDraft(entry,draft(entry),[],[])).rejects.toThrow('Fixture link failure');spy.mockRestore();expect(await listLocalDiveRecords<RawPlanningRecord>('trip')).toHaveLength(1);});
 it('an aborted online transaction sends nothing and exposes no record-update event',async()=>{const entry=await seed();vi.stubGlobal('navigator',{onLine:true});const changed=vi.fn();window.addEventListener('zeustek-records-updated',changed);const original=zeustekDb.events.add.bind(zeustekDb.events),spy=vi.spyOn(zeustekDb.events,'add').mockImplementationOnce(original).mockRejectedValueOnce(new Error('Fixture rollback'));await expect(saveCalendarPlanFromDraft(entry,draft(entry),[],[])).rejects.toThrow('Fixture rollback');spy.mockRestore();expect(fetch).not.toHaveBeenCalled();expect(changed).not.toHaveBeenCalled();vi.stubGlobal('navigator',{onLine:false});expect(await listLocalDiveRecords<RawPlanningRecord>('trip')).toHaveLength(1);});
 it('pending source conflict needs review and cannot create a hidden second record',async()=>{const entry=await seed();const key='pending:dive:event-plan-test:event',pending=(await zeustekDb.settings.get(key))!;await zeustekDb.settings.put({...pending,value:{...pending.value as object,state:'conflict'}});await expect(saveCalendarPlanFromDraft(entry,draft(entry),[],[])).rejects.toThrow(/sync differences/i);expect(await listLocalDiveRecords<RawPlanningRecord>('trip')).toHaveLength(1);});
 it('rejects a stale selected Gas Plan without creating the Plan or event association',async()=>{const entry=await seed();await saveLocalRecord('gas-plan',{entityId:'gas',name:'Gas',status:'draft',cylinders:[]});const gas=(await listLocalDiveRecords<import('../lib/offline/planning-pages').StoredGasPlanRecord>('gas-plan'))[0]!;await saveLocalRecord('gas-plan',{...gas,name:'New gas'});await expect(saveCalendarPlanFromDraft(entry,draft(entry),[{...gas,modifiedAt:'old'}],['gas'])).rejects.toThrow(/Gas Plan changed/i);expect(await listLocalDiveRecords<RawPlanningRecord>('trip')).toHaveLength(1);});
});

describe('Plan connections and reviewed loadout are one Save',()=>{
 const snapshot=()=>Promise.all(zeustekDb.tables.filter(table=>table.name!=='diagnostics').map(table=>table.toArray()));
 async function context(){const entry=await seed();await saveLocalRecord('dive-trip',{entityId:'holiday',name:'Trip',planIds:[],notes:'Keep Trip'});await saveLocalRecord('equipment-set',{entityId:'loadout',name:'Current loadout',equipmentIds:['mask'],slots:{'personal.mask':'mask'}});return{entry,trips:await listLocalDiveRecords<RawPlanningRecord>('dive-trip'),loadout:normaliseReusableLoadout((await listLocalDiveRecords<Stored<ReusableLoadoutRecord>>('equipment-set'))[0]!)};}
 it('saves current equipment and fresh application with both links, leaving the loadout unchanged',async()=>{const {entry,trips,loadout}=await context(),before=await listLocalDiveRecords<RawPlanningRecord>('equipment-set');const result=await savePlanDraftWithConnections({...draft(entry),tripId:'holiday',equipmentSetId:'loadout'},[],[],trips,null,entry,loadout);const rows=await listLocalDiveRecords<RawPlanningRecord>('trip');expect(rows.find(row=>row.entityId===result.id)).toMatchObject({equipmentIds:['mask'],equipmentSetApplications:[{equipmentSetId:'loadout',slots:expect.objectContaining({'personal.mask':'mask'})}]});expect(rows.find(row=>row.entityId==='event')).toMatchObject({linkedDivePlanId:result.id});expect((await listLocalDiveRecords<RawPlanningRecord>('dive-trip'))[0]).toMatchObject({planIds:[result.id],notes:'Keep Trip'});expect(await listLocalDiveRecords<RawPlanningRecord>('equipment-set')).toEqual(before);});
 it('a late loadout persistence failure rolls back all rows/history/queue and permits retry',async()=>{const {entry,trips,loadout}=await context(),before=await snapshot(),original=zeustekDb.events.add.bind(zeustekDb.events);const spy=vi.spyOn(zeustekDb.events,'add').mockImplementationOnce(original).mockImplementationOnce(original).mockImplementationOnce(original).mockRejectedValueOnce(new Error('Fixture loadout persistence failure'));try{await expect(savePlanDraftWithConnections({...draft(entry),tripId:'holiday',equipmentSetId:'loadout'},[],[],trips,null,entry,loadout)).rejects.toThrow('Fixture loadout persistence failure');}finally{spy.mockRestore();}expect(await snapshot()).toEqual(before);await expect(savePlanDraftWithConnections({...draft(entry),tripId:'holiday',equipmentSetId:'loadout'},[],[],trips,null,entry,loadout)).resolves.toHaveProperty('id');});
 it('account switching during loadout persistence rolls back the entire original-account Save',async()=>{const {entry,trips,loadout}=await context(),before=await snapshot(),original=zeustekDb.events.add.bind(zeustekDb.events);const spy=vi.spyOn(zeustekDb.events,'add').mockImplementationOnce(original).mockImplementationOnce(original).mockImplementationOnce(original).mockImplementationOnce((...args)=>original(...args).then(result=>{configureDiveStore('different-account');return result;}));try{await expect(savePlanDraftWithConnections({...draft(entry),tripId:'holiday',equipmentSetId:'loadout'},[],[],trips,null,entry,loadout)).rejects.toThrow(/account changed/i);}finally{spy.mockRestore();configureDiveStore('event-plan-test');}expect(await snapshot()).toEqual(before);});
 it.each(['stale','deleted','conflicted'])('rejects %s loadout evidence before creating any Plan',async(mode)=>{const {entry,trips,loadout}=await context();if(mode==='stale')await saveLocalRecord('equipment-set',{...loadout,slots:{'personal.mask':'changed-mask'}});if(mode==='deleted')await zeustekDb.entities.update('dive:event-plan-test:loadout',{deleted:1});if(mode==='conflicted'){const row=(await zeustekDb.settings.get('pending:dive:event-plan-test:loadout'))!;await zeustekDb.settings.put({...row,value:{...row.value as object,state:'conflict'}});}const before=await snapshot();await expect(savePlanDraftWithConnections({...draft(entry),tripId:'holiday',equipmentSetId:'loadout'},[],[],trips,null,entry,loadout)).rejects.toThrow(/loadout.*changed|loadout.*review/i);expect(await snapshot()).toEqual(before);});
});
