import 'fake-indexeddb/auto';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {configureDiveStore,listLocalDiveRecords,saveLocalRecord} from '../lib/offline/dive-store';
import {zeustekDb} from '../lib/offline/db';
import {saveCalendarPlanFromDraft} from '../lib/planning/calendar-plan-creation';
import {calendarPlanDestination,planDraftForBooking} from '../lib/planning/planning-start-context';
import {parseWorkflowDestination} from '../lib/workflow/workflow-destination';
import {readCalendarSources,type CalendarBooking} from '../lib/planning/calendar-booking-workflow';
import type {EnrichedDivePlan} from '../lib/offline/dive-planning-centre';
beforeEach(async()=>{vi.stubGlobal('window',new EventTarget());vi.stubGlobal('navigator',{onLine:false});vi.stubGlobal('fetch',vi.fn());configureDiveStore('event-plan-test');await zeustekDb.open();for(const table of zeustekDb.tables)await table.clear();});
afterEach(()=>vi.unstubAllGlobals());
async function seed(){await saveLocalRecord('trip',{entityId:'event',name:'Boat day',bookingKind:'dive',bookingStatus:'confirmed',startDate:'2026-10-10',endDate:'2026-10-10',startAt:'2026-10-10T08:30',siteId:'site',siteName:'Harbour',notes:'Private source notes',futureField:{keep:true}});return (await listLocalDiveRecords<CalendarBooking>('trip'))[0]!;}
const draft=(entry:CalendarBooking)=>planDraftForBooking({name:'',startDate:'today',endDate:'today',siteName:'',buddy:'',status:'planned',lifecycleStatus:'draft',planTeam:[],gasPlanLinks:[],conditions:{},humanFactors:{},emergency:{},checklist:[]} as unknown as EnrichedDivePlan,entry);
describe('Calendar event â†’ reviewed new Dive Plan',()=>{
 it('ordinary booking opens new explicit context and linked Plan still opens exact record',()=>{expect(parseWorkflowDestination(calendarPlanDestination({entityId:'event',bookingKind:'dive'},false))).toMatchObject({params:{newPlanForBooking:'event'}});expect(parseWorkflowDestination(calendarPlanDestination({entityId:'event',linkedDivePlanId:'plan',bookingKind:'dive'},false))).toMatchObject({recordId:'plan'});expect(parseWorkflowDestination(calendarPlanDestination({entityId:'legacy',bookingKind:'dive'},true))).toMatchObject({recordId:'legacy'});});
 it('creates no record while building a reviewable event/date/Site draft',async()=>{const entry=await seed(),before=structuredClone(entry);expect(draft(entry)).toMatchObject({name:'Boat day â€” Dive Plan',startDate:'2026-10-10',startAt:'2026-10-10T08:30',siteId:'site',siteName:'Harbour',lifecycleStatus:'draft'});expect(draft(entry)).not.toHaveProperty('entityId');expect(draft(entry)).not.toHaveProperty('bookingKind');expect(await listLocalDiveRecords('trip')).toEqual([before]);});
 it('saves distinct canonical Plan and event link atomically, retaining source fields and history',async()=>{const entry=await seed();const result=await saveCalendarPlanFromDraft(entry,draft(entry),[],[]);const rows=await listLocalDiveRecords<CalendarBooking>('trip');expect(result.id).not.toBe('event');expect(rows.find(r=>r.entityId==='event')).toMatchObject({notes:'Private source notes',futureField:{keep:true},linkedDivePlanId:result.id});expect(rows.find(r=>r.entityId===result.id)).not.toHaveProperty('bookingKind');expect((await readCalendarSources()).canonicalPlanIds).toContain(result.id);expect(fetch).not.toHaveBeenCalled();});
 it('rejects a stale source before creating any Plan or overwriting its newer notes',async()=>{const entry=await seed();await saveLocalRecord('trip',{...entry,notes:'New notes'});await expect(saveCalendarPlanFromDraft(entry,draft(entry),[],[])).rejects.toThrow(/changed|reopen/i);expect(await listLocalDiveRecords('trip')).toHaveLength(1);});
 it('refuses duplicate creation after another Plan is linked',async()=>{const entry=await seed();await saveCalendarPlanFromDraft(entry,draft(entry),[],[]);const current=(await listLocalDiveRecords<CalendarBooking>('trip')).find(r=>r.entityId==='event')!;await expect(saveCalendarPlanFromDraft(current,draft(current),[],[])).rejects.toThrow(/already|linked/i);expect(await listLocalDiveRecords('trip')).toHaveLength(2);});
 it('rolls back the new Plan if saving its booking association fails',async()=>{const entry=await seed();const add=vi.spyOn(zeustekDb.events,'add');const original=zeustekDb.events.add.bind(zeustekDb.events);add.mockRestore();const spy=vi.spyOn(zeustekDb.events,'add').mockImplementationOnce(original).mockRejectedValueOnce(new Error('Fixture link failure'));await expect(saveCalendarPlanFromDraft(entry,draft(entry),[],[])).rejects.toThrow('Fixture link failure');spy.mockRestore();expect(await listLocalDiveRecords('trip')).toHaveLength(1);});
 it('an aborted online transaction sends nothing and exposes no record-update event',async()=>{const entry=await seed();vi.stubGlobal('navigator',{onLine:true});const changed=vi.fn();window.addEventListener('zeustek-records-updated',changed);const original=zeustekDb.events.add.bind(zeustekDb.events),spy=vi.spyOn(zeustekDb.events,'add').mockImplementationOnce(original).mockRejectedValueOnce(new Error('Fixture rollback'));await expect(saveCalendarPlanFromDraft(entry,draft(entry),[],[])).rejects.toThrow('Fixture rollback');spy.mockRestore();expect(fetch).not.toHaveBeenCalled();expect(changed).not.toHaveBeenCalled();vi.stubGlobal('navigator',{onLine:false});expect(await listLocalDiveRecords('trip')).toHaveLength(1);});
 it('pending source conflict needs review and cannot create a hidden second record',async()=>{const entry=await seed();const key='pending:dive:event-plan-test:event',pending=(await zeustekDb.settings.get(key))!;await zeustekDb.settings.put({...pending,value:{...pending.value as object,state:'conflict'}});await expect(saveCalendarPlanFromDraft(entry,draft(entry),[],[])).rejects.toThrow(/sync differences/i);expect(await listLocalDiveRecords('trip')).toHaveLength(1);});
 it('rejects a stale selected Gas Plan without creating the Plan or event association',async()=>{const entry=await seed();await saveLocalRecord('gas-plan',{entityId:'gas',name:'Gas',status:'draft',cylinders:[]});const gas=(await listLocalDiveRecords<import('../lib/offline/planning-pages').StoredGasPlanRecord>('gas-plan'))[0]!;await saveLocalRecord('gas-plan',{...gas,name:'New gas'});await expect(saveCalendarPlanFromDraft(entry,draft(entry),[{...gas,modifiedAt:'old'}],['gas'])).rejects.toThrow(/Gas Plan changed/i);expect(await listLocalDiveRecords('trip')).toHaveLength(1);});
});
