import 'fake-indexeddb/auto';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {zeustekDb} from '../lib/offline/db';
import {configureDiveStore,flushDiveChanges,refreshDiveRecords,saveLocalRecord} from '../lib/offline/dive-store';
import {readCloudAccountStatus} from '../lib/offline/read-cloud-account-status';
import {cloudAccountIndicator} from '../lib/offline/cloud-account-indicator';
beforeEach(async()=>{vi.stubGlobal('window',new EventTarget());vi.stubGlobal('navigator',{onLine:false});vi.stubGlobal('fetch',vi.fn());configureDiveStore('');configureDiveStore('cloud-evidence');await zeustekDb.open();for(const table of zeustekDb.tables)await table.clear();});
afterEach(()=>vi.unstubAllGlobals());
const status=async()=>cloudAccountIndicator(await readCloudAccountStatus());
describe('Cloud badge uses actual account-scoped cloud evidence',()=>{
 it('an empty online device queue and no-op flush do not establish Synced',async()=>{vi.stubGlobal('navigator',{onLine:true});await flushDiveChanges();expect(fetch).not.toHaveBeenCalled();expect(await status()).toMatchObject({state:'pending',label:expect.stringContaining('Checking')});});
 it('failed cloud refresh remains visible across repeated device-only reads',async()=>{vi.stubGlobal('navigator',{onLine:true});vi.mocked(fetch).mockResolvedValue(Response.json({}, {status:503}));await refreshDiveRecords('person',true);expect(await status()).toMatchObject({state:'pending',label:expect.stringContaining('attention')});expect(await status()).toMatchObject({state:'pending'});});
 it('a successful download verifies the current account; another failed kind stays visible until it recovers',async()=>{vi.stubGlobal('navigator',{onLine:true});vi.mocked(fetch).mockResolvedValue(Response.json({items:[]}));await refreshDiveRecords('person',true);expect(await status()).toMatchObject({state:'synced'});vi.mocked(fetch).mockResolvedValue(Response.json({}, {status:503}));await refreshDiveRecords('trip',true);vi.mocked(fetch).mockResolvedValue(Response.json({items:[]}));await refreshDiveRecords('person',true);expect(await status()).toMatchObject({state:'pending',label:expect.stringContaining('attention')});await refreshDiveRecords('trip',true);expect(await status()).toMatchObject({state:'synced'});});
 it('late completion for a previous account cannot verify a newly selected account',async()=>{vi.stubGlobal('navigator',{onLine:true});let complete!:(value:Response)=>void;vi.mocked(fetch).mockImplementation(()=>new Promise(resolve=>{complete=resolve;}));const request=refreshDiveRecords('site',true);configureDiveStore('new-cloud-account');complete(Response.json({items:[]}));await request;expect(await status()).toMatchObject({state:'pending',label:expect.stringContaining('Checking')});});
 it('a failed real write remains local, surfaces attention and only a successful retry clears it',async()=>{await saveLocalRecord('operator',{entityId:'dummy',name:'Retained'});const before=await zeustekDb.entities.toArray();vi.stubGlobal('navigator',{onLine:true});vi.mocked(fetch).mockResolvedValue(Response.json({error:'Fixture transport failure'},{status:503}));await flushDiveChanges();expect(await status()).toMatchObject({state:'pending',label:expect.stringContaining('attention')});expect(await zeustekDb.entities.toArray()).toEqual(before);vi.mocked(fetch).mockResolvedValue(Response.json({updatedAt:Date.parse('2026-10-05T18:00:00Z')}));await flushDiveChanges();expect(await status()).toMatchObject({state:'synced'});});
});
