import { describe, expect, it } from 'vitest';
import { DEFAULT_PLAN_CHECKLIST, evaluatePlanReadiness, normalisePlan, type StoredEnrichedDivePlan } from '../lib/offline/dive-planning-centre';

const plan:StoredEnrichedDivePlan={entityId:'p1',name:'Test',planType:'day-dive',startDate:'2026-09-20',endDate:'2026-09-20',siteName:'St Abbs',buddy:'Gemma',status:'planned',notes:'',createdAt:'x',modifiedAt:'x'};
describe('T10 Dive Planning Centre',()=>{
 it('normalises legacy Plans without replacing IDs',()=>{const next=normalisePlan(plan);expect(next.entityId).toBe('p1');expect(next.lifecycleStatus).toBe('draft');expect(next.checklist).toHaveLength(DEFAULT_PLAN_CHECKLIST.length);});
 it('keeps readiness advisory and explains missing fields',()=>{const result=evaluatePlanReadiness(plan);expect(result.state).toBe('draft');expect(result.warnings.length).toBeGreaterThan(0);});
 it('can become ready when operational evidence is present',()=>{const ready={...plan,siteId:'s1',startAt:'2026-09-20T09:30',planTeam:[{personId:'u2',role:'Buddy'}],equipmentSetId:'set1',emergency:{emergencyContact:'Centre'},humanFactors:{keyRisks:['Current']},checklist:DEFAULT_PLAN_CHECKLIST.map(item=>({...item,completed:true}))};expect(evaluatePlanReadiness(ready).state).toBe('ready');});
 it('does not require technical fields for a recreational plan',()=>{const simple={...plan,siteId:'s1',startAt:'2026-09-20T09:30',planTeam:[{personId:'u2',role:'Buddy'}],equipmentSetId:'set1',emergency:{emergencyContact:'Centre'},humanFactors:{stopAbortCriteria:['Turn pressure']},checklist:DEFAULT_PLAN_CHECKLIST.map(item=>({...item,completed:true}))};const result=evaluatePlanReadiness(simple);expect(result.state).toBe('ready');expect('technicalMode' in simple).toBe(false);});
 it('requires canonical gas evidence only when technical planning is disclosed',()=>{const technical={...plan,technicalMode:true,siteId:'s1',startAt:'2026-09-20T09:30',planTeam:[{personId:'u2',role:'Buddy'}],equipmentSetId:'set1',emergency:{emergencyContact:'Centre'},humanFactors:{stopAbortCriteria:['Turn pressure']},checklist:DEFAULT_PLAN_CHECKLIST.map(item=>({...item,completed:true}))};const incomplete=evaluatePlanReadiness(technical);expect(incomplete.state).not.toBe('ready');expect(incomplete.warnings).toContain('Link every planned cylinder to canonical Equipment.');const ready={...technical,plannedMaxDepthM:42,plannedRuntimeMin:55,cylinderAssignments:[{id:'c1',cylinderEquipmentId:'cylinder-1',fillId:'fill-1',analysisId:'analysis-1'}]};expect(evaluatePlanReadiness(ready).state).toBe('ready');});
});
