import 'fake-indexeddb/auto';
import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
import { zeustekDb } from '../lib/offline/db';
import { configureDiveStore, saveLocalRecord } from '../lib/offline/dive-store';
import { createCanonicalSkill, createCanonicalSkills, createDiveDraftFromPlan, deleteDiveSkillEvidence, deleteUnusedArchivedSkills, linkSkillEvidenceToDive, listCanonicalSkills, loadOriginatingPlan, listSkillEvidence, planComparison, previewCanonicalSkillBatch, previewUnusedArchivedSkills, resolveCanonicalSkillReference, saveDiveSkillEvidence, setCanonicalSkillArchived, skillEvidenceDisplayName, skillRecordGroup, skillRecordKey, unlinkSkillEvidenceFromDive, updateCanonicalSkill } from '../lib/offline/dive-context';
import { saveDive, listDives } from '../lib/offline/dives';
import { saveDivePerspective } from '../lib/offline/dive-perspectives';
import { localBackupPayload, restoreLocalPayload } from '../lib/offline/local-backup';
import { loadMediaMetadata } from '../lib/offline/media-metadata';
import { DiveEditorWrites } from '../lib/offline/dive-editor-writes';

beforeEach(async () => {
  vi.stubGlobal('window', new EventTarget()); vi.stubGlobal('navigator', { onLine: false }); vi.stubGlobal('fetch', vi.fn());
  configureDiveStore('context-test'); await zeustekDb.open();
  for (const table of zeustekDb.tables) await table.clear();
});
afterEach(() => vi.unstubAllGlobals());
const plan = { entityId: 'same-plan', name: 'Quarry practice', siteName: 'Capernwray', siteId: 'same-site', startDate: '2026-09-12', endDate: '2026-09-12', startAt: '2026-09-12T10:00', buddy: 'Buddy', status: 'planned', notes: 'Original intent', futurePlanField: 'retain' };

describe('shared Dive references and save boundary', () => {
  it('preserves the original immutable Plan revision through later edits and backup/restore', async () => {
    await saveLocalRecord('trip', plan);
    const draft = await createDiveDraftFromPlan(plan.entityId);
    await saveDive({ ...draft, entityId: 'same-dive', site: draft.site!, date: draft.date!, maxDepthM: 12, bottomTimeMin: 38, gas: 'Air', notes: draft.notes! });
    await saveLocalRecord('trip', { entityId: plan.entityId, notes: 'Later changed plan' });
    const dive = (await listDives())[0]!;
    expect(dive).toMatchObject({ originatingPlanId: plan.entityId, siteId: plan.siteId });
    const original = await loadOriginatingPlan(dive);
    expect(original).toMatchObject({ notes: 'Original intent', futurePlanField: 'retain' });
    expect(planComparison(original!, dive)).toContainEqual(['Dive duration', 'Not recorded', '38 min']);
    const backup = await localBackupPayload();
    for (const table of zeustekDb.tables) await table.clear();
    await restoreLocalPayload(backup);
    expect(await loadOriginatingPlan((await listDives())[0]!)).toMatchObject({ notes: 'Original intent' });
    expect(await zeustekDb.entities.count()).toBe(2);
    configureDiveStore('other-account'); expect(await loadOriginatingPlan(dive)).toBeNull();
  });
  it('retains a legacy cloud Plan revision in the unsaved draft without changing its history or fields', async () => {
    await zeustekDb.entities.put({ entityId: 'dive:context-test:same-plan', module: 'dive:context-test', entityType: 'trip', schemaVersion: 1, record: { ...plan, modifiedAt: '2026-09-01', createdAt: '2026-09-01' }, recordHash: '', deleted: 0, updatedEventId: '', updatedAt: '2026-09-01' });
    const draft = await createDiveDraftFromPlan(plan.entityId);
    expect(draft.originatingPlanRevision?.eventId).toBeTruthy();
    expect(await zeustekDb.entities.count()).toBe(1);
    expect(await zeustekDb.events.count()).toBe(0);
    expect(await loadOriginatingPlan(draft as never)).toMatchObject({ futurePlanField: 'retain', siteId: 'same-site' });
    await expect(createDiveDraftFromPlan('missing')).rejects.toThrow('Load this Dive Plan');
    expect(await loadOriginatingPlan({ originatingPlanId: plan.entityId } as never)).toBeNull();
  });
  it('links and unlinks shared evidence without copying or deleting the evidence, skill or attachment', async () => {
    await saveLocalRecord('skill_evidence', { entityId: 'existing-evidence', skillKey: 'buoyancy', performedAt: '2026-09-12', attachmentIds: ['same-asset'], notes: 'Recorded session' });
    await saveDive({ entityId: 'same-dive', site: 'Capernwray', date: '2026-09-12', maxDepthM: 12, bottomTimeMin: 38, gas: 'Air', notes: '' });
    const before = (await listSkillEvidence())[0];
    await saveDivePerspective('same-dive', { debrief: { skillEvidenceIds: ['existing-evidence'] } });
    expect((await listDives())[0]?.debrief?.skillEvidenceIds).toEqual(['existing-evidence']);
    await saveDivePerspective('same-dive', { debrief: { skillEvidenceIds: [] } });
    expect((await listSkillEvidence())[0]).toEqual(before);
    expect(await zeustekDb.entities.count()).toBe(2);
  });
  it('creates one canonical Skill and persists add, reopen, edit, unlink, relink and explicit evidence delete offline',async()=>{
    await saveDive({entityId:'skill-dive',site:'Training quarry',date:'2026-09-12',timeIn:'10:00',timeOut:'10:40',maxDepthM:12,bottomTimeMin:40,gas:'Air',notes:''});
    const first=await createCanonicalSkill({name:' DSMB   deployment ',group:'DSMB & ascent'});
    const repeated=await createCanonicalSkill({name:'dsmb deployment',group:'Other'});
    expect(repeated.entityId).toBe(first.entityId);
    expect(await listCanonicalSkills()).toHaveLength(1);
    const created=await saveDiveSkillEvidence('skill-dive',{skillKey:first.skillKey!,performedAt:'2026-09-12T10:40:00.000Z',environment:'Quarry',assessment:'Controlled ascent',competenceLevel:3,confidenceLevel:4,evaluatorPersonId:null,equipmentSetId:null,attachmentIds:['existing-asset'],notes:'Stable stop'});
    expect(created.evidence).toMatchObject({diveId:'skill-dive',skillKey:first.skillKey,attachmentIds:['existing-asset']});
    expect((await listDives()).find(item=>item.entityId==='skill-dive')?.debrief?.skillEvidenceIds).toEqual([created.evidence.entityId]);
    await zeustekDb.close();await zeustekDb.open();
    expect((await listSkillEvidence())[0]).toMatchObject({entityId:created.evidence.entityId,diveId:'skill-dive',notes:'Stable stop'});
    await saveDiveSkillEvidence('skill-dive',{...created.evidence,entityId:created.evidence.entityId,notes:'Edited after review',confidenceLevel:5});
    expect(await listSkillEvidence()).toHaveLength(1);
    expect((await listSkillEvidence())[0]).toMatchObject({notes:'Edited after review',confidenceLevel:5});
    await unlinkSkillEvidenceFromDive('skill-dive',created.evidence.entityId);
    expect((await listDives()).find(item=>item.entityId==='skill-dive')?.debrief?.skillEvidenceIds).toEqual([]);
    expect((await listSkillEvidence())[0]?.diveId).toBeNull();
    expect(await listCanonicalSkills()).toHaveLength(1);
    await linkSkillEvidenceToDive('skill-dive',created.evidence.entityId);
    expect((await listSkillEvidence())[0]?.diveId).toBe('skill-dive');
    await deleteDiveSkillEvidence('skill-dive',created.evidence.entityId);
    expect(await listSkillEvidence()).toHaveLength(0);
    expect(await listCanonicalSkills()).toHaveLength(1);
    expect((await listDives()).find(item=>item.entityId==='skill-dive')?.debrief?.skillEvidenceIds).toEqual([]);
    expect(fetch).not.toHaveBeenCalled();
  });
  it('stores stable Skill competence levels while retaining legacy evidence values',async()=>{
    await saveDive({entityId:'competence-dive',site:'Training quarry',date:'2026-09-13',timeIn:'10:00',timeOut:'10:40',maxDepthM:12,bottomTimeMin:40,gas:'Air',notes:''});
    const skill=await createCanonicalSkill({name:'Air-sharing stop control',group:'Buoyancy & Trim',competenceDefinitions:{foundation:'Coached',developing:'Corrections',competent:'Reliable',advanced:'Communicates',mastered:'Automatic'}});
    const created=await saveDiveSkillEvidence('competence-dive',{skillKey:skillRecordKey(skill),performedAt:'2026-09-13T10:20:00.000Z',competenceLevel:'advanced',assessment:''});
    expect(created.evidence.competenceLevel).toBe('advanced');
    await updateCanonicalSkill(skill.entityId,{name:'Air-sharing stop control',group:'Buoyancy & Trim',competenceDefinitions:{foundation:'Coached',developing:'Corrections',competent:'Reliable',advanced:'Updated definition',mastered:'Automatic'}});
    expect((await listSkillEvidence())[0]?.competenceLevel).toBe('advanced');
    await zeustekDb.close(); await zeustekDb.open();
    expect((await listSkillEvidence())[0]?.competenceLevel).toBe('advanced');
    await saveLocalRecord('skill_evidence',{entityId:'legacy-level',skillKey:skill.entityId,performedAt:'2026-09-13T10:25:00.000Z',competenceLevel:4,assessment:'Older free-text assessment'});
    expect((await listSkillEvidence()).find(item=>item.entityId==='legacy-level')).toMatchObject({competenceLevel:4,assessment:'Older free-text assessment'});
    await expect(saveDiveSkillEvidence('competence-dive',{skillKey:skill.entityId,performedAt:'2026-09-13T10:30:00.000Z',competenceLevel:'expert' as never})).rejects.toThrow('recognised level');
  });
  it('resolves distinct canonical Skill references for display and controls unavailable historical references',async()=>{
    const trim=await createCanonicalSkill({name:'Trim',group:'Buoyancy & trim'});
    const hover=await createCanonicalSkill({name:'Hover',group:'Buoyancy & trim'});
    const skills=await listCanonicalSkills();
    const first={entityId:'evidence-trim',skillKey:trim.entityId,performedAt:'2026-09-05T11:34:00.000Z'};
    const second={entityId:'evidence-hover',skillKey:skillRecordKey(hover),performedAt:'2026-09-05T11:36:00.000Z'};
    expect(skillEvidenceDisplayName(first,skills)).toBe('Trim');
    expect(skillEvidenceDisplayName(second,skills)).toBe('Hover');
    expect(resolveCanonicalSkillReference(first.skillKey,skills)?.entityId).toBe(trim.entityId);
    expect(skillEvidenceDisplayName({entityId:'legacy',skillKey:'missing-canonical-id'},skills)).toBe('Unknown / unavailable Skill');
    expect(first.skillKey).toBe(trim.entityId);
  });
  it('previews and creates 20 canonical Skills with blanks and case/whitespace duplicates excluded, then persists offline',async()=>{
    const trim=await createCanonicalSkill({name:'Trim',group:'Buoyancy & trim'});
    const twenty=Array.from({length:20},(_,index)=>`Training skill ${String(index+1).padStart(2,'0')}`);
    const preview=previewCanonicalSkillBatch(['Trim',' trim ','',...twenty].join('\n'),await listCanonicalSkills());
    expect(preview).toMatchObject({submittedCount:22,blankCount:1,newSkills:twenty,existingSkills:['Trim','trim'],duplicateSkills:[]});
    expect(previewCanonicalSkillBatch('Hover\n hover \nHOVER',[])).toMatchObject({newSkills:['Hover'],duplicateSkills:['hover','HOVER']});
    await createCanonicalSkills(preview.newSkills);
    expect(await listCanonicalSkills()).toHaveLength(21);
    await zeustekDb.close();await zeustekDb.open();
    expect(await listCanonicalSkills()).toHaveLength(21);
    await saveDive({entityId:'catalogue-dive',site:'Quarry',date:'2026-09-13',maxDepthM:10,bottomTimeMin:30,gas:'Air',notes:''});
    const selected=(await listCanonicalSkills()).find(skill=>skill.name==='Training skill 20')!;
    const result=await saveDiveSkillEvidence('catalogue-dive',{skillKey:skillRecordKey(selected),performedAt:'2026-09-13T10:30:00.000Z'});
    expect(skillEvidenceDisplayName(result.evidence,await listCanonicalSkills())).toBe('Training skill 20');
    await setCanonicalSkillArchived(selected.entityId,true);
    expect(skillEvidenceDisplayName(result.evidence,await listCanonicalSkills())).toBe('Training skill 20');
    await expect(updateCanonicalSkill(selected.entityId,{name:' trim '})).rejects.toThrow('already exists');
    expect((await listCanonicalSkills()).find(skill=>skill.entityId===trim.entityId)?.name).toBe('Trim');
    expect(fetch).not.toHaveBeenCalled();
  });
  it('adds rich fields without invalidating legacy Skills or changing historical evidence references',async()=>{
    await saveLocalRecord('skill',{entityId:'legacy-skill',skillKey:'legacy-skill',name:'Legacy hover'});
    expect(skillRecordGroup((await listCanonicalSkills())[0]!)).toBe('Uncategorised');
    const beforeKey='legacy-skill';
    await saveLocalRecord('skill_evidence',{entityId:'legacy-evidence',skillKey:beforeKey,performedAt:'2026-09-13'});
    const updated=await updateCanonicalSkill('legacy-skill',{name:'Legacy hover',group:'Buoyancy & Trim',description:'Hold depth and position.',competenceDefinitions:{foundation:'With coaching',developing:'Regular corrections',competent:'Reliable',advanced:'Stable under task load',mastered:'Automatic'}});
    expect(updated.competenceDefinitions?.mastered).toBe('Automatic');
    expect((await listSkillEvidence())[0]?.skillKey).toBe(beforeKey);
    expect(skillEvidenceDisplayName((await listSkillEvidence())[0]!,await listCanonicalSkills())).toBe('Legacy hover');
  });
  it('deletes only zero-reference archived Skills and protects referenced history through the canonical tombstone path',async()=>{
    const unused=await createCanonicalSkill({name:'Disposable unused',group:'Other'});
    const protectedSkill=await createCanonicalSkill({name:'Referenced history',group:'Other'});
    await setCanonicalSkillArchived(unused.entityId,true); await setCanonicalSkillArchived(protectedSkill.entityId,true);
    await saveLocalRecord('skill_evidence',{entityId:'historical-evidence',skillKey:protectedSkill.entityId,performedAt:'2026-09-13'});
    const preview=await previewUnusedArchivedSkills();
    expect(preview).toMatchObject({archivedCount:2});
    expect(preview.eligible.map(item=>item.skill.entityId)).toEqual([unused.entityId]);
    expect(preview.protected.map(item=>item.skill.entityId)).toEqual([protectedSkill.entityId]);
    await expect(deleteUnusedArchivedSkills([unused.entityId,protectedSkill.entityId])).rejects.toThrow('references changed');
    expect(await deleteUnusedArchivedSkills([unused.entityId])).toBe(1);
    expect((await listCanonicalSkills()).map(item=>item.entityId)).toEqual([protectedSkill.entityId]);
    expect((await listSkillEvidence())[0]?.skillKey).toBe(protectedSkill.entityId);
    expect((await zeustekDb.settings.where('key').startsWith('pending:dive:context-test:').toArray()).some(row=>row.key.endsWith(unused.entityId))).toBe(true);
  });
  it('retains media metadata and featured IDs after offline restart; no binaries or network are needed', async () => {
    const items = [{ id: 'same-asset', fileName: 'Dive.jpg', contentType: 'image/jpeg', caption: 'Original' }];
    vi.stubGlobal('navigator', { onLine: true });
    const network = vi.fn(async () => Response.json({ items })); vi.stubGlobal('fetch', network);
    expect(await loadMediaMetadata('dive', 'same-dive')).toEqual({ items, unavailable: false });
    vi.stubGlobal('navigator', { onLine: false });
    await saveDive({ entityId: 'same-dive', site: 'Capernwray', date: '2026-09-12', maxDepthM: 12, bottomTimeMin: 38, gas: 'Air', notes: '' });
    await saveDivePerspective('same-dive', { story: { featuredAttachmentIds: ['same-asset'] } });
    await zeustekDb.close(); await zeustekDb.open(); network.mockClear();
    expect(await loadMediaMetadata('dive', 'same-dive')).toEqual({ items, unavailable: true });
    expect((await listDives())[0]?.story?.featuredAttachmentIds).toEqual(['same-asset']);
    expect(network).not.toHaveBeenCalled();
    expect(await zeustekDb.attachmentChunks.count()).toBe(0);
    configureDiveStore('other-account'); expect((await loadMediaMetadata('dive', 'same-dive')).items).toEqual([]);
  });
  it('blocks switch/close/navigation until local save succeeds; failed drafts require explicit retry', async () => {
    const writes = new DiveEditorWrites(); let release!: () => void;
    const pending = writes.enqueue(() => new Promise<void>(resolve => { release = resolve; }));
    const navigate = vi.fn(); const leaving = writes.afterSaved(navigate);
    await Promise.resolve(); expect(navigate).not.toHaveBeenCalled();
    let releaseSecond!: () => void;
    const second = writes.enqueue(() => new Promise<void>(resolve => { releaseSecond = resolve; }));
    release(); await pending; await Promise.resolve(); expect(navigate).not.toHaveBeenCalled();
    releaseSecond(); await second; await leaving;
    expect(navigate).toHaveBeenCalledOnce();
    await expect(writes.enqueue(async () => { throw new Error('Storage full'); })).rejects.toThrow('Storage full');
    const close = vi.fn(); await expect(writes.afterSaved(close)).rejects.toThrow('Storage full'); expect(close).not.toHaveBeenCalled();
    const retry = vi.fn(async () => {}); await writes.retry(retry); await writes.afterSaved(close);
    expect(retry).toHaveBeenCalledOnce(); expect(close).toHaveBeenCalledOnce();
  });
});
