import {describe,it,expect} from 'vitest';
import {deriveDiveDayNumbers,previewDiveOfDay} from '../lib/logbook/dive-of-day';
const dive=(entityId:string,date='2026-10-04',timeIn='09:00',diveNumber=68)=>({entityId,date,timeIn,diveNumber});
describe('Derived Dive of the day',()=>{
 it('starts01 on each date independently of lifetime numbering',()=>{const rows=[dive('a'),dive('b','2026-10-05','08:00',69)];const result=deriveDiveDayNumbers(rows);expect(result.get('a')).toMatchObject({number:1,label:'01',provisional:false});expect(result.get('b')?.label).toBe('01');});
 it('orders by start time, never storage order',()=>{const result=deriveDiveDayNumbers([dive('late','2026-10-04','13:30'),dive('early')]);expect(result.get('early')?.label).toBe('01');expect(result.get('late')?.label).toBe('02');});
 it('uses seconds when present and handles more than nine dives',()=>{const result=deriveDiveDayNumbers(Array.from({length:11},(_,i)=>dive('d'+i,'2026-10-04','09:00:'+String(i).padStart(2,'0'))));expect(result.get('d0')?.label).toBe('01');expect(result.get('d10')?.label).toBe('11');});
 it('has stable same-time tie ordering and labels it provisional',()=>{const rows=[dive('b','2026-10-04','09:00',70),dive('a','2026-10-04','09:00',68)];expect(deriveDiveDayNumbers(rows).get('a')).toMatchObject({label:'01',provisional:true});expect([...deriveDiveDayNumbers(rows)].sort(([a],[b])=>a.localeCompare(b))).toEqual([...deriveDiveDayNumbers([...rows].reverse())].sort(([a],[b])=>a.localeCompare(b)));});
 it('puts unknown times after known ones and does not assert a confirmed chronological order',()=>{const result=deriveDiveDayNumbers([dive('unknown','2026-10-04',''),dive('known')]);expect(result.get('known')).toMatchObject({label:'01',provisional:true});expect(result.get('unknown')).toMatchObject({label:'02',provisional:true});});
 it('never groups missing, month-only or invalid calendar dates into an invented day',()=>{for(const date of ['', '2026-10','2026-02-30'])expect(deriveDiveDayNumbers([dive('a',date)]).get('a')).toMatchObject({number:null,label:'—'});});
 it('updates the draft preview when its date/time changes without writing any record',()=>{const rows=[dive('a'),dive('b','2026-10-04','12:00')];const before=JSON.stringify(rows);expect(previewDiveOfDay({date:'2026-10-04',timeIn:'10:00'},rows).label).toBe('02');expect(previewDiveOfDay({date:'2026-10-05',timeIn:'10:00'},rows).label).toBe('01');expect(JSON.stringify(rows)).toBe(before);});
 it('excludes the old version of the edited Dive rather than counting it twice',()=>{const rows=[dive('a'),dive('b','2026-10-04','12:00')];expect(previewDiveOfDay({...rows[0]!,timeIn:'13:00'},rows).label).toBe('02');});
 it('deduplicates repeated canonical references without rewriting lifetime IDs or records',()=>{const row=dive('a');const rows=[row,{...row}];const before=JSON.stringify(rows);expect(deriveDiveDayNumbers(rows).size).toBe(1);expect(deriveDiveDayNumbers(rows).get('a')?.label).toBe('01');expect(JSON.stringify(rows)).toBe(before);});
});
