import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {readFileSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {SevenDayForecastCard} from '../components/weather/overview-conditions';
import {overviewForecast} from '../lib/weather/overview-forecast';
import {conditionReading,type ConditionsSnapshot,type ConditionMetric} from '../lib/weather/conditions-model';

const source={provider:'xweather' as const,kind:'model' as const,classification:'forecast' as const,label:'Vaisala Xweather',attribution:'Powered by Vaisala Xweather',url:'https://www.xweather.com/',resolution:'hourly',latitude:50,longitude:-2,retrievedAt:'2026-10-04T15:16:00Z',timeZone:'UTC'};
const reading=(metric:ConditionMetric,value:number|string,unit:string,date:string,extra={})=>conditionReading(metric,value,unit,{...source,validAt:date+'T12:00:00Z',...extra})!;
const snapshot=(readings:ConditionsSnapshot['readings']):ConditionsSnapshot=>({version:1,request:{siteId:'site',siteName:'Coast',siteType:'coastal',latitude:50,longitude:-2,marine:true,date:'2026-10-04',time:'12:00',mode:'forecast',provider:'xweather'},readings,retrievedAt:source.retrievedAt,diagnostics:[]});
const week=Array.from({length:7},(_,i)=>'2026-10-'+String(i+4).padStart(2,'0'));
const html=(data:ConditionsSnapshot)=>renderToStaticMarkup(createElement(SevenDayForecastCard,{site:{entityId:'site',name:'Coast',location:'North coast'},forecast:overviewForecast(data)}));

describe('Overview forecast completeness and truthful detail',()=>{
 it('renders all seven returned dates rather than four compressed tiles',()=>{const rendered=html(snapshot(week.flatMap(date=>[reading('air-temperature',16,'°C',date),reading('wind-speed',9,'m/s',date)])));for(const date of week)expect(rendered).toMatch(new RegExp('datetime="'+date+'"','i'));expect((rendered.match(/class="forecast-day"/g)??[])).toHaveLength(7);});
 it('shows both temperature extrema, weather and labelled wind/gust data',()=>{const rendered=html(snapshot([reading('air-temperature',8,'°C',week[0]!,{validAt:week[0]+'T06:00:00Z'}),reading('air-temperature',16,'°C',week[0]!),reading('wind-speed',9,'m/s',week[0]!),reading('wind-gust',14,'m/s',week[0]!),reading('weather','Rain showers','text',week[0]!),reading('wind-direction',270,'°',week[0]!)]));expect(rendered).toContain('8–16');expect(rendered).toContain('Rain showers');expect(rendered).toContain('Gust');expect(rendered).toContain('Wind from');expect(rendered).toContain('270');});
 it('renders one linked source attribution and one retrieval time without repeating its name',()=>{const rendered=html(snapshot([reading('air-temperature',16,'°C',week[0]!)]));expect((rendered.match(/Vaisala Xweather/g)??[])).toHaveLength(1);expect(rendered).toContain('2026-10-04 15:16 UTC');});
 it('does not imply missing provider days were returned',()=>{const rendered=html(snapshot([reading('air-temperature',16,'°C',week[0]!)]));expect(rendered).toContain('1 of 7 days available');expect((rendered.match(/class="forecast-day"/g)??[])).toHaveLength(1);});
 it('keeps missing extrema and winds unknown rather than zero',()=>{const rendered=html(snapshot([reading('air-temperature',16,'°C',week[0]!,{resolution:'UTC-day forecast average'})]));expect(rendered).toContain('UTC-day average');expect(rendered).toContain('Wind unknown');expect(rendered).not.toContain('0 mph');});
 it('does not pool competing atmosphere models',()=>{const forecast=overviewForecast(snapshot([reading('air-temperature',16,'°C',week[0]!),reading('air-temperature',40,'°C',week[0]!,{provider:'tomorrow',label:'Tomorrow.io'})]));expect(forecast.days[0]?.maximumC).toBe(16);});
 it('shares one attribution when atmosphere and marine have the same provider link and displayed retrieval minute',()=>{const rendered=html(snapshot([reading('air-temperature',16,'°C',week[0]!),reading('wave-height',1.2,'m',week[0]!,{label:'Vaisala Xweather Maritime',retrievedAt:'2026-10-04T15:16:20Z'})]));expect((rendered.match(/Powered by Vaisala Xweather/g)??[])).toHaveLength(1);expect(rendered).toContain('Wave height');});
 it('does not relabel a daily mean wind as a forecast peak',()=>{const data=snapshot([reading('air-temperature',16,'°C',week[0]!,{resolution:'UTC-day forecast average'}),reading('wind-speed',9,'m/s',week[0]!,{resolution:'UTC-day forecast average'})]);expect(overviewForecast(data).days[0]).toMatchObject({windMaximumMps:null,windAverageMps:9});const rendered=html(data);expect(rendered).toContain('mph UTC-day average');expect(rendered).not.toContain('Up to');});
 it('includes independent marine forecast details and their attribution without crediting observations as forecast',()=>{const data=snapshot([reading('air-temperature',16,'°C',week[0]!),reading('wave-height',1.2,'m',week[0]!,{provider:'wwo',label:'World Weather Online',attribution:'World Weather Online marine',url:'https://www.worldweatheronline.com/'}),reading('wave-period',8,'s',week[0]!,{provider:'wwo',label:'World Weather Online',attribution:'World Weather Online marine',url:'https://www.worldweatheronline.com/'}),reading('water-temperature',12,'°C',week[0]!,{provider:'zeustek',classification:'observed',label:'Saved Dive observation',observedAt:week[0]+'T12:00:00Z',depth:{kind:'surface'}})]);const before=JSON.stringify(data);const rendered=html(data);expect(rendered).toContain('Wave height');expect(rendered).toContain('Wave period');expect(rendered).toContain('World Weather Online marine');expect(rendered).not.toContain('Saved Dive observation');expect(JSON.stringify(data)).toBe(before);});
 it('never hides dates five onward at mobile breakpoints',()=>{const css=readFileSync('app/focus.css','utf8');expect(css).not.toMatch(/\.forecast-days>div:nth-child\(n\+5\)[^{]*\{display:none/);});
 it('removes only the two owner-requested Overview cards and compact forecast mode',()=>{const dashboard=readFileSync('app/dashboard-client.tsx','utf8');const overview=dashboard.slice(dashboard.indexOf('function Overview('),dashboard.indexOf('function StatusRow('));expect(overview).not.toContain('overview-profile-card');expect(overview).not.toContain('overview-buddy-card');expect(overview).not.toMatch(/<SevenDayForecastCard[^>]+compact/);expect(overview).toContain('HOME DIVE FORECASTS');});
});
