import 'fake-indexeddb/auto';
import {DatabaseSync} from 'node:sqlite';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {zeustekDb} from '../lib/offline/db';
import {configureDiveStore,cacheSavedRecord,saveLocalRecord,deleteLocalRecord,listLocalDiveRecords} from '../lib/offline/dive-store';
import {diveEntityWriteConstraint} from '../lib/operators/dive-log-write-boundary';
import {OPERATOR_DELETE_CONSTRAINT,operatorDeleteBindings} from '../lib/operators/operator-dependencies';
import {localBackupPayload,restoreLocalPayload} from '../lib/offline/local-backup';
beforeEach(async()=>{vi.stubGlobal('window',new EventTarget());vi.stubGlobal('navigator',{onLine:false});vi.stubGlobal('fetch',vi.fn());configureDiveStore('centre-owner');await zeustekDb.open();for(const table of zeustekDb.tables)await table.clear();});afterEach(()=>vi.unstubAllGlobals());
describe.each(['trip','dive-trip'])('Canonical Dive Centre contacts on %s',kind=>{
 it('rejects new unavailable centre references before writing or creating any Person, and retains historical references',async()=>{await expect(saveLocalRecord(kind,{name:'Dummy',diveCentreIds:['missing']})).rejects.toThrow(/unavailable/i);expect(await zeustekDb.entities.count()).toBe(0);await cacheSavedRecord(kind,'historical',{name:'Old',diveCentreIds:['historical-centre']});await saveLocalRecord(kind,{entityId:'historical',notes:'Reviewed edit',diveCentreIds:['historical-centre']});expect(await listLocalDiveRecords('person')).toEqual([]);});
 it('persists exact centre IDs through edit and backup, and protects deletion until an explicit unlink',async()=>{await saveLocalRecord('operator',{entityId:'centre',name:'Same name',phone:'+44 123',operatorType:'dive-centre'});await saveLocalRecord('person',{entityId:'human',name:'Same name',role:'buddy'});await saveLocalRecord(kind,{entityId:'planned',name:'Dummy',diveCentreIds:['centre'],notes:'Original'});const backup=await localBackupPayload();for(const table of zeustekDb.tables)await table.clear();await restoreLocalPayload(backup);expect((await listLocalDiveRecords(kind))[0]).toMatchObject({entityId:'planned',diveCentreIds:['centre'],notes:'Original'});const before=JSON.stringify(await zeustekDb.entities.toArray());await expect(deleteLocalRecord('centre')).rejects.toThrow(/link/i);expect(JSON.stringify(await zeustekDb.entities.toArray())).toBe(before);await saveLocalRecord(kind,{entityId:'planned',diveCentreIds:[]});await deleteLocalRecord('centre');expect((await listLocalDiveRecords(kind))[0]).toMatchObject({notes:'Original',diveCentreIds:[]});expect(await listLocalDiveRecords('person')).toHaveLength(1);});
 it('uses same-statement owner verification and deletion protection for a stale cloud client',()=>{const db=new DatabaseSync(':memory:');try{db.exec('CREATE TABLE dive_records (id TEXT PRIMARY KEY,user_id TEXT,kind TEXT,data_json TEXT,deleted_at INTEGER)');const add=db.prepare('INSERT INTO dive_records VALUES (?,?,?,?,NULL)');add.run('centre','owner','operator','{}');add.run('private','other','operator','{}');const input={diveCentreIds:['centre','private']};const guard=diveEntityWriteConstraint(kind,input,{},'owner');expect(guard.bindings).toHaveLength(4);const write=db.prepare('INSERT INTO dive_records SELECT ?,?,?,?,NULL WHERE 1=1'+guard.sql);expect(write.run('planned','owner',kind,JSON.stringify(input),...guard.bindings).changes).toBe(0);const valid=diveEntityWriteConstraint(kind,{diveCentreIds:['centre']},{},'owner');expect(db.prepare('INSERT INTO dive_records SELECT ?,?,?,?,NULL WHERE 1=1'+valid.sql).run('planned','owner',kind,JSON.stringify({diveCentreIds:['centre']}),...valid.bindings).changes).toBe(1);const remove=db.prepare('UPDATE dive_records SET deleted_at=1 WHERE id=? AND user_id=?'+OPERATOR_DELETE_CONSTRAINT);expect(remove.run('centre','owner',...operatorDeleteBindings('owner','centre')).changes).toBe(0);db.prepare('UPDATE dive_records SET user_id=? WHERE id=?').run('other','planned');expect(remove.run('centre','owner',...operatorDeleteBindings('owner','centre')).changes).toBe(1);}finally{db.close();}});
});
