import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {describe,it,expect} from 'vitest';
import {PlanningDiveCentres} from '../components/planning/planning-dive-centres';
import {PlanConditionFields} from '../components/planning/plan-condition-fields';
import {PlanEditor} from '../components/dive-planning-centre';
import {TripEditor} from '../components/trips-expeditions';
import type {OperatorRecord,Stored} from '../lib/offline/dive-planning';
import {API_FIELDS,validateApiKeyInput} from '../lib/sharing/readonly-api';
const base={website:'',notes:'',createdAt:'2026-10-05T00:00:00Z',modifiedAt:'2026-10-05T00:00:00Z'};
const centres:Array<Stored<OperatorRecord>>=[{...base,entityId:'centre-a',name:'Fixture Centre',operatorType:'dive-centre',phone:'+44 12345',email:'fixture@example.invalid',location:'Port'},{...base,entityId:'centre-b',name:'Fixture Centre',operatorType:'dive-centre',phone:'javascript:alert(1)',location:'Different port',active:false}];
describe('Private planning contacts and ordered environmental form',()=>{
 it('both real editors offer canonical centres separately from People, including new and legacy records',()=>{for(const html of [renderToStaticMarkup(createElement(PlanEditor,{item:null,sites:[],people:[],centres,loadouts:[],trips:[],skills:[],gasPlans:[],close:()=>{},saved:()=>{}})),renderToStaticMarkup(createElement(TripEditor,{item:null,items:[],plans:[],sites:[],people:[],centres,equipment:[],equipmentSets:[],currentUserId:'fixture-owner',sourceBooking:null,close:()=>{},saved:()=>{}}))]){expect(html).toContain('Dive Centre contacts');expect(html).toContain('value="centre-a"');expect(html).toContain('Add Dive Centre / operator');expect(html).not.toContain('value="centre-b"');}});
 it('displays exact contact links, preserves unavailable/inactive references and safely renders phone/text injection',()=>{const html=renderToStaticMarkup(createElement(PlanningDiveCentres,{ids:['centre-a','centre-b','missing'],centres,change:()=>{}}));expect(html).toContain('tel:+4412345');expect(html).toContain('Phone:');expect(html).toContain('operatorId=centre-a');expect(html).toContain('inactive');expect(html).toContain('Unavailable Dive Entity');expect(html).not.toContain('href="javascript:');expect(html).toContain('Remove Fixture Centre contact');const safe=renderToStaticMarkup(createElement(PlanningDiveCentres,{ids:['attack'],centres:[{...centres[0]!,entityId:'attack',name:'<script>attack</script>'}]}));expect(safe).not.toContain('<script>');expect(safe).toContain('&lt;script&gt;');});
 it('keeps the ordered groups, paired limits and full-width notes without source labels on manual fields',()=>{const html=renderToStaticMarkup(createElement(PlanConditionFields,{draft:{conditions:{waterTemperatureC:10,visibilityM:6},minimumVisibilityM:3,maximumWaveHeightM:2},change:()=>{},changeWeather:()=>{}}));const labels=['Water conditions','Water temperature','Visibility (m)','Minimum visibility','Current','Unacceptable current','Surface conditions','Wave height','Maximum waves','Swell (m)','Maximum swell','Access &amp; logistics','Access permit required','Permit confirmed','Entry cost','Notes','Conditions notes'];const offsets=labels.map(label=>html.indexOf(label));expect(offsets.every(offset=>offset>=0)).toBe(true);expect(offsets).toEqual([...offsets].sort((a,b)=>a-b));expect(html).toContain('value="10"');expect(html).toContain('value="6"');expect(html).toContain('Your planning limit');expect(html).not.toContain('>Weather<');});
 it('keeps new contact IDs and weather source objects outside integration consent, including attempted field opt-in',()=>{for(const scope of ['trips','dive-plans'] as const){expect(API_FIELDS[scope]).not.toContain('diveCentreIds');expect(()=>validateApiKeyInput({client:'ZeusTek',expiresAt:'2026-10-10',scopes:[scope],selection:{[scope]:{ids:['fixture'],fields:['diveCentreIds']}}},Date.parse('2026-10-05'))).toThrow(/supported fields/);}});
});
