import 'fake-indexeddb/auto';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {configureDiveStore,listLocalDiveRecords,saveLocalRecord} from '../lib/offline/dive-store';
import {zeustekDb} from '../lib/offline/db';
import {savePlanDraftWithConnections} from '../lib/planning/calendar-plan-creation';
import type {StoredGasPlanRecord} from '../lib/offline/planning-pages';
import type {EnrichedDivePlan} from '../lib/offline/dive-planning-centre';
beforeEach(async()=>{vi.stubGlobal('window',new EventTarget());vi.stubGlobal('navigator',{onLine:false});vi.stubGlobal('fetch',vi.fn());configureDiveStore('gas-link-review');await zeustekDb.open();for(const table of zeustekDb.tables)await table.clear();});
afterEach(()=>vi.unstubAllGlobals());
async function seed(inverseOnly=false){
 await saveLocalRecord('trip',{entityId:'plan',name:'Plan',status:'planned',lifecycleStatus:'draft',notes:'Keep Plan notes',gasPlanLinks:inverseOnly?[]:[{gasPlanId:'gas',name:'Gas'}]});
 await saveLocalRecord('gas-plan',{entityId:'gas',name:'Gas',status:'draft',divePlanId:'plan',cylinders:[],notes:'Keep Gas notes',futureField:{keep:true}});
 return {plan:(await listLocalDiveRecords<EnrichedDivePlan>('trip'))[0]!,gas:await listLocalDiveRecords<StoredGasPlanRecord>('gas-plan')};
}
const save=({plan,gas}:Awaited<ReturnType<typeof seed>>,selected:string[]=[])=>savePlanDraftWithConnections({...plan,entityId:plan.entityId},gas,selected,[],plan);
describe('Reviewed Plan Gas deselection reconciles both ends',()=>{
 it('removes the deselected inverse while preserving the Plan, Gas details and unrelated Gas links',async()=>{const reviewed=await seed();await saveLocalRecord('gas-plan',{entityId:'other',name:'Other',divePlanId:'other-plan',notes:'Unrelated'});await save(reviewed);expect((await listLocalDiveRecords<EnrichedDivePlan>('trip'))[0]).toMatchObject({notes:'Keep Plan notes',gasPlanLinks:[]});expect((await listLocalDiveRecords<StoredGasPlanRecord>('gas-plan')).find(r=>r.entityId==='gas')).toMatchObject({divePlanId:null,notes:'Keep Gas notes',futureField:{keep:true}});expect((await listLocalDiveRecords<StoredGasPlanRecord>('gas-plan')).find(r=>r.entityId==='other')).toMatchObject({divePlanId:'other-plan',notes:'Unrelated'});});
 it('clears an inverse-only prior link even when the Plan has no forward snapshot',async()=>{const reviewed=await seed(true);await save(reviewed);expect((await listLocalDiveRecords<StoredGasPlanRecord>('gas-plan'))[0]!.divePlanId).toBeNull();});
 it('rejects stale deselected Gas evidence before altering either endpoint',async()=>{const reviewed=await seed();await saveLocalRecord('gas-plan',{...reviewed.gas[0],notes:'New owner Gas notes'});await expect(save(reviewed)).rejects.toThrow(/Gas Plan changed/i);expect((await listLocalDiveRecords<EnrichedDivePlan>('trip'))[0]!.gasPlanLinks).toHaveLength(1);expect((await listLocalDiveRecords<StoredGasPlanRecord>('gas-plan'))[0]).toMatchObject({divePlanId:'plan',notes:'New owner Gas notes'});});
 it('rejects a conflicted deselected Gas without changing Plan links',async()=>{const reviewed=await seed(),key='pending:dive:gas-link-review:gas',pending=(await zeustekDb.settings.get(key))!;await zeustekDb.settings.put({...pending,value:{...pending.value as object,state:'conflict'}});await expect(save(reviewed)).rejects.toThrow(/Gas Plan changed/i);expect((await listLocalDiveRecords<EnrichedDivePlan>('trip'))[0]!.gasPlanLinks).toHaveLength(1);});
 it('an inverse-link write failure rolls back Plan, Gas, history and outbox',async()=>{const reviewed=await seed();const before=await Promise.all([zeustekDb.entities.toArray(),zeustekDb.events.toArray(),zeustekDb.outbox.toArray(),zeustekDb.settings.toArray()]);const original=zeustekDb.events.add.bind(zeustekDb.events),spy=vi.spyOn(zeustekDb.events,'add').mockImplementationOnce(original).mockRejectedValueOnce(new Error('Fixture inverse Gas failure'));await expect(save(reviewed)).rejects.toThrow('Fixture inverse Gas failure');spy.mockRestore();expect(await Promise.all([zeustekDb.entities.toArray(),zeustekDb.events.toArray(),zeustekDb.outbox.toArray(),zeustekDb.settings.toArray()])).toEqual(before);});
 it('rejects a newly linked inverse record that the editor has never reviewed',async()=>{const reviewed=await seed(true);await saveLocalRecord('gas-plan',{entityId:'new',name:'New Gas',divePlanId:'plan'});await expect(save(reviewed)).rejects.toThrow(/Gas Plan changed/i);expect((await listLocalDiveRecords<StoredGasPlanRecord>('gas-plan')).every(r=>r.divePlanId==='plan')).toBe(true);});
 it('keeps a still-selected prior Gas link and does not change its notes',async()=>{const reviewed=await seed();await save(reviewed,['gas']);expect((await listLocalDiveRecords<StoredGasPlanRecord>('gas-plan'))[0]).toMatchObject({divePlanId:'plan',notes:'Keep Gas notes'});expect((await listLocalDiveRecords<EnrichedDivePlan>('trip'))[0]!.gasPlanLinks.map(r=>r.gasPlanId)).toEqual(['gas']);});
});
