import 'fake-indexeddb/auto';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {configureDiveStore,deleteLocalRecord,listLocalDiveRecords,saveLocalRecord} from '../lib/offline/dive-store';
import {zeustekDb} from '../lib/offline/db';
import {readPlanningConnections,unlinkPlanningConnection} from '../lib/offline/planning-connections';
beforeEach(async()=>{vi.stubGlobal('window',new EventTarget());vi.stubGlobal('navigator',{onLine:false});vi.stubGlobal('fetch',vi.fn());configureDiveStore('unlink-test');await zeustekDb.open();for(const table of zeustekDb.tables)await table.clear();});
afterEach(()=>vi.unstubAllGlobals());
const rows=(kind:string)=>listLocalDiveRecords<Record<string,unknown>>(kind);
async function seed(){
 await saveLocalRecord('trip',{entityId:'plan',name:'Plan',tripId:'holiday',gasPlanLinks:[{gasPlanId:'gas',name:'Gas',notes:'Keep this evidence in gas source'}],notes:'Owner plan notes',futureField:{keep:true}});
 await saveLocalRecord('dive-trip',{entityId:'holiday',name:'Holiday',planIds:['plan','other-plan'],itinerary:[],notes:'Owner Trip notes'});
 await saveLocalRecord('gas-plan',{entityId:'gas',name:'Gas',divePlanId:'plan',notes:'Original gas notes',cylinders:[{fillId:'fill',analysisId:'analysis'}]});
}
describe('Explicit planning connection unlink',()=>{
 it('projects a mirrored gas association once, removes both references, and preserves all original evidence/other links',async()=>{await seed();const panel=await readPlanningConnections('plan');const link=panel.connections.find(x=>x.other.id==='gas')!;expect(panel.connections.filter(x=>x.other.id==='gas')).toHaveLength(1);await unlinkPlanningConnection(link);expect((await rows('trip'))[0]).toMatchObject({tripId:'holiday',gasPlanLinks:[],notes:'Owner plan notes',futureField:{keep:true}});expect((await rows('gas-plan'))[0]).toMatchObject({entityId:'gas',divePlanId:null,notes:'Original gas notes',cylinders:[{fillId:'fill',analysisId:'analysis'}]});expect((await rows('dive-trip'))[0]!.planIds).toEqual(['plan','other-plan']);expect(fetch).not.toHaveBeenCalled();});
 it('removes only the selected Trip/Plan association, keeping other Plans and both endpoints',async()=>{await seed();const link=(await readPlanningConnections('holiday')).connections.find(x=>x.other.id==='plan')!;await unlinkPlanningConnection(link);expect((await rows('dive-trip'))[0]!.planIds).toEqual(['other-plan']);expect((await rows('trip'))[0]!.tripId).toBeNull();expect((await rows('trip'))[0]!.gasPlanLinks).toHaveLength(1);});
 it('detaches Calendar conversion/inverse/itinerary references without deleting itinerary notes, dates or attachments',async()=>{await saveLocalRecord('trip',{entityId:'event',name:'Event',linkedTripId:'holiday',notes:'Event text'});await saveLocalRecord('dive-trip',{entityId:'holiday',name:'Holiday',originCalendarBookingId:'event',calendarBookingIds:['event','other'],itinerary:[{id:'segment',calendarBookingId:'event',title:'Boat',notes:'Keep text',attachments:[{id:'photo'}]}]});const link=(await readPlanningConnections('event')).connections[0]!;await unlinkPlanningConnection(link);expect((await rows('trip'))[0]!.linkedTripId).toBeNull();expect((await rows('dive-trip'))[0]).toMatchObject({originCalendarBookingId:null,calendarBookingIds:['other'],itinerary:[{id:'segment',calendarBookingId:null,title:'Boat',notes:'Keep text',attachments:[{id:'photo'}]}]});});
 it('retains logged Dive and skill evidence, detaching just their Plan references',async()=>{await saveLocalRecord('trip',{entityId:'plan',name:'Plan'});await saveLocalRecord('dive',{entityId:'dive',site:'Saved Site',originatingPlanId:'plan',notes:'Original Dive'});await saveLocalRecord('skill_evidence',{entityId:'skill',planId:'plan',notes:'Assessment evidence'});for(const link of (await readPlanningConnections('plan')).connections)await unlinkPlanningConnection(link);expect((await rows('dive'))[0]).toMatchObject({originatingPlanId:null,notes:'Original Dive',site:'Saved Site'});expect((await rows('skill_evidence'))[0]).toMatchObject({planId:null,notes:'Assessment evidence'});await deleteLocalRecord('plan');expect(await rows('trip')).toHaveLength(0);expect(await rows('dive')).toHaveLength(1);});
 it('keeps a linked Gas Plan undeleted, then permits recoverable deletion only after explicit unlink',async()=>{await seed();await expect(deleteLocalRecord('gas')).rejects.toThrow(/linked|unlink/i);const link=(await readPlanningConnections('gas')).connections[0]!;await unlinkPlanningConnection(link);await deleteLocalRecord('gas');expect(await rows('gas-plan')).toHaveLength(0);expect(await rows('trip')).toHaveLength(1);expect(await zeustekDb.events.where('entityId').equals('dive:unlink-test:gas').count()).toBeGreaterThan(2);});
 it('rejects a stale review without overwriting a newer note or removing either endpoint link',async()=>{await seed();const link=(await readPlanningConnections('gas')).connections[0]!;const plan=(await rows('trip'))[0]!;await saveLocalRecord('trip',{...plan,notes:'New note'});await expect(unlinkPlanningConnection(link)).rejects.toThrow(/changed|refresh/i);expect((await rows('trip'))[0]!.notes).toBe('New note');expect((await rows('gas-plan'))[0]!.divePlanId).toBe('plan');});
 it('rejects account changes and never reads or edits a different owner record',async()=>{await seed();const link=(await readPlanningConnections('gas')).connections[0]!;configureDiveStore('other-owner');await expect(unlinkPlanningConnection(link)).rejects.toThrow(/account/i);expect(await rows('gas-plan')).toHaveLength(0);configureDiveStore('unlink-test');expect((await rows('gas-plan'))[0]!.divePlanId).toBe('plan');});
 it('offers explicit removal of a missing historical endpoint while keeping its source',async()=>{await saveLocalRecord('gas-plan',{entityId:'gas',name:'Gas',divePlanId:'missing-plan',notes:'Historical'});const panel=await readPlanningConnections('gas');expect(panel.connections[0]!.other.available).toBe(false);await unlinkPlanningConnection(panel.connections[0]!);expect((await rows('gas-plan'))[0]).toMatchObject({divePlanId:null,notes:'Historical'});});
 it('rolls back every endpoint and pending mutation when a local mutation fails',async()=>{await seed();const link=(await readPlanningConnections('gas')).connections[0]!;const before=await Promise.all([rows('trip'),rows('gas-plan')]);const add=vi.spyOn(zeustekDb.events,'add').mockRejectedValueOnce(new Error('Fixture storage failure'));await expect(unlinkPlanningConnection(link)).rejects.toThrow('Fixture storage failure');add.mockRestore();expect(await Promise.all([rows('trip'),rows('gas-plan')])).toEqual(before);});
});
