import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {sharingDatabase} from './selected-sharing-fixture';
const state=vi.hoisted(()=>({db:null as unknown as D1Database,user:{userId:'fixture-owner',email:'owner@fixture.invalid',displayName:'Owner',fullName:null} as {userId:string;email:string;displayName:string;fullName:null}|null}));
vi.mock('cloudflare:workers',()=>({env:{get DB(){return state.db;}}}));
vi.mock('../app/chatgpt-auth',()=>({getChatGPTUser:async()=>state.user}));
vi.mock('../lib/server/household',()=>({OWNER_EMAIL:'owner@fixture.invalid',isLocalPreviewUser:()=>false}));
import {POST as manage} from '../app/api/integration-keys/route';
import {GET as choices} from '../app/api/integration-keys/records/route';
import {GET as contract} from '../app/api/v1/openapi/route';
import {serveApi} from '../lib/server/readonly-api';
import {API_FIELDS,API_RESOURCES,type ApiResource} from '../lib/sharing/readonly-api';
let fixture:ReturnType<typeof sharingDatabase>;
const resources=['gas-plans','dive-plans','trips'] as const;
const kinds={'gas-plans':'gas-plan','dive-plans':'trip',trips:'dive-trip'};
const rows={
  'gas-plans':{name:'Selected gas plan',status:'planned',plannedDepthM:24,plannedBottomTimeMin:35,rmvRateLitresMin:16,cylinders:[{id:'PRIVATE CYLINDER',role:'primary',gasType:'nitrox',manualOxygenFraction:0.32,startPressureBar:210,reservePressureBar:60,waterVolumeOverrideL:12,cylinderEquipmentId:'PRIVATE EQUIPMENT',serialNumber:'PRIVATE SERIAL',notes:'PRIVATE CYLINDER NOTES'}],recGasPlan101:{secret:'PRIVATE ENGINE'},notes:'PRIVATE GAS NOTES',divePlanId:'PRIVATE LINK'},
  'dive-plans':{name:'Selected dive plan',status:'planned',lifecycleStatus:'cancelled',startDate:'2026-10',endDate:'2026-10',siteName:'Chosen site',plannedMaxDepthM:22,plannedDurationMin:40,planTeam:[{personId:'PRIVATE PERSON',notes:'PRIVATE TEAM'}],emergency:{medical:'PRIVATE MEDICAL'},notes:'PRIVATE PLAN NOTES',gasPlanLinks:[{gasPlanId:'PRIVATE GAS LINK'}]},
  trips:{name:'Selected expedition',status:'confirmed',startsOn:'2026-11',endsOn:'2026-12',destination:'Chosen destination',itinerary:[{id:'PRIVATE SEGMENT ID',kind:'dive',title:'Chosen dive',startsAt:'2026-11-02T10:00',endsAt:'2026-11-02T11:00',location:'Chosen location',bookingRef:'PRIVATE BOOKING',notes:'PRIVATE NOTES',attachments:[{objectKey:'PRIVATE ATTACHMENT'}]}],guestParticipants:[{name:'PRIVATE GUEST'}],medicalNotes:'PRIVATE MEDICAL',bookings:[{amount:123,reference:'PRIVATE PAYMENT'}],organiserUserId:'PRIVATE ACCOUNT'},
};
const write=(selection:Record<string,{ids:string[];fields:readonly string[]}>)=>manage(new Request('https://fixture/api/integration-keys',{method:'POST',headers:{origin:'https://fixture','content-type':'application/json'},body:JSON.stringify({action:'create',client:'AMZeus',expiresAt:new Date(Date.now()+86400000).toISOString(),scopes:Object.keys(selection),selection})}));
async function create(scope:string,ids=[scope],fields:readonly string[]=[]){const response=await write({[scope]:{ids,fields}});expect(response.status).toBe(200);return (await response.json() as {key:string}).key;}
const read=(scope:string,key?:string,query='',method='GET')=>serveApi(fixture.db,new Request(`https://fixture/api/v1/${scope}${query}`,{method,headers:key?{authorization:`Bearer ${key}`}:{}}),scope as ApiResource);
beforeEach(()=>{fixture=sharingDatabase();state.db=fixture.db;state.user={userId:'fixture-owner',email:'owner@fixture.invalid',displayName:'Owner',fullName:null};for(const scope of resources){fixture.add(scope,kinds[scope],rows[scope]);fixture.add(`${scope}-foreign`,kinds[scope],rows[scope],'fixture-partner');fixture.add(`${scope}-deleted`,kinds[scope],rows[scope],'fixture-owner',1);}fixture.add('legacy-dive','dive',{site:'Legacy site'});});
afterEach(()=>fixture.sqlite.close());
describe('explicit owner-selected planning API extension',()=>{
  it('adds three scopes without changing existing field consent',()=>{expect(API_RESOURCES).toEqual(['dives','awards','equipment','equipment-usage','gas-plans','dive-plans','trips']);expect(API_FIELDS.dives).toEqual(['date','site','depth','duration','mode']);});
  it.each(resources)('%s lists only exact owner records and excludes deleted/foreign choices',async scope=>{const before=fixture.records();const response=await choices(new Request(`https://fixture/api/integration-keys/records?resource=${scope}`));expect(response.status).toBe(200);const body=await response.json() as {items:Array<{id:string;label:string}>};expect(body.items).toEqual([{id:scope,label:rows[scope].name}]);expect(fixture.records()).toEqual(before);});
  it.each(resources)('%s projects only selected saved values and opaque identity',async scope=>{const before=fixture.records();const key=await create(scope,[scope],API_FIELDS[scope as ApiResource]);const response=await read(scope,key);expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toContain('no-store');expect(response.headers.get('access-control-allow-origin')).toBeNull();const body=await response.json() as {units:Record<string,string>;items:Array<Record<string,unknown>>};expect(body.items).toHaveLength(1);expect(body.items[0]!.id).toMatch(/^[a-f0-9-]{36}$/);expect(body.items[0]!.name).toBe(rows[scope].name);if(scope==='gas-plans'){expect(body.items[0]).toMatchObject({depthM:24,durationMin:35,rmvLitresMin:16,supplies:[{role:'primary',gas:'nitrox',oxygenFraction:0.32,startPressureBar:210,reservePressureBar:60,volumeLitres:12}]});expect(body.units).toEqual({depth:'metres',duration:'minutes',rmv:'litres/minute',pressure:'bar',volume:'litres'});}if(scope==='dive-plans')expect(body.items[0]).toMatchObject({status:'cancelled',start:'2026-10',end:'2026-10',site:'Chosen site',depthM:22,durationMin:40});if(scope==='trips')expect(body.items[0]).toMatchObject({start:'2026-11',end:'2026-12',destination:'Chosen destination',itinerary:[{kind:'dive',title:'Chosen dive',start:'2026-11-02T10:00',end:'2026-11-02T11:00',location:'Chosen location'}],omittedItineraryCount:0});expect(JSON.stringify(body)).not.toMatch(/PRIVATE|fixture-owner|serialNumber|medical|bookingRef|organiser|gasPlanId|cylinderEquipmentId|recGasPlan101/);expect(fixture.records()).toEqual(before);});
  it.each(resources)('%s rejects private fields, cross-owner, deleted and wrong-kind selections',async scope=>{for(const ids of [[`${scope}-foreign`],[`${scope}-deleted`],['legacy-dive'],['missing']])expect((await write({[scope]:{ids,fields:['name']}})).status).toBe(400);for(const fields of [['notes'],['team'],['serialNumber'],['attachments'],['medicalNotes']])expect((await write({[scope]:{ids:[scope],fields}})).status).toBe(400);});
  it.each(resources)('%s requires independent consent, remains read-only and rechecks object ownership',async scope=>{const legacy=await create('dives',['legacy-dive'],['site']);expect((await read(scope,legacy)).status).toBe(403);expect((await read(scope)).status).toBe(401);const key=await create(scope);expect(await (await read(scope,key,'','HEAD')).text()).toBe('');expect((await read(scope,key,'','POST')).status).toBe(405);let body=await (await read(scope,key)).json() as {items:object[]};expect(Object.keys(body.items[0]!)).toEqual(['id']);fixture.sqlite.prepare("UPDATE dive_records SET user_id='fixture-partner' WHERE id=?").run(scope);body=await (await read(scope,key)).json() as {items:object[]};expect(body.items).toEqual([]);});
  it('bounds itinerary projection and explicitly reports omitted entries without leaking nested fields',async()=>{const itinerary=Array.from({length:103},(_,i)=>({id:`PRIVATE-${i}`,title:`Chosen ${i}`,notes:'PRIVATE NOTES'}));fixture.sqlite.prepare('UPDATE dive_records SET data_json=? WHERE id=?').run(JSON.stringify({...rows.trips,itinerary}),'trips');const key=await create('trips',['trips'],['itinerary']);const body=await (await read('trips',key)).json() as {items:Array<{itinerary:object[];omittedItineraryCount:number}>};expect(body.items[0]!.itinerary).toHaveLength(100);expect(body.items[0]!.omittedItineraryCount).toBe(3);expect(JSON.stringify(body)).not.toMatch(/PRIVATE|notes/);});
  it('binds new-resource pagination to its scope and fails safely on unreadable canonical records',async()=>{fixture.add('gas-plans-2','gas-plan',{name:'Second plan'});const key=await create('gas-plans',['gas-plans','gas-plans-2'],['name']);const first=await (await read('gas-plans',key,'?limit=1')).json() as {nextCursor:string;items:object[]};expect(first.items).toHaveLength(1);const second=await (await read('gas-plans',key,`?limit=1&cursor=${encodeURIComponent(first.nextCursor)}`)).json() as {items:object[]};expect(second.items).toHaveLength(1);fixture.sqlite.prepare('UPDATE dive_records SET data_json=? WHERE id=?').run(JSON.stringify({encryptedPayload:'PRIVATE CIPHER'}),'gas-plans');expect((await read('gas-plans',key)).status).toBe(503);});
  it('serves readable browser documentation while preserving machine JSON and safe errors',async()=>{const html=await contract(new Request('https://fixture/api/v1/openapi',{headers:{accept:'text/html,application/xhtml+xml'}}));expect(html.headers.get('content-type')).toContain('text/html');expect(html.headers.get('cache-control')).toContain('no-store');const page=await html.text();for(const phrase of ['API usage guide','/api/v1/gas-plans','/api/v1/dive-plans','/api/v1/trips','Select all matching','/public-profile','Authorization: Bearer'])expect(page).toContain(phrase);expect(page).not.toContain('<script');const json=await contract(new Request('https://fixture/api/v1/openapi?format=json',{headers:{accept:'text/html'}}));expect(json.headers.get('content-type')).toContain('application/json');const body=await json.json() as {paths:Record<string,unknown>};for(const scope of resources)expect(body.paths).toHaveProperty(`/api/v1/${scope}`);expect((await contract(new Request('https://fixture/api/v1/openapi?format=unsafe'))).status).toBe(400);});
});
