import {describe,expect,it} from 'vitest';
import {cylinderNumberIssues,reviewCylinderNumberChange,type CylinderNumberIdentity} from '../lib/cylinders/cylinder-number-review';
const cylinder=(entityId:string,cylinderNumber:string|null,recordStorageKind:'cylinder'|'equipment'='cylinder'):CylinderNumberIdentity=>({entityId,cylinderNumber,recordStorageKind,modifiedAt:'2026-10-02T06:00:00.000Z'});
const review={entityId:'tank-a',recordStorageKind:'cylinder' as const,expectedNumber:'03',expectedModifiedAt:'2026-10-02T06:00:00.000Z',requestedNumber:'02'};
describe('read-only cylinder number diagnostics and explicit review',()=>{
 it('reports both duplicate identities without choosing which tank should change',()=>{expect(cylinderNumberIssues([cylinder('tank-a','03'),cylinder('tank-b','3','equipment')])).toEqual([{kind:'duplicate',number:'03',records:[{entityId:'tank-a',recordStorageKind:'cylinder'},{entityId:'tank-b',recordStorageKind:'equipment'}]}]);});
 it('distinguishes missing and invalid values without inventing an assignment',()=>{const issues=cylinderNumberIssues([cylinder('missing',null),cylinder('invalid','100'),cylinder('invalid-zero','00')]);expect(issues.map(item=>item.kind)).toEqual(['missing','invalid','invalid']);expect(issues.every(item=>item.number===null)).toBe(true);});
 it('keeps malformed historical number values readable without echoing or repairing them',()=>{const row={...cylinder('malformed','03'),cylinderNumber:{private:'DO_NOT_DISPLAY'}} as unknown as CylinderNumberIdentity;const issues=cylinderNumberIssues([row]);expect(issues).toMatchObject([{kind:'invalid',number:null,records:[{entityId:'malformed'}]}]);expect(JSON.stringify(issues)).not.toContain('DO_NOT_DISPLAY');expect(row.cylinderNumber).toEqual({private:'DO_NOT_DISPLAY'});});
 it('does not rewrite historical formatting, IDs, values or ordering',()=>{const rows=[cylinder('later','03'),cylinder('earlier','03'),cylinder('legacy','1')];const before=JSON.stringify(rows);cylinderNumberIssues(rows);expect(JSON.stringify(rows)).toBe(before);});
 it('prepares only the explicitly selected tank and number with a current revision',()=>{const rows=[cylinder('tank-a','03'),cylinder('tank-b','03')];expect(reviewCylinderNumberChange(rows,review)).toEqual({entityId:'tank-a',recordStorageKind:'cylinder',cylinderNumber:'02',expectedNumber:'03',expectedModifiedAt:review.expectedModifiedAt});expect(rows.map(row=>row.cylinderNumber)).toEqual(['03','03']);});
 it('rejects another tank already holding the requested number, including legacy equipment',()=>{expect(()=>reviewCylinderNumberChange([cylinder('tank-a','03'),cylinder('other','2','equipment')],review)).toThrow('already assigned');});
 it('rejects missing or type-mismatched identity and stale reviews',()=>{expect(()=>reviewCylinderNumberChange([],review)).toThrow('no longer available');expect(()=>reviewCylinderNumberChange([cylinder('tank-a','03','equipment')],review)).toThrow('no longer available');expect(()=>reviewCylinderNumberChange([cylinder('tank-a','04')],review)).toThrow('changed');expect(()=>reviewCylinderNumberChange([{...cylinder('tank-a','03'),modifiedAt:'2026-10-02T07:00:00.000Z'}],review)).toThrow('changed');});
 it('retains the established 01–99 range and rejects destructive bulk/ambiguous requests',()=>{for(const requestedNumber of ['00','100','-1','1.5','02,03',''])expect(()=>reviewCylinderNumberChange([cylinder('tank-a','03')],{...review,requestedNumber})).toThrow('01–99');expect(reviewCylinderNumberChange([cylinder('tank-a','03')],{...review,requestedNumber:' 2 '}).cylinderNumber).toBe('02');});
 it('supports correcting a missing label only after explicit identity and revision review',()=>{expect(reviewCylinderNumberChange([cylinder('tank-a',null)],{...review,expectedNumber:null,requestedNumber:'01'}).cylinderNumber).toBe('01');});
 it('does not offer an automatic reverse of an already accepted 03-to-02 change',()=>{expect(cylinderNumberIssues([cylinder('tank-a','02'),cylinder('tank-b','03')])).toEqual([]);});
});
