import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {renderToStaticMarkup} from 'react-dom/server';
import {createElement} from 'react';
import {strToU8,zlibSync} from 'fflate';
import {sharingBucket,sharingDatabase} from './selected-sharing-fixture';
const state=vi.hoisted(()=>({db:null as unknown as D1Database,files:null as unknown as R2Bucket,user:{userId:'fixture-owner',email:'owner@fixture.invalid',displayName:'Owner',fullName:null} as {userId:string;email:string;displayName:string;fullName:null}|null}));
vi.mock('cloudflare:workers',()=>({env:{get DB(){return state.db;},get FILES(){return state.files;}}}));
vi.mock('../app/chatgpt-auth',()=>({getChatGPTUser:async()=>state.user}));
vi.mock('../lib/server/household',()=>({OWNER_EMAIL:'owner@fixture.invalid',isLocalPreviewUser:()=>false}));
import {GET as visitor} from '../app/api/public-profile/route';
import {GET as status,POST as manage} from '../app/api/public-profile/manage/route';
import {POST as upload,GET as photo} from '../app/api/public-profile/photo/route';
import {PublicProfileView} from '../components/sharing/public-profile-view';
import type {PublicationSnapshot} from '../lib/sharing/public-profile';
type Preview={snapshot:PublicationSnapshot;previewHash:string};
import {sanitizePublicationRaster} from '../lib/sharing/public-photo';
let fixture:ReturnType<typeof sharingDatabase>,bucket:ReturnType<typeof sharingBucket>;
const request=(value:object,origin='https://fixture')=>new Request('https://fixture/api/public-profile/manage',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify(value)});
function crc(bytes:Uint8Array){let value=0xffffffff;for(const byte of bytes){value^=byte;for(let bit=0;bit<8;bit++)value=(value>>>1)^((value&1)?0xedb88320:0);}return (value^0xffffffff)>>>0;}
function chunk(name:string,data:Uint8Array){const output=new Uint8Array(data.length+12),view=new DataView(output.buffer);view.setUint32(0,data.length);output.set(strToU8(name),4);output.set(data,8);view.setUint32(data.length+8,crc(output.subarray(4,data.length+8)));return output;}
function png(width=2,height=2,metadata=true){const header=new Uint8Array(13),view=new DataView(header.buffer);view.setUint32(0,width);view.setUint32(4,height);header[8]=8;header[9]=6;const parts=[new Uint8Array([137,80,78,71,13,10,26,10]),chunk('IHDR',header),...(metadata?[chunk('tEXt',strToU8('GPS\0PRIVATE LOCATION'))]:[]),chunk('IDAT',zlibSync(new Uint8Array(height*(width*4+1)))),chunk('IEND',new Uint8Array())];const result=new Uint8Array(parts.reduce((n,part)=>n+part.length,0));let cursor=0;for(const part of parts){result.set(part,cursor);cursor+=part.length;}return result;}
beforeEach(()=>{fixture=sharingDatabase();bucket=sharingBucket();state.db=fixture.db;state.files=bucket.bucket;state.user={userId:'fixture-owner',email:'owner@fixture.invalid',displayName:'Owner',fullName:null};fixture.add('owner-person','person',{name:'Private owner',roles:{ownerProfile:true},email:'private@example.invalid',highestRecreationalCertification:'Rescue Diver'});fixture.add('dive','dive',{site:'Private site',date:'2026-10-01',maxDepthM:22,bottomTimeMin:40,notes:'SECRET NOTE',buddyIds:['private-buddy']});fixture.add('partner-dive','dive',{site:'Partner site',maxDepthM:99,bottomTimeMin:100},'fixture-partner');fixture.add('award','certification',{certification:'Master Scuba Diver',courseType:'experience',personId:'owner-person',certificationNumber:'SECRET NUMBER'});});
afterEach(()=>fixture.sqlite.close());
describe('public profile: actual owner/visitor handlers',()=>{
 it('matches canonical elapsed-runtime Insights and presents absent depth/time evidence as not recorded',async()=>{fixture.sqlite.prepare("UPDATE dive_records SET data_json=json_set(data_json,'$.totalElapsedMin',57) WHERE id='dive'").run();let preview=await (await manage(request({action:'preview',input:{insights:['totalMinutes']}}))).json() as Preview;expect(preview.snapshot.insights[0]?.value).toBe(57);fixture.sqlite.prepare("UPDATE dive_records SET data_json=json_set(data_json,'$.totalElapsedMin',NULL,'$.bottomTimeMin',NULL,'$.maxDepthM',NULL) WHERE id='dive'").run();const before=fixture.records();preview=await (await manage(request({action:'preview',input:{insights:['totalMinutes','maxDepth']}}))).json() as Preview;expect(preview.snapshot.insights.map(item=>item.value)).toEqual(['Not recorded','Not recorded']);expect(fixture.records()).toEqual(before);});
 it('uses the same active canonical evidence as the private summaries, without counting suppressed duplicates or awards',async()=>{fixture.add('suppressed-dive','dive',{site:'Duplicate fixture',maxDepthM:99,bottomTimeMin:900,suppressedFromUse:true});fixture.add('suppressed-award','certification',{certification:'Fixture award',courseType:'recreational',awardPriority:999,personId:'owner-person',suppressedFromUse:true});const before=fixture.records();const preview=await (await manage(request({action:'preview',input:{insights:['totalDives','totalMinutes','maxDepth','highestRecreationalAward']}}))).json() as Preview;expect(preview.snapshot.insights.map(item=>item.value)).toEqual([1,40,22,'Master Scuba Diver']);expect(fixture.records()).toEqual(before);});
 it('defaults disabled without writing tables or records on reads',async()=>{const before=fixture.records();expect((await visitor()).status).toBe(404);expect(await (await status()).json()).toMatchObject({enabled:false});expect(fixture.records()).toEqual(before);expect(fixture.sqlite.prepare("SELECT name FROM sqlite_master WHERE name='dive_publications'").get()).toBeUndefined();});
 it('builds an exact canonical redacted preview, requires its hash, publishes explicitly and revokes immediately',async()=>{const before=fixture.records();const input={displayName:'Diver',biography:'<script>alert(1)</script>',insights:['totalDives','totalMinutes','maxDepth','highestRecreationalAward']};const preview=await (await manage(request({action:'preview',input}))).json() as Preview;expect(preview.snapshot).toMatchObject({version:1,displayName:'Diver',biography:input.biography});expect(preview.snapshot.insights.map((item:{value:unknown})=>item.value)).toEqual([1,40,22,'Master Scuba Diver']);expect(JSON.stringify(preview)).not.toMatch(/SECRET|private@example|Private site|owner-person|partner-dive/);expect((await visitor()).status).toBe(404);expect((await manage(request({action:'publish',input,asOf:preview.snapshot.asOf,previewHash:'wrong'}))).status).toBe(409);expect((await manage(request({action:'publish',input,asOf:preview.snapshot.asOf,previewHash:preview.previewHash}))).status).toBe(200);const live=await visitor();expect(live.headers.get('cache-control')).toContain('no-store');expect(await live.json()).toEqual(preview.snapshot);const html=renderToStaticMarkup(createElement(PublicProfileView,{snapshot:preview.snapshot}));expect(html).toContain('&lt;script&gt;');expect(html).not.toContain('<script>alert');expect((await manage(request({action:'revoke'}))).status).toBe(200);expect((await visitor()).status).toBe(404);expect(fixture.records()).toEqual(before);});
 it('rejects nested/unknown fields and private photo keys and never serialises private records',async()=>{for(const input of [{displayName:'Diver',insights:[],email:'leak'},{displayName:'Diver',insights:[],biography:{notes:'leak'}},{displayName:'Diver',insights:['serialNumbers']},{displayName:'Diver',insights:[],photoId:'certificates/owner/private'}])expect((await manage(request({action:'preview',input}))).status).toBe(400);});
 it('requires owner identity and exact same-origin writes including preview/upload',async()=>{expect((await manage(request({action:'revoke'},'https://evil.invalid'))).status).toBe(403);state.user={userId:'member',email:'member@fixture.invalid',displayName:'Member',fullName:null};expect((await status()).status).toBe(403);expect((await manage(request({action:'revoke'}))).status).toBe(403);state.user=null;expect((await manage(request({action:'revoke'}))).status).toBe(401);});
 it('rejects a stale preview when canonical evidence changed',async()=>{const input={displayName:'Diver',insights:['totalDives']};const preview=await (await manage(request({action:'preview',input}))).json() as Preview;fixture.add('later','dive',{site:'Later',date:'2026-10-02'});expect((await manage(request({action:'publish',input,asOf:preview.snapshot.asOf,previewHash:preview.previewHash}))).status).toBe(409);expect((await visitor()).status).toBe(404);});
 it('stores only a sanitised public photo derivative, gates draft ownership and makes replaced/revoked images unavailable',async()=>{const before=fixture.records();const bytes=png();const result=await upload(new Request('https://fixture/api/public-profile/photo',{method:'POST',headers:{origin:'https://fixture','content-type':'image/png'},body:bytes}));expect(result.status).toBe(200);const uploaded=await result.json() as {photoId:string};expect(uploaded.photoId).toMatch(/^[a-f0-9-]{36}$/);const object=[...bucket.objects.values()][0]!;expect(new TextDecoder().decode(object.bytes)).not.toContain('PRIVATE LOCATION');expect((await photo(new Request(`https://fixture/api/public-profile/photo?id=${uploaded.photoId}`))).status).toBe(404);expect((await photo(new Request(`https://fixture/api/public-profile/photo?id=${uploaded.photoId}&preview=1`))).status).toBe(200);state.user={userId:'member',email:'member@fixture.invalid',displayName:'Member',fullName:null};expect((await photo(new Request(`https://fixture/api/public-profile/photo?id=${uploaded.photoId}&preview=1`))).status).toBe(404);state.user={userId:'fixture-owner',email:'owner@fixture.invalid',displayName:'Owner',fullName:null};const input={displayName:'Diver',insights:[],photoId:uploaded.photoId};const preview=await (await manage(request({action:'preview',input}))).json() as Preview;await manage(request({action:'publish',input,asOf:preview.snapshot.asOf,previewHash:preview.previewHash}));expect((await photo(new Request(`https://fixture/api/public-profile/photo?id=${uploaded.photoId}`))).status).toBe(200);const noPhoto={displayName:'Diver',insights:[]};const updated=await (await manage(request({action:'preview',input:noPhoto}))).json() as Preview;await manage(request({action:'publish',input:noPhoto,asOf:updated.snapshot.asOf,previewHash:updated.previewHash}));expect((await photo(new Request(`https://fixture/api/public-profile/photo?id=${uploaded.photoId}`))).status).toBe(404);expect(fixture.records()).toEqual(before);});
});
describe('independent raster and public bundle boundaries',()=>{
 it('strips JPEG EXIF/comments, retains a real raster and rejects malformed frame/scan lengths or truncation',()=>{const original=new Uint8Array(Buffer.from('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAADAAIDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDwqiiiv6DP58P/2Q==','base64'));const payload=strToU8('Exif\0PRIVATE GPS / CONTACT');const segment=(marker:number)=>new Uint8Array([255,marker,0,payload.length+2,...payload]);const privateJpeg=new Uint8Array([...original.slice(0,2),...segment(225),...segment(254),...original.slice(2)]);const clean=sanitizePublicationRaster(privateJpeg,'image/jpeg');expect(clean).toMatchObject({contentType:'image/jpeg',width:2,height:3});expect(clean.bytes).toEqual(sanitizePublicationRaster(original,'image/jpeg').bytes);expect(new TextDecoder().decode(clean.bytes)).not.toMatch(/PRIVATE|CONTACT|Exif/);expect(()=>sanitizePublicationRaster(original.slice(0,-2),'image/jpeg')).toThrow();const bad=original.slice();const scan=bad.findIndex((value,index)=>value===255&&bad[index+1]===218);expect(scan).toBeGreaterThan(0);bad[scan+4]=0;expect(()=>sanitizePublicationRaster(bad,'image/jpeg')).toThrow();});
 it('rejects compressed data that exceeds its claimed PNG dimensions',()=>{const valid=png(2,2,false),header=valid.slice(8,33);const parts=[valid.slice(0,8),header,chunk('IDAT',zlibSync(new Uint8Array(100000))),chunk('IEND',new Uint8Array())];expect(()=>sanitizePublicationRaster(new Uint8Array(parts.flatMap(part=>[...part])),'image/png')).toThrow();});
 it('strips metadata, preserves PNG alpha pixels and rejects malformed/huge/forged rasters',()=>{const clean=sanitizePublicationRaster(png(),'image/png');expect(clean.contentType).toBe('image/png');expect(clean.width).toBe(2);expect(clean.bytes).toEqual(png(2,2,false));expect(()=>sanitizePublicationRaster(png(3000,1),'image/png')).toThrow();expect(()=>sanitizePublicationRaster(strToU8('<svg/>'),'image/png')).toThrow();const bad=png();bad[30]=bad[30]!^1;expect(()=>sanitizePublicationRaster(bad,'image/png')).toThrow();expect(()=>sanitizePublicationRaster(png(),'image/jpeg')).toThrow();});
 it('keeps public presentation independent of private dashboard/stores and identity navigation uncached',()=>{const view=readFileSync(new URL('../components/sharing/public-profile-view.tsx',import.meta.url),'utf8');expect(view).not.toMatch(/dashboard-client|offline\/|household|gmail/);const page=readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8');expect(page).toContain("await import('./dashboard-client')");expect(page).toContain('chatGPTSignInPath');const worker=readFileSync(new URL('../app/service-worker.ts',import.meta.url),'utf8');expect(worker).not.toContain('new NetworkFirst');expect(worker).toContain("self.addEventListener('activate'");expect(worker).toContain('zeustek-navigation-');});
});
