import {describe,expect,it} from 'vitest';
import {tripDirectionsUrl,siteRoadArrival,ownerHomeAddress} from '../lib/planning/trip-directions';
import type {PersonRecord,DiveSiteRecord} from '../lib/offline/dive-planning';
const owner={name:'Dummy owner',roles:{ownerProfile:true},address:'1 Dummy Road',postcode:'AA1 1AA',location:'London'} as PersonRecord;
describe('Reviewed Trip driving directions',()=>{
 it('omits origin for current location and fixes the public Google host/mode',()=>{const url=new URL(tripDirectionsUrl('Dummy harbour',{kind:'current'})!);expect(url.origin+url.pathname).toBe('https://www.google.com/maps/dir/');expect(url.searchParams.get('api')).toBe('1');expect(url.searchParams.get('travelmode')).toBe('driving');expect(url.searchParams.has('origin')).toBe(false);});
 it('encodes Unicode and query-like text as locations, never executable URL parameters',()=>{const destination='Port São João & mode=walking';const url=new URL(tripDirectionsUrl(destination,{kind:'address',address:'AB1 2CD & x=1'})!);expect(url.searchParams.get('destination')).toBe(destination);expect(url.searchParams.get('origin')).toBe('AB1 2CD & x=1');expect(url.searchParams.get('travelmode')).toBe('driving');expect(url.searchParams.has('x')).toBe(false);});
 it('rejects blank destination, unavailable Home, blank manual origin and oversized URLs',()=>{expect(tripDirectionsUrl(' ',{kind:'current'})).toBeNull();expect(tripDirectionsUrl('Port',{kind:'home',address:''})).toBeNull();expect(tripDirectionsUrl('Port',{kind:'address',address:' '})).toBeNull();expect(tripDirectionsUrl('a'.repeat(2200),{kind:'current'})).toBeNull();});
 it('uses only the uniquely identified owner and leaves all source records unchanged',()=>{const rows=[{...owner,roles:{buddy:true},address:'Other private address'},owner];const before=JSON.stringify(rows);expect(ownerHomeAddress(rows)).toBe('1 Dummy Road, AA1 1AA, London');expect(JSON.stringify(rows)).toBe(before);expect(ownerHomeAddress([])).toBeNull();expect(ownerHomeAddress([owner,{...owner,name:'Second owner'}])).toBeNull();expect(ownerHomeAddress([{...owner,address:'',postcode:''}])).toBeNull();});
 it('uses Home in the URL only when explicitly selected',()=>{const address=ownerHomeAddress([owner])!;expect(new URL(tripDirectionsUrl('Port',{kind:'home',address})!).searchParams.get('origin')).toBe(address);expect(new URL(tripDirectionsUrl('Port',{kind:'current'})!).searchParams.has('origin')).toBe(false);});
 it('prefers recorded road address and rejects underwater-coordinate/name-only fallbacks',()=>{expect(siteRoadArrival({name:'Underwater wreck',address:'Pier Road',postcode:'BB2 2BB',location:'Town',country:'UK',latitude:55,longitude:-1} as DiveSiteRecord)).toBe('Pier Road, BB2 2BB, Town, UK');expect(siteRoadArrival({name:'Offshore wreck',location:'North Sea',latitude:55,longitude:-1} as DiveSiteRecord)).toBeNull();expect(siteRoadArrival(null)).toBeNull();});
});
