import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {describe,expect,it} from 'vitest';
import {TripEditor} from '../components/trips-expeditions';
import type {PersonRecord,Stored} from '../lib/offline/dive-planning';
import type {DiveExpeditionTripRecord} from '../lib/offline/trips-expeditions';
const people=[{entityId:'owner-person',name:'Zeus',role:'buddy',roles:{ownerProfile:true}},{entityId:'other-zeus',name:'Zeus',role:'buddy'}] as Array<Stored<PersonRecord>>;
describe('Trip destination and canonical owner presentation',()=>{
 it('existing itinerary items have individual closed summaries with their type, title and start date',()=>{const item={entityId:'dummy-trip',name:'Three-week trip',teamPersonIds:[],siteIds:[],planIds:[],guestParticipants:[],bookings:[],packingItems:[],packingEquipmentSetIds:[],gasLogistics:[],documentAttachmentIds:[],itinerary:[{id:'flight',kind:'travel',title:'Outbound flight',startsAt:'2026-10-10T09:00'},{id:'dive',kind:'dive',title:'Day 20 dive',startsAt:'2026-10-30T08:00'}]} as unknown as Stored<DiveExpeditionTripRecord>;const html=renderToStaticMarkup(createElement(TripEditor,{item,items:[item],plans:[],sites:[],people:[],equipment:[],equipmentSets:[],currentUserId:'dummy-account',sourceBooking:null,close:()=>{},saved:()=>{}}));expect(html).toMatch(/<details[^>]*><summary><span>Travel · Outbound flight<\/span><small>2026-10-10 · 09:00/);expect(html).toMatch(/<details[^>]*><summary><span>Dive · Day 20 dive<\/span><small>2026-10-30 · 08:00/);expect(html).toContain('Link URL');expect(html).toContain('Notes');});
 it('offers a labelled searchable destination with exact saved Site choices',()=>{const html=renderToStaticMarkup(createElement(TripEditor,{item:null,items:[],plans:[],sites:[],people,equipment:[],equipmentSets:[],currentUserId:'dummy-account',sourceBooking:null,close:()=>{},saved:()=>{}}));expect(html).toMatch(/<input[^>]*list=/);expect(html).toContain('Type a Site name');});
 it('shows only the canonical owner as Me / Self while leaving the source Person roles untouched',()=>{const before=JSON.stringify(people);const html=renderToStaticMarkup(createElement(TripEditor,{item:null,items:[],plans:[],sites:[],people,equipment:[],equipmentSets:[],currentUserId:'dummy-account',sourceBooking:null,close:()=>{},saved:()=>{}}));expect(html).toContain('<b>Me</b><small>Self');expect(html).toContain('<b>Zeus</b><small>buddy');expect(JSON.stringify(people)).toBe(before);});
});
