import {API_FIELDS,API_LABELS,API_RESOURCES} from './readonly-api';
const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
/** Static, script-free reference. No credential input or owner data is embedded. */
export function apiUsageGuide(){
  const rows=API_RESOURCES.map(resource=>`<tr><th scope="row">${escape(API_LABELS[resource])}</th><td><code>/api/v1/${resource}</code></td><td>${escape(API_FIELDS[resource].join(', ')||'Saved usage evidence only')}</td></tr>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>API usage guide · ZeusTek Diving</title><style>body{margin:0;background:#080808;color:#e8eef0;font:16px/1.65 Arial,sans-serif}main{max-width:1000px;margin:auto;padding:24px}h1,h2{color:#ff8800;line-height:1.3}a{color:#00cfff;display:inline-block;min-height:44px;overflow-wrap:anywhere}a:focus-visible{outline:3px solid #00cfff;outline-offset:4px}section{border:1px solid #33545d;border-radius:16px;padding:20px;margin:20px 0}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{padding:12px 8px;border-bottom:1px solid #33545d;text-align:left;vertical-align:top;overflow-wrap:anywhere}code,pre{font-family:monospace;overflow-wrap:anywhere;white-space:pre-wrap;word-break:break-word}pre{padding:16px;background:#121b1f;border-radius:10px}li{margin:8px 0}p{overflow-wrap:anywhere}@media(max-width:600px){main{padding:16px}section{padding:14px}table,tbody,tr,th,td{display:block;width:auto}tr{padding:10px 0}th,td{padding:5px 0;border:0}tr{border-bottom:1px solid #33545d}}</style></head><body><main><a href="/">ZeusTek Diving</a><h1>API usage guide</h1><p>Version1 · Read selected saved data from a client server. This guide contains no private records or real API keys.</p><nav aria-label="API guide sections"><a href="#setup">Set up access</a> · <a href="#resources">Records and fields</a> · <a href="#requests">Make a request</a> · <a href="#limits">Errors and limits</a> · <a href="#profile">Public profile</a></nav>
<section id="setup"><h2>1. Choose exactly what a client may read</h2><ol><li>Sign in as owner. Open <a href="/?section=Settings">Site Configuration</a> → Read-only API integrations.</li><li>Choose AMZeus or ZeusTek and an expiry within one year. Keep a separate key for each client.</li><li>Enable a resource, select its fields and saved records. <strong>Select all matching</strong> adds existing matching records only, up to1000; it never automatically includes future records. Minimise each section after reviewing it.</li><li>Review Selected access, confirm the exact selection and create the approved key. Store the once-only key in the client's server secret manager.</li></ol><p>Existing keys never gain new scopes automatically. Rotate/revoke in Settings. Do not place a key in public JavaScript, a URL, screenshots, logs or downloads.</p></section>
<section id="resources"><h2>2. Available records and fields</h2><table><thead><tr><th>Resource</th><th>GET endpoint / scope</th><th>Optional selected fields</th></tr></thead><tbody>${rows}</tbody></table><p>Every object uses a key-scoped opaque ID. Unselected fields and missing saved values are omitted. Depth is metres; duration is minutes; RMV is litres/minute; supply pressures are bar and volume is litres. Dates keep their saved precision.</p><p>Gas/Dive Plans expose saved planning inputs, not a new calculation or a readiness claim. Gas supplies contain only selected saved role/mix/volume/start/reserve inputs; inventory-only details are absent. Trips expose selected dates/destination and at most100 redacted itinerary entries, with an omitted-entry count. Teams, guests, booking references/payments, attachments, medical/emergency details, private notes, contacts, serial/certificate numbers and internal record IDs are excluded.</p><p>Equipment usage follows saved direct equipment IDs or a saved loadout snapshot. Today's loadout never establishes historical use. Equipment and its Dive must be separately selected to return their joined opaque references.</p></section>
<section id="requests"><h2>3. Make a server-side request</h2><pre>GET /api/v1/dives?limit=25 HTTP/1.1
Host: dive.amzeus.co.uk
Authorization: Bearer YOUR_CLIENT_KEY
Accept: application/json</pre><p>The placeholder is not a credential. HTTPS is required. GET/HEAD only; no record writes, Gmail sync or public-profile publication. Browser cookies do not authorise API access. There is no permissive browser CORS.</p><p>Follow the opaque <code>nextCursor</code> until it is null. Request <code>?limit=100</code> for up to100 objects per page. Only limit and cursor are accepted; escape plain text when presenting it.</p><a href="/api/v1/openapi?format=json">Download / view machine-readable OpenAPI JSON</a><p>Machine clients also receive JSON when they request application/json from this same endpoint.</p></section>
<section id="limits"><h2>4. Errors, privacy and revocation</h2><ul><li>400: invalid query/cursor or non-HTTPS request.</li><li>401: invalid, expired or revoked key.</li><li>403: resource outside the key's explicit scope.</li><li>405: unsupported write method.</li><li>429:60 requests per key per minute; respect Retry-After.</li><li>503: selected saved evidence temporarily unavailable.</li></ul><p>Responses are private/no-store. Never use public/CDN/PWA caches. Revocation stops future reads but cannot erase data a client already copied. Backups/support exports exclude connection and integration credentials.</p></section>
<section id="profile"><h2>Where is the public profile?</h2><p>The visitor page is <a href="/public-profile">/public-profile</a>. Anonymous visitors also see the approved landing snapshot at the site root. When publication is off, both show the generic welcome. Sign-in and approved users' private deep links remain intact.</p><p>Open Site Configuration → Public profile to select content, preview the exact visitor page and explicitly publish/update/revoke. No profile is published by reading this guide or creating an API key.</p></section></main></body></html>`;
}
