import {API_RESOURCES,type ApiResource} from './readonly-api';
const id={type:'string',format:'uuid',description:'Opaque consent-scoped object identifier. Never a canonical/account/import ID.'};
const text=(maxLength=512)=>({type:'string',maxLength,description:'Saved plain text; consumers must escape it when rendering.'});
const metric=(unit:string)=>({type:'number',minimum:0,description:unit});
const schemas={
  Dive:{type:'object',additionalProperties:false,required:['id'],properties:{id,date:{...text(64),description:'Original saved resolution, including month-only dates.'},site:text(),depthM:metric('metres'),durationMin:metric('Saved elapsed runtime in minutes; bottom time only when elapsed runtime is absent'),mode:text(120)}},
  Award:{type:'object',additionalProperties:false,required:['id'],properties:{id,title:text(180),agency:text(180),date:text(64),track:{enum:['recreational-display','technical-display','professional-display','unclassified'],description:'Display classification only; no depth, permission or physiological capability inference.'}}},
  Equipment:{type:'object',additionalProperties:false,required:['id'],properties:{id,name:text(),category:text(180),maker:text(180),model:text()}},
  EquipmentUsage:{type:'object',additionalProperties:false,required:['id','status','provenance','equipment','withheldEvidenceCount'],properties:{id,diveId:{...id,description:'Exact Dive object under this same key; omitted unless that Dive is separately consented and still owner-accessible.'},status:{enum:['confirmed','hire','unknown']},provenance:{enum:['saved-equipment-ids','saved-loadout-snapshot','no-saved-evidence']},equipment:{type:'array',maxItems:1000,items:{type:'object',additionalProperties:false,required:['id','provenance'],properties:{id,provenance:{enum:['saved-equipment-ids','saved-loadout-snapshot']}}}},withheldEvidenceCount:{type:'integer',minimum:0,description:'Saved references unavailable under this key’s explicit equipment consent; no identity or details disclosed.'}}},
  Error:{type:'object',additionalProperties:false,required:['error'],properties:{error:text()}},
};
const itemNames:Record<ApiResource,string>={dives:'Dive',awards:'Award',equipment:'Equipment','equipment-usage':'EquipmentUsage'};
function responses(resource:ApiResource){return {
  '200':{description:'Selected owner data; Cache-Control private/no-store. Fields absent from consent are omitted.',content:{'application/json':{schema:{type:'object',additionalProperties:false,required:['version','resource','units','provenance','items','nextCursor'],properties:{version:{const:'1'},resource:{const:resource},units:{type:'object',additionalProperties:{type:'string'},description:'Dive depth: metres; duration: saved elapsed-runtime minutes, with bottom-time fallback only when elapsed runtime is absent.'},provenance:text(),items:{type:'array',maxItems:100,items:{$ref:`#/components/schemas/${itemNames[resource]}`}},nextCursor:{type:['string','null'],maxLength:1000,description:'Signed key/owner/resource-bound cursor; opaque, do not alter.'}}}}}},
  ...Object.fromEntries([['400','Invalid query or cursor.'],['401','Invalid, expired or revoked key.'],['403','Resource outside selected scopes.'],['405','Read-only. GET/HEAD only.'],['429','60 requests per key per minute.'],['503','Selected evidence unavailable; no private details returned.']].map(([code,description])=>[code,{description,...(code==='429'?{headers:{'Retry-After':{schema:{type:'integer',minimum:1}}}}:{}),content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}}])),
};}
export const readonlyApiContract={
  openapi:'3.1.0',info:{title:'ZeusTek selected-data read-only API',version:'1.0.0',description:'Owner-issued per-client Bearer keys. Explicit scopes and record/field consent. Keys expire within one year; revocation is immediate and rotation invalidates the old key atomically. No query credentials, private contacts, notes, certificate/serial numbers, owner/account/import IDs or unrestricted backups. Dates retain saved resolution. Equipment usage uses saved direct IDs or loadout snapshots only; today’s loadout is never inferred. No permissive browser CORS.'},servers:[{url:'/'}],
  components:{securitySchemes:{integrationKey:{type:'http',scheme:'bearer',bearerFormat:'ZT1 opaque id and 256-bit secret'}},schemas},
  paths:Object.fromEntries(API_RESOURCES.map(resource=>[`/api/v1/${resource}`,{get:{summary:`Read selected ${resource}`,security:[{integrationKey:[]}],parameters:[{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:100,default:25}},{name:'cursor',in:'query',schema:{type:'string',maxLength:1000}}],responses:responses(resource)},head:{summary:'Same permissions and rate limits as GET, without a response body',security:[{integrationKey:[]}],responses:responses(resource)}}])),
};
