import {env} from 'cloudflare:workers';
import {publicationRow,publicationPreview,ensurePublicationSchema} from '@/lib/server/public-profile';
import {boundedJson,sharingOwner,sharingJson} from '@/lib/server/sharing-access';
import {strictObject,validatePublicationInput,validatePublicationSnapshot} from '@/lib/sharing/public-profile';
export async function GET(){const access=await sharingOwner();if(access.error)return access.error;try {const row=await publicationRow(env.DB,access.slot);if(!row||row.owner_user_id!==access.user.userId)return sharingJson({enabled:false});return sharingJson({enabled:Boolean(row.enabled),snapshot:validatePublicationSnapshot(JSON.parse(row.snapshot_json)),updatedAt:new Date(row.updated_at).toISOString()});}catch{return sharingJson({error:'Publication status unavailable.'},503);}}
export async function POST(request:Request){const access=await sharingOwner(request);if(access.error)return access.error;let body:Record<string,unknown>;try {body=strictObject(await boundedJson(request),['action','input','asOf','previewHash']);}catch{return sharingJson({error:'Use supported publication fields.'},400);}
  if(body.action==='revoke'){if(Object.keys(body).length!==1)return sharingJson({error:'Use supported publication fields.'},400);try {const row=await publicationRow(env.DB,access.slot);if(row&&row.owner_user_id!==access.user.userId)return sharingJson({error:'Publication unavailable.'},409);if(row)await env.DB.prepare('UPDATE dive_publications SET enabled=0,updated_at=? WHERE slot=? AND owner_user_id=?').bind(Date.now(),access.slot,access.user.userId).run();return sharingJson({enabled:false});}catch{return sharingJson({error:'Publication could not be revoked.'},503);}}
  if(!['preview','publish'].includes(String(body.action)))return sharingJson({error:'Choose Preview, Publish or Revoke.'},400);
  let input;try {input=validatePublicationInput(body.input);}catch{return sharingJson({error:'Use only the selected public fields and an approved photo.'},400);}
  let asOf: string|undefined;if(body.action==='publish'){if(typeof body.asOf!=='string'||!Number.isFinite(Date.parse(body.asOf))||Math.abs(Date.now()-Date.parse(body.asOf))>15*60*1000||typeof body.previewHash!=='string')return sharingJson({error:'Preview this exact content again before publishing.'},409);asOf=body.asOf;}
  try {const preview=await publicationPreview(env.DB,access.user.userId,input,asOf);if(body.action==='preview')return sharingJson(preview);if(preview.previewHash!==body.previewHash)return sharingJson({error:'Evidence changed. Review a fresh exact visitor preview.'},409);const previous=await publicationRow(env.DB,access.slot);if(previous&&previous.owner_user_id!==access.user.userId)return sharingJson({error:'Publication unavailable.'},409);await ensurePublicationSchema(env.DB);const now=Date.now();await env.DB.prepare('INSERT INTO dive_publications (slot,owner_user_id,public_id,enabled,snapshot_json,photo_id,created_at,updated_at) VALUES (?,?,?,1,?,?,?,?) ON CONFLICT(slot) DO UPDATE SET enabled=1,snapshot_json=excluded.snapshot_json,photo_id=excluded.photo_id,updated_at=excluded.updated_at WHERE dive_publications.owner_user_id=excluded.owner_user_id').bind(access.slot,access.user.userId,crypto.randomUUID(),JSON.stringify(preview.snapshot),input.photoId??null,now,now).run();return sharingJson({enabled:true,snapshot:preview.snapshot});}catch{return sharingJson({error:'Publication could not be prepared or saved. Your private records have not changed.'},503);}
}
