'use client';
import {useEffect,useState} from 'react';
import {imageSource,storeDiveImage,type CardImage} from '@/lib/offline/dive-images';
import {currentDiveAccount} from '@/lib/offline/dive-store';
export function CardImageView({image,label}:{image:CardImage;label:string}){
  const [source,setSource]=useState('');useEffect(()=>{let alive=true;let objectUrl='';void imageSource(image,currentDiveAccount()).then(value=>{objectUrl=value;if(alive)setSource(value);else if(value.startsWith('blob:'))URL.revokeObjectURL(value);}).catch(()=>{if(alive)setSource('');});return()=>{alive=false;if(objectUrl.startsWith('blob:'))URL.revokeObjectURL(objectUrl);};},[image.attachmentId,image.remoteKey]);
  return source?<div className="cert-image-viewport"><img src={source} alt={label} loading="lazy" style={{objectPosition:`${image.x}% ${image.y}%`,transform:`scale(${image.zoom})`,transformOrigin:`${image.x}% ${image.y}%`}}/></div>:<p>{label}: image not available on this device yet.</p>;
}
export function CertificationImages({front,back,change}:{front:CardImage|null;back:CardImage|null;change:(side:'front'|'back',image:CardImage|null)=>void}){
  const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [url,setUrl]=useState({front:'',back:''});
  async function add(side:'front'|'back',file:File){setBusy(true);try{change(side,await storeDiveImage(file,currentDiveAccount()));setMessage('Image saved on this device. Save the certification to keep its reference.');}catch(error){setMessage(error instanceof Error?error.message:'Image failed');}finally{setBusy(false);}}
  return <div className="cert-image-slots record-wide">{(['front','back'] as const).map(side=>{const image=side==='front'?front:back;return <section key={side}><h3>Card {side}</h3>{image&&<><CardImageView image={image} label={`Certification card ${side}`}/>{(['zoom','x','y'] as const).map(field=><label key={field}>{field==='zoom'?'Zoom':field==='x'?'Horizontal crop':'Vertical crop'}<input type="range" min={field==='zoom'?1:0} max={field==='zoom'?3:100} step={field==='zoom'?0.05:1} value={image[field]} onChange={event=>change(side,{...image,[field]:Number(event.target.value)})}/></label>)}<button type="button" className="focus-secondary" onClick={()=>{if(confirm(`Remove card ${side}? The previous attachment remains recoverable in history.`))change(side,null);}}>Remove {side}</button></>}<label>Upload {side}<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>{const file=event.target.files?.[0];if(file)void add(side,file);}}/></label><label>Import image URL (online)<input type="url" value={url[side]} onChange={event=>setUrl({...url,[side]:event.target.value})}/></label><button type="button" className="focus-secondary" disabled={busy||!url[side]} onClick={async()=>{setBusy(true);try{const parsed=new URL(url[side]);if(!['http:','https:'].includes(parsed.protocol))throw new Error('Use an HTTPS image URL.');const response=await fetch(`/api/image-proxy?url=${encodeURIComponent(parsed.href)}`);if(!response.ok)throw new Error('This image URL could not be imported. Download it and upload the file instead.');const blob=await response.blob();await add(side,new File([blob],`card-${side}`,{type:blob.type}));}catch(error){setMessage(error instanceof Error?error.message:'Image import failed');}finally{setBusy(false);}}}>Import {side} URL</button></section>;})}{message&&<p role="status">{message}</p>}</div>;
}
