'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronRight, Clock3, FileText, Gauge, MapPin, Plus, ShieldCheck, Users, Waves, X } from 'lucide-react';
import { AccessibleDialog } from './accessible-dialog';
import { useRecordRefresh } from './record-status';
import { listDiveSites, listPeople, type DiveSiteRecord, type PersonRecord, type Stored } from '../lib/offline/dive-planning';
import { applyReusableLoadout, listReusableLoadouts, type LoadoutApplication, type ReusableLoadoutRecord } from '../lib/offline/loadouts-gas';
import { listCanonicalSkills, skillRecordName, type CanonicalSkillRecord } from '../lib/offline/dive-context';
import type { TechnicalPlanExtension } from '../lib/offline/technical-workspace';
import {
  DEFAULT_PLAN_CHECKLIST,
  createDiveDraftFromEnrichedPlan,
  evaluatePlanReadiness,
  listEnrichedDivePlans,
  saveEnrichedDivePlan,
  setPlanLifecycleStatus,
  type EnrichedDivePlan,
  type PlanChecklistItem,
  type PlanLifecycleStatus,
  type PlanTeamMember,
  type StoredEnrichedDivePlan,
} from '../lib/offline/dive-planning-centre';
import type { DiveRecord } from '../lib/offline/dives';
import { listDiveExpeditionTrips, saveDiveExpeditionTrip, type DiveExpeditionTripRecord } from '../lib/offline/trips-expeditions';
import { TechnicalPlanFields } from './technical-plan-fields';
import { CollapsibleWorkCard } from './workflow/collapsible-work-card';
import styles from './dive-planning-centre.module.css';

type Props={convertToDive:(draft:Partial<DiveRecord>)=>void;go?:(next:string)=>void};
type PlanDraft=Omit<EnrichedDivePlan,'createdAt'|'modifiedAt'>&Partial<Pick<StoredEnrichedDivePlan,'entityId'|'createdAt'|'modifiedAt'>>;
const localDate=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const emptyPlan=(technicalMode=false):Omit<EnrichedDivePlan,'createdAt'|'modifiedAt'>=>({name:'',planType:'day-dive',startDate:localDate(),endDate:localDate(),siteName:'',buddy:'',status:'planned',notes:'',lifecycleStatus:'draft',objective:'',plannedMaxDepthM:null,plannedDurationMin:null,plannedRuntimeMin:null,entryType:'',planTeam:[],equipmentSetId:null,equipmentSetIds:[],equipmentIds:[],equipmentSetApplications:[],cylinderAssignments:[],conditions:{},humanFactors:{keyRisks:[],mitigations:[],pressures:[],stopAbortCriteria:[],teamConcerns:[]},emergency:{},checklist:DEFAULT_PLAN_CHECKLIST.map(item=>({...item})),plannedSkillKeys:[],technicalMode,decoSchedule:[]});

export function DivePlanningCentre({convertToDive}:Props){
 const [plans,setPlans]=useState<StoredEnrichedDivePlan[]>([]);const [sites,setSites]=useState<Array<Stored<DiveSiteRecord>>>([]);const [people,setPeople]=useState<Array<Stored<PersonRecord>>>([]);const [loadouts,setLoadouts]=useState<Array<Stored<ReusableLoadoutRecord>>>([]);const [trips,setTrips]=useState<Array<Stored<DiveExpeditionTripRecord>>>([]);const [skills,setSkills]=useState<CanonicalSkillRecord[]>([]);const [selectedId,setSelectedId]=useState('');const [editing,setEditing]=useState<StoredEnrichedDivePlan|null|undefined>(undefined);const [showReadiness,setShowReadiness]=useState(false);const openedLink=useRef(false);
 const refresh=useCallback(async()=>{const [p,s,pe,l,expeditions,sk]=await Promise.all([listEnrichedDivePlans(),listDiveSites(),listPeople(),listReusableLoadouts(),listDiveExpeditionTrips(),listCanonicalSkills()]);const sorted=p.sort((a,b)=>(a.startAt||a.startDate).localeCompare(b.startAt||b.startDate));setPlans(sorted);setSites(s);setPeople(pe);setLoadouts(l);setTrips(expeditions);setSkills(sk);const linkedId=new URLSearchParams(window.location.search).get('planId');setSelectedId(current=>current&&sorted.some(item=>item.entityId===current)?current:linkedId&&sorted.some(item=>item.entityId===linkedId)?linkedId:(sorted[0]?.entityId??''));},[]);useRecordRefresh(refresh);
 useEffect(()=>{if(openedLink.current)return;const params=new URLSearchParams(window.location.search);if(params.get('newPlan')==='technical'){openedLink.current=true;const frame=requestAnimationFrame(()=>setEditing(null));return()=>cancelAnimationFrame(frame);}if(!params.get('planId'))openedLink.current=true;},[]);
 const plan=plans.find(item=>item.entityId===selectedId)??null;const readiness=useMemo(()=>plan?evaluatePlanReadiness(plan):null,[plan]);const site=plan?.siteId?sites.find(item=>item.entityId===plan.siteId):null;const loadout=plan?.equipmentSetId?loadouts.find(item=>item.entityId===plan.equipmentSetId):plan?.equipmentSetIds?.[0]?loadouts.find(item=>item.entityId===plan.equipmentSetIds?.[0]):null;const team=(plan?.planTeam??[]).map(item=>({link:item,person:people.find(person=>person.entityId===item.personId)}));
 async function startDive(){if(!plan)return;const draft=await createDiveDraftFromEnrichedPlan(plan.entityId);await setPlanLifecycleStatus(plan,'in_progress');convertToDive(draft);}
 if(!plans.length)return <main className={styles.page}><Hero/><section className={`focus-card ${styles.empty}`}><h2>Create your first operational Dive Plan</h2><p>Keep an ordinary recreational plan quick, then disclose gas, technical and professional detail only when needed.</p><button className="focus-primary" onClick={()=>setEditing(null)}><Plus/>New plan</button></section>{editing!==undefined&&<PlanEditor item={editing} sites={sites} people={people} loadouts={loadouts} trips={trips} skills={skills} close={()=>setEditing(undefined)} saved={async()=>{setEditing(undefined);await refresh();}}/>}</main>;
 return <main className={styles.page}><Hero action={<button className="focus-primary" onClick={()=>setEditing(null)}><Plus/>New plan</button>}/><div className={styles.planTabs}>{plans.filter(item=>!['completed','cancelled'].includes(item.lifecycleStatus??'')).map(item=><button key={item.entityId} className={item.entityId===selectedId?styles.active:''} onClick={()=>setSelectedId(item.entityId)}><span>{item.startDate.slice(5)}</span><b>{item.name}</b><small>{item.siteName||'Site not chosen'}</small></button>)}</div>{plan&&<>
 <section className={styles.upcoming}><div className={styles.siteArt} style={{backgroundImage:`linear-gradient(180deg,transparent,rgba(0,0,0,.65)),url('/zeustek-hero.png')`}}/><div className={styles.upcomingMain}><span className="focus-eyebrow">UPCOMING DIVE PLAN</span><h2>{plan.name}</h2><p><Clock3/> {plan.startAt||plan.startDate} <Users/> {team.length||plan.personIds?.length||1} diver{(team.length||plan.personIds?.length||1)===1?'':'s'}</p><p><MapPin/> {site?.name||plan.siteName||'Site not selected'}</p></div><div className={styles.upcomingLoadout}><span className="focus-eyebrow">EQUIPMENT SET</span><b>{loadout?.name||'Not selected'}</b><small>{loadout?.intendedUse||'Choose a reusable loadout'}</small></div><button className={styles.readiness} data-state={readiness?.state} aria-haspopup="dialog" aria-label="Review plan readiness" onClick={()=>setShowReadiness(true)}><CheckCircle2/><span><b>{readiness?.state==='ready'?'Plan ready':readiness?.state==='needs-attention'?'Needs attention':'Draft plan'}</b><small>{readiness?.completed}/{readiness?.total} readiness checks</small></span><ChevronRight/></button></section>
 <section className={styles.grid}>
  <PlanCard title="SITE & CONDITIONS" icon={<Waves/>} onOpen={()=>setEditing(plan)}><div className={styles.siteCard}><b>{site?.name||plan.siteName||'Choose a Site'}</b><small>{site?.location||''}</small><div><Metric label="Entry" value={plan.entryType||'Not set'}/><Metric label="Max depth" value={plan.plannedMaxDepthM==null?'—':`${plan.plannedMaxDepthM} m`}/><Metric label="Runtime" value={plan.plannedRuntimeMin==null?'—':`${plan.plannedRuntimeMin} min`}/></div><p>{plan.conditions?.weather||plan.conditions?.currentStrength||plan.conditions?.notes||'No conditions snapshot recorded.'}</p></div></PlanCard>
  <PlanCard title="TEAM & ROLES" icon={<Users/>} onOpen={()=>setEditing(plan)}>{team.length?<div className={styles.rows}>{team.map(({link,person})=><div key={link.personId}><span><b>{person?.name||'Unavailable person'}</b><small>{link.role}</small></span></div>)}</div>:<p className={styles.muted}>No canonical People linked yet.</p>}</PlanCard>
  <PlanCard title="EQUIPMENT & GAS" icon={<Gauge/>} onOpen={()=>setEditing(plan)}><div className={styles.rows}><div><span><b>{loadout?.name||'No loadout'}</b><small>{loadout?.description||''}</small></span></div>{(plan.cylinderAssignments??[]).map((cylinder,index)=><div key={cylinder.id||index}><span><b>{cylinder.role||`Cylinder ${index+1}`}</b><small>{cylinder.gasLabel||'Gas not recorded'}</small></span><em>{cylinder.startPressureBar==null?'—':`${cylinder.startPressureBar} bar`}</em></div>)}</div></PlanCard>
  <PlanCard title="SAFETY & HF (INTEGRATED)" icon={<AlertTriangle/>} onOpen={()=>setEditing(plan)}><HFRows plan={plan}/></PlanCard>
  <PlanCard title="EMERGENCY & CHECKLISTS" icon={<ShieldCheck/>} onOpen={()=>setEditing(plan)}><div className={styles.rows}><div><span><b>Oxygen & first aid</b><small>{plan.emergency?.oxygenFirstAid||'Not recorded'}</small></span></div><div><span><b>Emergency contact</b><small>{plan.emergency?.emergencyContact||'Not recorded'}</small></span></div><div><span><b>Pre-dive checklist</b><small>{plan.checklist?.filter(item=>item.completed).length??0}/{plan.checklist?.length??0} complete</small></span></div><div><span><b>Contingency</b><small>{plan.emergency?.alternateSite||plan.emergency?.evacuation||'Not recorded'}</small></span></div></div></PlanCard>
  <PlanCard title="PLAN NOTES" icon={<FileText/>} onOpen={()=>setEditing(plan)}><p className={styles.notes}>{plan.notes||plan.objective||'No plan notes yet.'}</p></PlanCard>
 </section>
 <section className={styles.actions}><button className="focus-secondary" onClick={()=>setEditing(plan)}><FileText/>Save / edit draft</button><button className={styles.readyButton} disabled={readiness?.state!=='ready'} onClick={()=>void setPlanLifecycleStatus(plan,'ready').then(refresh)}><CheckCircle2/>Mark ready</button><button className="focus-primary" onClick={()=>void startDive()}><Gauge/>Start dive</button></section>
 </>}{editing!==undefined&&<PlanEditor item={editing} sites={sites} people={people} loadouts={loadouts} trips={trips} skills={skills} close={()=>setEditing(undefined)} saved={async()=>{setEditing(undefined);await refresh();}}/>}{showReadiness&&readiness&&plan&&<div className="focus-modal-bg"><AccessibleDialog label="Plan readiness" close={()=>setShowReadiness(false)} className={`focus-modal ${styles.readinessDialog}`}><header><div><span className="focus-eyebrow">ADVISORY READINESS</span><h2>{readiness.state==='ready'?'Plan ready':readiness.state==='needs-attention'?'Needs attention':'Draft plan'}</h2><p>{readiness.completed} of {readiness.total} checks complete · {readiness.percent}%</p></div><button className="focus-icon" data-dialog-close aria-label="Close plan readiness" onClick={()=>setShowReadiness(false)}><X/></button></header>{readiness.warnings.length?<><h3>Before marking ready</h3><ul>{readiness.warnings.map(warning=><li key={warning}>{warning}</li>)}</ul></>:<p><CheckCircle2/> All configured readiness checks are complete.</p>}<p className={styles.help}>Readiness is advisory and does not replace training, judgement, a briefing or a separately validated decompression plan.</p><footer><button className="focus-secondary" data-dialog-close onClick={()=>setShowReadiness(false)}>Close</button><button className="focus-primary" onClick={()=>{setShowReadiness(false);setEditing(plan);}}>Review plan</button></footer></AccessibleDialog></div>}</main>;
}
function Hero({action}:{action?:React.ReactNode}){return <header className={styles.hero}><div><span className="focus-eyebrow">DIVE PLANNING CENTRE</span><h1>Dive Planning Centre</h1><p>Plan → Prepare → Dive → Debrief</p></div><div className={styles.heroQuote}>Better dives through<br/>better planning.<i/></div>{action}</header>}
function PlanCard({title,icon,onOpen,children}:{title:string;icon:React.ReactNode;onOpen:()=>void;children:React.ReactNode}){const id=`dive-plan-${title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;return <CollapsibleWorkCard id={id} title={title} eyebrow="PLAN WORKBENCH" status={<span>{icon} Ready to review</span>} onOpenDetail={onOpen}>{children}</CollapsibleWorkCard>}
function Metric({label,value}:{label:string;value:string}){return <span><small>{label}</small><b>{value}</b></span>}
function HFRows({plan}:{plan:EnrichedDivePlan}){const hf=plan.humanFactors??{};const rows=[['Key risks',(hf.keyRisks??[]).join(', ')],['Mitigations',(hf.mitigations??[]).join(', ')],['Stop / abort criteria',(hf.stopAbortCriteria??[]).join(', ')],['Team concerns',(hf.teamConcerns??[]).join(', ')],['Task loading',hf.taskLoading??'']];return <div className={styles.rows}>{rows.map(([label,value])=><div key={label}><span><b>{label}</b><small>{value||'None noted'}</small></span></div>)}</div>}

function PlanEditor({item,sites,people,loadouts,trips,skills,close,saved}:{item:StoredEnrichedDivePlan|null;sites:Array<Stored<DiveSiteRecord>>;people:Array<Stored<PersonRecord>>;loadouts:Array<Stored<ReusableLoadoutRecord>>;trips:Array<Stored<DiveExpeditionTripRecord>>;skills:CanonicalSkillRecord[];close:()=>void;saved:()=>void}){
 const source:PlanDraft=item?{...item}:emptyPlan(typeof window!=='undefined'&&new URLSearchParams(window.location.search).get('newPlan')==='technical');const [draft,setDraft]=useState<PlanDraft>(()=>source);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const closeButtonRef=useRef<HTMLButtonElement>(null);const update=(patch:Partial<PlanDraft>)=>setDraft(current=>({...current,...patch}));const hf=draft.humanFactors??{};const emergency=draft.emergency??{};const checklist:PlanChecklistItem[]=draft.checklist??DEFAULT_PLAN_CHECKLIST;
 const technical:TechnicalPlanExtension={technicalMode:draft.technicalMode??false,maxDepthM:draft.plannedMaxDepthM??draft.maxDepthM??null,bottomTimeMin:draft.plannedDurationMin??draft.bottomTimeMin??null,plannedRuntimeMin:draft.plannedRuntimeMin??null,cylinderAssignments:draft.cylinderAssignments??[],decoSchedule:draft.decoSchedule??[]};
 const changeTechnical=(value:TechnicalPlanExtension)=>update({technicalMode:value.technicalMode??false,maxDepthM:value.maxDepthM??null,plannedMaxDepthM:value.maxDepthM??null,bottomTimeMin:value.bottomTimeMin??null,plannedDurationMin:value.bottomTimeMin??null,plannedRuntimeMin:value.plannedRuntimeMin??null,cylinderAssignments:value.cylinderAssignments??[],decoSchedule:value.decoSchedule??[]});
 async function save(){setBusy(true);setError('');try{const site=sites.find(s=>s.entityId===draft.siteId);const selectedLoadout=loadouts.find(loadout=>loadout.entityId===draft.equipmentSetId);const requiresApplication=Boolean(selectedLoadout)&&((source.equipmentSetId??null)!==(draft.equipmentSetId??null)||!(source.equipmentSetApplications??[]).some((application:LoadoutApplication)=>application.equipmentSetId===draft.equipmentSetId));const result=await saveEnrichedDivePlan({...draft,...(item?{entityId:item.entityId}:{}),siteName:site?.name||draft.siteName||'',startDate:(draft.startAt||draft.startDate||localDate()).slice(0,10),endDate:draft.endDate||draft.startDate||localDate()});if(selectedLoadout&&requiresApplication)await applyReusableLoadout('trip',result.id,selectedLoadout);if(source.tripId&&source.tripId!==draft.tripId){const oldTrip=trips.find(trip=>trip.entityId===source.tripId);if(oldTrip)await saveDiveExpeditionTrip({...oldTrip,entityId:oldTrip.entityId,planIds:oldTrip.planIds.filter(planId=>planId!==result.id)});}if(draft.tripId){const selectedTrip=trips.find(trip=>trip.entityId===draft.tripId);if(selectedTrip&&!selectedTrip.planIds.includes(result.id))await saveDiveExpeditionTrip({...selectedTrip,entityId:selectedTrip.entityId,planIds:[...selectedTrip.planIds,result.id]});}saved();}catch(reason){setError(reason instanceof Error?reason.message:'The Dive Plan could not be saved.');}finally{setBusy(false);}}
 const toggleSkill=(value:string)=>{const next=new Set(draft.plannedSkillKeys??[]);if(next.has(value))next.delete(value);else next.add(value);update({plannedSkillKeys:[...next]});};
 return <div className="focus-modal-bg"><AccessibleDialog editable onEscape={()=>{if(!busy)closeButtonRef.current?.click();}} label={item?'Edit Dive Plan':'New Dive Plan'} close={close} className={`focus-modal ${styles.editor}`}><header><div><span className="focus-eyebrow">PLAN → PREPARE → DIVE</span><h2>{item?'Edit Dive Plan':'New Dive Plan'}</h2></div><button ref={closeButtonRef} className="focus-icon" data-dialog-close aria-label="Close Dive Plan editor" disabled={busy} onClick={close}><X/></button></header><div className={styles.editorGrid}>
  <fieldset><legend>Plan identity</legend><label>Name<input value={draft.name??''} onChange={e=>update({name:e.target.value})}/></label><label>Lifecycle<select value={draft.lifecycleStatus??'draft'} onChange={e=>update({lifecycleStatus:e.target.value as PlanLifecycleStatus})}><option value="draft">Draft</option><option value="planned">Planned</option><option value="ready" disabled>Ready (use Mark ready)</option><option value="in_progress" disabled>In progress (use Start dive)</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label>Start<input type="datetime-local" value={draft.startAt??''} onChange={e=>update({startAt:e.target.value,startDate:e.target.value.slice(0,10)})}/></label><label>Trip / expedition<select value={draft.tripId??''} onChange={e=>update({tripId:e.target.value||null})}><option value="">Not linked</option>{draft.tripId&&!trips.some(trip=>trip.entityId===draft.tripId)&&<option value={draft.tripId}>Unavailable Trip · reference retained</option>}{trips.map(trip=><option key={trip.entityId} value={trip.entityId}>{trip.name}{trip.destination?` · ${trip.destination}`:''}</option>)}</select></label><label className={styles.wide}>Objective<textarea value={draft.objective??''} onChange={e=>update({objective:e.target.value})}/></label></fieldset>
  <fieldset><legend>Site & conditions</legend><label>Site<select value={draft.siteId??''} onChange={e=>update({siteId:e.target.value,siteName:sites.find(s=>s.entityId===e.target.value)?.name??''})}><option value="">Choose Site</option>{sites.map(s=><option key={s.entityId} value={s.entityId}>{s.name}</option>)}</select></label><label>Entry type<input value={draft.entryType??''} onChange={e=>update({entryType:e.target.value})}/></label><label>Max depth (m)<input type="number" min="0" step="0.1" value={draft.plannedMaxDepthM??''} onChange={e=>update({plannedMaxDepthM:e.target.value?Number(e.target.value):null,maxDepthM:e.target.value?Number(e.target.value):null})}/></label><label>Bottom time (min)<input type="number" min="0" value={draft.plannedDurationMin??''} onChange={e=>update({plannedDurationMin:e.target.value?Number(e.target.value):null,bottomTimeMin:e.target.value?Number(e.target.value):null})}/></label><label>Runtime (min)<input type="number" min="0" value={draft.plannedRuntimeMin??''} onChange={e=>update({plannedRuntimeMin:e.target.value?Number(e.target.value):null})}/></label><label>Weather / surface<input value={draft.conditions?.weather??''} onChange={e=>update({conditions:{...draft.conditions,weather:e.target.value,provenance:'recorded',capturedAt:new Date().toISOString()}})}/></label><label>Current<input value={draft.conditions?.currentStrength??''} onChange={e=>update({conditions:{...draft.conditions,currentStrength:e.target.value,provenance:'recorded',capturedAt:new Date().toISOString()}})}/></label><label>Water temperature (°C)<input type="number" step="0.1" value={draft.conditions?.waterTemperatureC??''} onChange={e=>update({conditions:{...draft.conditions,waterTemperatureC:e.target.value?Number(e.target.value):null,provenance:'recorded',capturedAt:new Date().toISOString()}})}/></label><label>Tide summary<input value={draft.conditions?.tideSummary??''} onChange={e=>update({conditions:{...draft.conditions,tideSummary:e.target.value,provenance:'recorded',capturedAt:new Date().toISOString()}})}/></label><label className={styles.wide}>Conditions notes<textarea value={draft.conditions?.notes??''} onChange={e=>update({conditions:{...draft.conditions,notes:e.target.value,provenance:'recorded',capturedAt:new Date().toISOString()}})}/></label>{draft.conditions?.capturedAt&&<small className={styles.wide}>Recorded snapshot · {new Date(draft.conditions.capturedAt).toLocaleString('en-GB')}</small>}</fieldset>
  <fieldset><legend>Team & roles</legend><div className={styles.choiceList}>{people.map(person=>{const rows:PlanTeamMember[]=[...(draft.planTeam??[])];const existing=rows.find(row=>row.personId===person.entityId);return <div className={styles.teamRow} key={person.entityId}><label><input type="checkbox" checked={Boolean(existing)} onChange={e=>{const next=rows.filter(row=>row.personId!==person.entityId);if(e.target.checked)next.push({personId:person.entityId,role:'Diver'});update({planTeam:next});}}/>{person.name}</label>{existing&&<select aria-label={`Role for ${person.name}`} value={existing.role||'Diver'} onChange={e=>update({planTeam:rows.map(row=>row.personId===person.entityId?{...row,role:e.target.value}:row)})}><option>Diver</option><option>Buddy</option><option>Team leader</option><option>Instructor</option><option>Divemaster</option><option>Surface support</option></select>}</div>})}</div></fieldset>
  <fieldset><legend>Equipment & gas</legend><label>Reusable loadout<select value={draft.equipmentSetId??''} onChange={e=>update({equipmentSetId:e.target.value||null,equipmentSetIds:e.target.value?[e.target.value]:[]})}><option value="">Choose loadout</option>{loadouts.map(item=><option key={item.entityId} value={item.entityId}>{item.name}</option>)}</select></label><p className={styles.help}>The selected loadout is applied as stable Equipment IDs and a slot snapshot; later Equipment edits do not rewrite this Plan.</p><TechnicalPlanFields value={technical} change={changeTechnical}/></fieldset>
  <fieldset><legend>Safety & human factors</legend><label className={styles.wide}>Key risks<textarea value={(hf.keyRisks??[]).join('\n')} onChange={e=>update({humanFactors:{...hf,keyRisks:e.target.value.split('\n').map((v:string)=>v.trim()).filter(Boolean)}})}/></label><label className={styles.wide}>Mitigations<textarea value={(hf.mitigations??[]).join('\n')} onChange={e=>update({humanFactors:{...hf,mitigations:e.target.value.split('\n').map((v:string)=>v.trim()).filter(Boolean)}})}/></label><label className={styles.wide}>Stop / abort criteria<textarea value={(hf.stopAbortCriteria??[]).join('\n')} onChange={e=>update({humanFactors:{...hf,stopAbortCriteria:e.target.value.split('\n').map((v:string)=>v.trim()).filter(Boolean)}})}/></label><label className={styles.wide}>Task loading<textarea value={hf.taskLoading??''} onChange={e=>update({humanFactors:{...hf,taskLoading:e.target.value}})}/></label></fieldset>
  <fieldset><legend>Emergency</legend><label>Oxygen & first aid<input value={emergency.oxygenFirstAid??''} onChange={e=>update({emergency:{...emergency,oxygenFirstAid:e.target.value}})}/></label><label>Emergency contact<input value={emergency.emergencyContact??''} onChange={e=>update({emergency:{...emergency,emergencyContact:e.target.value}})}/></label><label>Alternate site<input value={emergency.alternateSite??''} onChange={e=>update({emergency:{...emergency,alternateSite:e.target.value}})}/></label><label className={styles.wide}>Evacuation / contingency<textarea value={emergency.evacuation??''} onChange={e=>update({emergency:{...emergency,evacuation:e.target.value}})}/></label></fieldset>
  <fieldset><legend>Checklist</legend><div className={styles.choiceList}>{checklist.map(row=><label key={row.id}><input type="checkbox" checked={row.completed} onChange={e=>update({checklist:checklist.map(item=>item.id===row.id?{...item,completed:e.target.checked}:item)})}/>{row.label}</label>)}</div></fieldset>
  <fieldset><legend>Planned skills</legend><div className={styles.choiceList}>{skills.filter(skill=>!skill.archived).slice(0,80).map(skill=><label key={skill.entityId}><input type="checkbox" checked={(draft.plannedSkillKeys??[]).includes(skill.entityId)} onChange={()=>toggleSkill(skill.entityId)}/>{skillRecordName(skill)}</label>)}</div></fieldset>
  <fieldset><legend>Notes</legend><label className={styles.wide}>Plan notes<textarea value={draft.notes??''} onChange={e=>update({notes:e.target.value})}/></label></fieldset>
 </div>{error&&<p role="alert" className="dive-save-error">{error}</p>}<footer><button className="focus-secondary" data-dialog-close disabled={busy} onClick={close}>Cancel</button><button className="focus-primary" disabled={!draft.name?.trim()||busy} onClick={()=>void save()}>{busy?'Saving…':'Save plan'}</button></footer></AccessibleDialog></div>;
}
