'use client';
import { useCallback,useState } from 'react';
import { strFromU8,unzipSync } from 'fflate';
import { listRecords,saveRecord,listCertifications,listDiveMedia,listTrainingProgress,type Stored,type DiveMediaRecord } from '@/lib/offline/dive-planning';
import { chooseDiagnosticQuestions,chooseQuestions,diagnosticCoverage,difficultyLabel,knowledgeEvidence,KNOWLEDGE_TOPICS,parseQuestionSet,QUESTION_DIFFICULTIES,questionSetSchema,relevantTopics,scoreQuestion,studyNeeds,type Question,type QuestionSet,type TestAttempt } from '@/lib/knowledge-tests';
import { useRecordRefresh } from './record-status';

function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);}
const jsonName=(name:string)=>name.toLowerCase().endsWith('.json');
async function questionFiles(file:File){
  if(file.size>25_000_000)throw new Error(`${file.name} is over the 25 MB archive limit.`);
  if(jsonName(file.name))return [{name:file.name,text:await file.text()}];
  const bytes=new Uint8Array(await file.arrayBuffer());
  if(file.name.toLowerCase().endsWith('.zip')){
    const entries=unzipSync(bytes,{filter:entry=>jsonName(entry.name)&&entry.originalSize<=2_000_000});return Object.entries(entries).slice(0,100).map(([name,data])=>({name,text:strFromU8(data)}));
  }
  if(file.name.toLowerCase().endsWith('.rar')){
    const [{createExtractorFromData},wasm]=await Promise.all([import('node-unrar-js/esm/index.esm.js'),fetch('/vendor/unrar.wasm').then(response=>{if(!response.ok)throw new Error('RAR reader could not load.');return response.arrayBuffer();})]);
    const extractor=await createExtractorFromData({data:bytes.buffer as ArrayBuffer,wasmBinary:wasm});
    return [...extractor.extract({files:header=>!header.flags.directory&&jsonName(header.name)&&header.unpSize<=2_000_000}).files].slice(0,100).flatMap(entry=>entry.extraction?[{name:entry.fileHeader.name,text:new TextDecoder().decode(entry.extraction)}]:[]);
  }
  throw new Error('Use a JSON question bank or a ZIP/RAR package containing JSON banks.');
}
function answerRationale(question:Question){
  const entries=question.options?.filter(option=>!question.answers.includes(option)).map(option=>[option,question.incorrectExplanations?.[option]] as const).filter((entry):entry is readonly [string,string]=>Boolean(entry[1]))??[];
  return entries.length?<div className="answer-rationales"><b>Why the other choices are wrong</b>{entries.map(([option,reason])=><p key={option}><strong>{option}:</strong> {reason}</p>)}</div>:null;
}
export function KnowledgeCentre({close,openMedia}:{close:()=>void;openMedia:(item:Stored<DiveMediaRecord>)=>void}){
  const [sets,setSets]=useState<Array<Stored<QuestionSet>>>([]);const [attempts,setAttempts]=useState<Array<Stored<TestAttempt>>>([]);const [media,setMedia]=useState<Array<Stored<DiveMediaRecord>>>([]);
  const [inputs,setInputs]=useState<TestAttempt['inputs']>({training:[],media:[],plan:[],focus:''});const [focus,setFocus]=useState('');const [exportTopics,setExportTopics]=useState<string[]>([]);const [message,setMessage]=useState('');const [review,setReview]=useState<Stored<QuestionSet>|null>(null);const [history,setHistory]=useState<Stored<TestAttempt>|null>(null);const [showAllHistory,setShowAllHistory]=useState(false);
  const [active,setActive]=useState<{startedAt:string;questions:ReturnType<typeof chooseQuestions>;inputs:TestAttempt['inputs'];diagnostic:boolean}|null>(null);const [answers,setAnswers]=useState<Record<string,string[]>>({});const [busy,setBusy]=useState(false);
  const refresh=useCallback(async()=>{const [nextSets,nextAttempts,training,nextMedia,plan]=await Promise.all([listRecords<QuestionSet>('question-set'),listRecords<TestAttempt>('test-attempt'),listCertifications(),listDiveMedia(),listTrainingProgress()]);setSets(nextSets);setAttempts(nextAttempts);setMedia(nextMedia);setInputs({training:training.map(item=>item.certification),media:nextMedia.filter(item=>item.status==='consumed').flatMap(item=>item.topics),plan:plan.filter(item=>item.status==='planned'||item.status==='in-progress').sort((a,b)=>(a.planOrder??999)-(b.planOrder??999)).map(item=>item.courseTitle),focus:''});},[]);useRecordRefresh(refresh);
  const topics=[...new Set([...KNOWLEDGE_TOPICS,...sets.flatMap(set=>set.questions.map(question=>question.topic))])];const reviewedTopics=[...new Set(sets.filter(set=>set.reviewed).flatMap(set=>set.questions.map(question=>question.topic)))];const evidence=knowledgeEvidence(attempts,topics);const coverage=diagnosticCoverage(attempts,KNOWLEDGE_TOPICS);const needs=studyNeeds(attempts);const weak=evidence.filter(item=>item.count&&item.percent!==null&&item.percent<70).sort((a,b)=>(a.percent??0)-(b.percent??0));
  const suggested=coverage.complete?(weak[0]?.topic??relevantTopics(inputs.plan,topics)[0]??relevantTopics(inputs.training,topics)[0]??''):'';
  const recommendations=coverage.complete?media.filter(item=>item.topics.some(topic=>weak.some(area=>area.topic.toLowerCase()===topic.toLowerCase()))).sort((a,b)=>Number(a.status==='consumed')-Number(b.status==='consumed')):[];
  async function importSets(files:FileList){setBusy(true);setMessage('Validating question package…');try{const known=new Set(sets.map(item=>`${item.setId}:${item.version}`));let imported=0;let skipped=0;for(const file of [...files])for(const entry of await questionFiles(file)){if(entry.text.length>2_000_000)throw new Error(`${entry.name} is over the 2 MB bank limit.`);const set=parseQuestionSet(JSON.parse(entry.text));const key=`${set.setId}:${set.version}`;if(known.has(key)){skipped++;continue;}known.add(key);await saveRecord('question-set',set);imported++;}if(!imported&&!skipped)throw new Error('No JSON question banks were found in the selected package.');setMessage(`${imported} question bank${imported===1?'':'s'} imported for review${skipped?`; ${skipped} existing version${skipped===1?'':'s'} skipped`:''}.`);await refresh();}catch(error){setMessage(error instanceof Error?error.message:'Import failed.');}finally{setBusy(false);}}
  function start(){const diagnostic=!focus;const questions=diagnostic?chooseDiagnosticQuestions(sets,attempts):chooseQuestions(sets,[focus]);if(!questions.length){setMessage('No reviewed questions match this area. Import a question set, review it, or choose another topic.');return;}setActive({startedAt:new Date().toISOString(),questions,inputs:{...inputs,focus:focus||'Full diagnostic'},diagnostic});setAnswers({});setMessage('');}
  async function finish(){if(!active)return;setBusy(true);try{const questions=active.questions.map(question=>{const response=answers[`${question.setId}:${question.setVersion}:${question.id}`]??[];return {...question,response,correct:scoreQuestion(question,response)};});const attempt:TestAttempt={startedAt:active.startedAt,completedAt:new Date().toISOString(),inputs:active.inputs,questions,correct:questions.filter(question=>question.correct).length,total:questions.length,diagnostic:active.diagnostic};await saveRecord('test-attempt',attempt);setMessage(`${attempt.correct} / ${attempt.total} correct. Your knowledge rank and exact study topics have been updated.`);setActive(null);await refresh();}catch(error){setMessage(error instanceof Error?error.message:'Could not save result.');}finally{setBusy(false);}}
  const requestTopics=exportTopics.length?exportTopics:[focus||suggested||'General scuba theory'];
  const request={format:'zeustek-question-request',version:2,topics:requestTopics,questionTypes:[{type:'single-choice',options:4,answers:1},{type:'multiple-response',options:6,answers:'one-or-more'},{type:'missing-word',options:4,answers:1},{type:'diagram-labels',options:4,answers:1},{type:'scenario-response',options:4,answers:1}],difficultyOrder:QUESTION_DIFFICULTIES,countPerTopic:12,requiredQuestionFields:['difficulty','topic','exactTopic','explanation','incorrectExplanations','studySources','provenance'],instructions:'Create original multiple-choice practice questions in ascending difficulty. Use precise exactTopic labels. Explain why the correct answer is right, why every distractor is wrong, and where the learner can read more. Include enough questions at each difficulty for a balanced diagnostic. Do not reproduce proprietary assessment banks. Mark reviewed false and return JSON conforming to the enclosed schema.',schema:questionSetSchema};
  if(active)return <section className="knowledge-centre"><div className="focus-card-head"><div><span className="focus-eyebrow">{active.diagnostic?'FULL DIAGNOSTIC':'FOCUSED PRACTICE'}</span><h1>{active.diagnostic?'Diagnostic assessment':'Practice test'}</h1></div><button className="focus-secondary" onClick={()=>{if(confirm('Discard this unfinished attempt?'))setActive(null);}}>Cancel</button></div><p>Questions progress from foundation knowledge to more demanding judgement.</p>{active.questions.map((question,index)=>{const id=`${question.setId}:${question.setVersion}:${question.id}`;const multiple=question.type==='multiple-response';const selected=answers[id]??[];return <fieldset className="focus-card question-card" key={id}><legend>{index+1}. {question.prompt}</legend><small>{question.topic} · {question.exactTopic||question.topic} · {difficultyLabel(question.difficulty)}</small>{question.diagramImage&&<img className="question-diagram" src={question.diagramImage} alt="Question diagram with a missing label"/>}{question.options?.map(option=><label className="question-option" key={option}><input type={multiple?'checkbox':'radio'} name={id} value={option} checked={selected.includes(option)} onChange={()=>setAnswers({...answers,[id]:multiple?(selected.includes(option)?selected.filter(value=>value!==option):[...selected,option]):[option]})}/>{option}</label>)}</fieldset>;})}<div className="record-actions"><button className="focus-primary" disabled={busy} onClick={()=>void finish()}>{busy?'Saving result…':'Finish and save result'}</button></div></section>;
  const orderedAttempts=[...attempts].sort((a,b)=>b.completedAt.localeCompare(a.completedAt));const visibleAttempts=showAllHistory?orderedAttempts:orderedAttempts.slice(0,5);
  return <section className="knowledge-centre"><div className="focus-card-head"><div><span className="focus-eyebrow">LEARN · REVIEW · PRACTISE</span><h1>Diving knowledge</h1></div><button className="focus-secondary" onClick={close}>Back to Dive Media</button></div><p>Practice supports learning; it does not certify diving competence or replace instructor assessment.</p>{message&&<p role="status" className="focus-notice">{message}</p>}
    <div className="focus-card test-launch-card"><h2>Take a test</h2>{!sets.length&&<p>No question bank is installed. Open question-bank tools below to export a request or import a package.</p>}<label>Focus area<select value={focus} onChange={event=>setFocus(event.target.value)}><option value="">Full diagnostic across every area</option>{topics.map(topic=><option key={topic}>{topic}</option>)}</select></label><p>{coverage.complete?'Core diagnostic complete. Knowledge-led study guidance is active.':`Complete a diagnostic in every core area before study guidance is applied. ${coverage.tested.length}/${KNOWLEDGE_TOPICS.length} areas tested.`}</p><button className="focus-primary" disabled={!sets.some(set=>set.reviewed)} onClick={start}>{focus?'Start focused test':'Continue full diagnostic'}</button><details className="question-tools"><summary>Question-bank import and export</summary><p>Select one or more topics for a combined request.</p><div className="question-topic-picker">{topics.map(topic=><label key={topic}><input type="checkbox" checked={exportTopics.includes(topic)} onChange={()=>setExportTopics(current=>current.includes(topic)?current.filter(value=>value!==topic):[...current,topic])}/>{topic}</label>)}</div><div className="record-actions"><button className="focus-secondary" onClick={()=>download(request,'zeustek-question-request.json')}>Export question request</button><label className="focus-secondary file-action">Import JSON / ZIP / RAR<input type="file" multiple accept="application/json,.json,application/zip,.zip,application/vnd.rar,application/x-rar-compressed,.rar" disabled={busy} onChange={event=>{if(event.target.files?.length)void importSets(event.target.files);event.target.value='';}}/></label></div></details></div>
    <div className="focus-card"><h2>Diagnostic coverage</h2><div className="diagnostic-progress"><b>{coverage.tested.length} of {KNOWLEDGE_TOPICS.length} core areas tested</b><progress value={coverage.tested.length} max={KNOWLEDGE_TOPICS.length}/></div>{coverage.missing.length?<p>Still to test: {coverage.missing.join(', ')}.</p>:<p>All core areas have diagnostic evidence.</p>}{KNOWLEDGE_TOPICS.filter(topic=>!reviewedTopics.includes(topic)).length>0&&<p>Question banks are still needed for: {KNOWLEDGE_TOPICS.filter(topic=>!reviewedTopics.includes(topic)).join(', ')}.</p>}</div>
    <div className="focus-card"><h2>Knowledge map</h2><div className="knowledge-grid">{evidence.map(area=><button key={area.topic} onClick={()=>setFocus(area.topic)}><b>{area.topic}</b><strong>{area.rank}</strong><span>{area.percent===null?'Unknown — not tested':`${area.percent}% weighted mastery · ${area.count} current exact topics`}</span>{area.percent!==null&&<progress value={area.percent} max={100} aria-label={`${area.topic}: ${area.percent}% weighted mastery`}/>}</button>)}</div></div>
    {coverage.complete&&needs.length>0&&<div className="focus-card"><h2>Your study plan</h2><p>Only the latest answer for each exact topic is used. A later correct answer clears the earlier weakness.</p>{needs.map((question,index)=><details key={`${question.topic}:${question.exactTopic}:${index}`}><summary>{question.topic} · {question.exactTopic||question.topic} · {difficultyLabel(question.difficulty)}</summary><p><b>Review:</b> {question.explanation}</p>{question.studySources?.length?<><b>Read more</b><ul>{question.studySources.map(source=><li key={source}>{/^https?:\/\//i.test(source)?<a href={source} target="_blank" rel="noreferrer">{source}</a>:source}</li>)}</ul></>:null}</details>)}</div>}
    {!!recommendations.length&&<div className="focus-card"><h2>Media for your study plan</h2>{recommendations.map(item=><button className="focus-link" key={item.entityId} onClick={()=>openMedia(item)}>{item.title}{item.status==='consumed'?' · revisit completed media':''}</button>)}</div>}
    <div className="focus-card"><h2>Previous test results</h2>{visibleAttempts.map(attempt=><button className="history-row" key={attempt.entityId} onClick={()=>setHistory(attempt)}>{new Date(attempt.completedAt).toLocaleString()} · {attempt.correct}/{attempt.total} · {attempt.inputs.focus}</button>)}{!attempts.length&&<p>No completed attempts yet.</p>}{orderedAttempts.length>5&&<button className="focus-secondary" onClick={()=>setShowAllHistory(value=>!value)}>{showAllHistory?'Show latest five':'… more'}</button>}</div>
    {history&&<div className="focus-card"><h2>Attempt details</h2><p>{history.inputs.focus} · {history.correct}/{history.total}</p>{history.questions.map((question,index)=><details key={`${question.id}:${index}`}><summary>{question.correct?'Correct':'Review'} — {question.exactTopic||question.topic}: {question.prompt}</summary><p>Your answer: {(Array.isArray(question.response)?question.response.join(' / '):question.response)||'Unanswered'}</p><p>Expected: {question.answers.join(' / ')}</p><p>{question.explanation}</p>{answerRationale(question)}{question.studySources?.length?<p>Read more: {question.studySources.join(' · ')}</p>:null}<small>Set {question.setId} v{question.setVersion} · {question.provenance}</small></details>)}<button className="focus-secondary" onClick={()=>setHistory(null)}>Close attempt</button></div>}
    {review&&<div className="focus-card"><h2>Review {review.title}</h2><p>Provenance: {review.provenance}</p>{review.questions.map(question=><details key={question.id}><summary>{question.prompt}</summary><p>{question.topic} · {question.exactTopic||question.topic} · {difficultyLabel(question.difficulty)}</p><p>Answer: {question.answers.join(' / ')}</p><p>{question.explanation}</p>{answerRationale(question)}{question.studySources?.length?<p>Read more: {question.studySources.join(' · ')}</p>:null}<p>{question.provenance}</p></details>)}<button className="focus-primary" onClick={async()=>{await saveRecord('question-set',{...review,reviewed:true});setReview(null);await refresh();}}>I have reviewed these questions — enable set</button><button className="focus-secondary" onClick={()=>setReview(null)}>Close review</button></div>}
    <details className="focus-card question-bank-list"><summary>Question banks ({sets.filter(set=>set.reviewed).length} reviewed · {sets.length} total)</summary>{sets.map(set=><div className="focus-card-head" key={set.entityId}><span>{set.title} · v{set.version} · {set.questions.length} questions · {set.reviewed?'Reviewed':'Needs review'}</span><button className="focus-secondary" onClick={()=>setReview(set)}>Review questions</button></div>)}{!sets.length&&<p>No question banks imported.</p>}</details>
  </section>;
}
