'use client';
import { useCallback,useState } from 'react';
import { useRecordRefresh } from './record-status';
import { listEquipment,type EquipmentRecord,type Stored } from '../lib/offline/dive-planning';
import { listCylinderFills,listGasAnalyses,deriveCylinderCurrentState,isCylinderEquipment,type CylinderFillRecord,type GasAnalysisRecord } from '../lib/offline/loadouts-gas';
import type { TechnicalPlanExtension } from '../lib/offline/technical-workspace';
export function TechnicalPlanFields({value,change}:{value:TechnicalPlanExtension;change:(value:TechnicalPlanExtension)=>void}) {
  const [equipment,setEquipment] = useState<Array<Stored<EquipmentRecord>>>([]);const [fills,setFills] = useState<Array<Stored<CylinderFillRecord>>>([]);const [analyses,setAnalyses] = useState<Array<Stored<GasAnalysisRecord>>>([]);
  useRecordRefresh(useCallback(async () => {const [e,f,a] = await Promise.all([listEquipment(),listCylinderFills(),listGasAnalyses()]);setEquipment(e);setFills(f);setAnalyses(a);},[]));
  const number = (text:string) => text === '' ? null : Number(text);
  return <section className="technical-plan-fields record-wide"><label><input type="checkbox" checked={value.technicalMode ?? false} onChange={event => change({...value,technicalMode:event.target.checked})}/>Technical planning (recorded / imported only)</label>{value.technicalMode && <details open><summary>Gas &amp; decompression evidence</summary><p>Advisory record, not a decompression engine or permission to dive. Enter a separately validated plan; no runtime or stop durations are calculated here.</p><div className="trip-link-fields">{([['maxDepthM','Maximum planned depth (m)'],['bottomTimeMin','Planned bottom time (min)'],['plannedRuntimeMin','Planned runtime (min)']] as const).map(([key,label]) => <label key={key}>{label}<input type="number" min="0" value={value[key] ?? ''} onChange={event => change({...value,[key]:number(event.target.value)})}/></label>)}</div><h4>Canonical cylinder assignments</h4>{(value.cylinderAssignments ?? []).map((gas,index) => {const cylinderFills = fills.filter(fill => fill.cylinderEquipmentId === gas.cylinderEquipmentId);const cylinderAnalyses = analyses.filter(analysis => analysis.cylinderEquipmentId === gas.cylinderEquipmentId);const current = deriveCylinderCurrentState({},cylinderFills,cylinderAnalyses);
    const set = (next:typeof gas) => change({...value,cylinderAssignments:value.cylinderAssignments?.map((item,i) => i === index ? next : item)});
    return <fieldset key={gas.id}><legend>Cylinder {index+1}</legend><div className="trip-link-fields"><label>Cylinder equipment<select value={gas.cylinderEquipmentId ?? ''} onChange={event => set({...gas,cylinderEquipmentId:event.target.value,fillId:null,analysisId:null})}><option value="">Not assigned</option>{equipment.filter(isCylinderEquipment).map(item => <option key={item.entityId} value={item.entityId}>{item.name}</option>)}</select></label><label>Role<input value={gas.role ?? ''} onChange={event => set({...gas,role:event.target.value})}/></label><label>Declared gas label<input value={gas.gasLabel ?? ''} onChange={event => set({...gas,gasLabel:event.target.value})}/></label><label>Start pressure (bar)<input type="number" min="0" value={gas.startPressureBar ?? ''} onChange={event => set({...gas,startPressureBar:number(event.target.value)})}/></label><label>Switch depth (m)<input type="number" min="0" value={gas.switchDepthM ?? ''} onChange={event => set({...gas,switchDepthM:number(event.target.value)})}/></label><label>Fill evidence<select value={gas.fillId ?? ''} onChange={event => set({...gas,fillId:event.target.value || null,analysisId:null})}><option value="">Not linked</option>{cylinderFills.map(fill => <option key={fill.entityId} value={fill.entityId}>{fill.filledAt}</option>)}</select></label><label>Analysis evidence<select value={gas.analysisId ?? ''} onChange={event => set({...gas,analysisId:event.target.value || null})}><option value="">Not linked</option>{cylinderAnalyses.filter(analysis => analysis.fillId === gas.fillId).map(analysis => <option key={analysis.entityId} value={analysis.entityId}>{analysis.analysedAt}</option>)}</select></label></div><p role="status">Current cylinder analysis: {current.analysisState}{gas.analysisId && gas.analysisId !== current.currentAnalysis?.entityId ? ' · selected historical analysis is not current' : ''}</p><button type="button" className="focus-secondary" onClick={() => change({...value,cylinderAssignments:value.cylinderAssignments?.filter((_,i) => i !== index)})}>Remove cylinder assignment</button></fieldset>;
  })}<button type="button" className="focus-secondary" onClick={() => change({...value,cylinderAssignments:[...(value.cylinderAssignments ?? []),{id:crypto.randomUUID(),role:'',gasLabel:''}]})}>Add cylinder assignment</button><h4>Recorded / imported deco stops</h4>{(value.decoSchedule ?? []).map((stop,index) => <div className="trip-link-fields" key={index}><label>Stop depth (m)<input type="number" min="0" value={stop.depthM ?? ''} onChange={event => change({...value,decoSchedule:value.decoSchedule?.map((item,i) => i === index ? {...item,depthM:number(event.target.value)} : item)})}/></label><label>Stop duration (min)<input type="number" min="0" value={stop.durationMin ?? ''} onChange={event => change({...value,decoSchedule:value.decoSchedule?.map((item,i) => i === index ? {...item,durationMin:number(event.target.value)} : item)})}/></label><label>Stop gas<input value={stop.gas ?? ''} onChange={event => change({...value,decoSchedule:value.decoSchedule?.map((item,i) => i === index ? {...item,gas:event.target.value} : item)})}/></label><button type="button" className="focus-secondary" onClick={() => change({...value,decoSchedule:value.decoSchedule?.filter((_,i) => i !== index)})}>Remove stop</button></div>)}<button type="button" className="focus-secondary" onClick={() => change({...value,decoSchedule:[...(value.decoSchedule ?? []),{depthM:null,durationMin:null,gas:''}]})}>Add recorded stop</button></details>}</section>;
}
