'use client';
/* oxlint-disable next/no-html-link-for-pages -- Vinext uses the existing query-routed application shell. */

import { ClipboardCheck, Cylinder, Gauge, Plus, Settings2, X } from 'lucide-react';
import { useCallback, useMemo, useState } from 'react';
import { AccessibleDialog } from './accessible-dialog';
import { ZeusTekIcon } from './zeustek-icon';
import { useRecordRefresh } from './record-status';
import { listDives, type DiveRecord } from '../lib/offline/dives';
import { canonicalSkillGroups, skillRecordGroup, listCanonicalSkills, listSkillEvidence, skillRecordName, type CanonicalSkillRecord, type SkillEvidenceRecord } from '../lib/offline/dive-context';
import { listCertifications, listDiveTrips, type CertificationRecord, type DiveTripRecord, type Stored } from '../lib/offline/dive-planning';
import { listCurrencyPolicies, buildSkillsCurrencyProjection, type CurrencyPolicyRecord } from '../lib/offline/skills-currency';
import { listReusableLoadouts, listCylinderFills, listGasAnalyses, deriveCylinderCurrentState, type CylinderFillRecord, type GasAnalysisRecord, type ReusableLoadoutRecord } from '../lib/offline/loadouts-gas';
import {
  TECH_PATHWAY_STARTERS,
  configurationCompetence,
  emptyRequirementSet,
  evaluatePathwayReadiness,
  isTechnicalSkill,
  listReferenceRequirementSets,
  recentTechnicalPractice,
  saveReferenceRequirementSet,
  technicalDiveMetrics,
  technicalDrillCurrency,
  technicalPlans,
  type ReferenceRequirementSetRecord,
  type RequirementState,
  type TechnicalRequirementDefinition,
} from '../lib/offline/technical-workspace';
import styles from './technical-workspace.module.css';

const stateLabel:Record<RequirementState,string>={satisfied:'Captured rules met',not_satisfied:'Not satisfied',unknown:'Unknown',manual_review:'Manual review'};
function Card({children,className=''}:{children:React.ReactNode;className?:string | undefined}){return <section className={`focus-card ${className}`}>{children}</section>;}
function date(value?:string|null){return value?new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Not recorded';}

export function TechnicalWorkspace({go}:{go?:(section:string)=>void}){
 const [group,setGroup] = useState('');
 const [gasEvidence,setGasEvidence] = useState<{fills:Array<Stored<CylinderFillRecord>>;analyses:Array<Stored<GasAnalysisRecord>>}>({fills:[],analyses:[]});
 useRecordRefresh(useCallback(async()=>{const [fills,analyses]=await Promise.all([listCylinderFills(),listGasAnalyses()]);setGasEvidence({fills,analyses});},[]));
 const [dives,setDives]=useState<Array<DiveRecord&{entityId:string}>>([]);const [plans,setPlans]=useState<Array<Stored<DiveTripRecord>>>([]);const [skills,setSkills]=useState<CanonicalSkillRecord[]>([]);const [evidence,setEvidence]=useState<SkillEvidenceRecord[]>([]);const [policies,setPolicies]=useState<Array<Stored<CurrencyPolicyRecord>>>([]);const [sets,setSets]=useState<Array<Stored<ReusableLoadoutRecord>>>([]);const [certs,setCerts]=useState<Array<Stored<CertificationRecord>>>([]);const [references,setReferences]=useState<Array<Stored<ReferenceRequirementSetRecord>>>([]);const [editingReference,setEditingReference]=useState<Stored<ReferenceRequirementSetRecord>|null|undefined>(undefined);
 const refresh=useCallback(async()=>{const [diveRows,planRows,skillRows,evidenceRows,policyRows,setRows,certRows,refRows]=await Promise.all([listDives(),listDiveTrips(),listCanonicalSkills(),listSkillEvidence(),listCurrencyPolicies(),listReusableLoadouts(),listCertifications(),listReferenceRequirementSets()]);setDives(diveRows);setPlans(planRows);setSkills(skillRows);setEvidence(evidenceRows);setPolicies(policyRows);setSets(setRows);setCerts(certRows);setReferences(refRows);},[]);useRecordRefresh(refresh);
 const currency=useMemo(()=>buildSkillsCurrencyProjection(skills.filter((skill)=>!skill.archived),evidence,policies),[skills,evidence,policies]);const drills=group ? currency.filter(row=>skillRecordGroup(row.skill)===group) : technicalDrillCurrency(skills,currency);const configs=configurationCompetence(sets,skills,evidence);const metrics=technicalDiveMetrics(dives);const practice=recentTechnicalPractice(dives);const techPlans=technicalPlans(plans as Array<Stored<DiveTripRecord&import('../lib/offline/technical-workspace').TechnicalPlanExtension>>);const readiness=references.map((set)=>evaluatePathwayReadiness(set,{dives,certifications:certs,skills,evidence,equipmentSets:sets}));
 const pathwayCards=TECH_PATHWAY_STARTERS.filter(starter=>!readiness.some(row=>row.set.pathwayKey.toLocaleLowerCase('en-GB')===starter.key)).map(starter=>({starter}));
 const latestPlan=techPlans[0];
 return <>
  <header className={styles.heading}><div className="focus-heading-title"><ZeusTekIcon id="technical-diving" size="heading"/><div><span className="focus-eyebrow">TECHNICAL DIVING</span><h1>Technical Diving</h1><p>A derived workspace over your Dives, Plans, Skills, loadouts and gas evidence — never a second technical logbook.</p></div></div><a className="focus-primary" href="/?section=Dive%20Plans&newPlan=technical"><Plus size={17}/>New tec plan</a></header>
  <section className={styles.advisory} role="note">
   <p>Readiness is advisory, not certification, medical clearance or instructor authorisation. Recorded / imported metrics only.</p>
   <label>Canonical Skill Group<select value={group} onChange={event=>setGroup(event.target.value)}><option value="">Detected technical drills</option>{canonicalSkillGroups(skills).map(name=><option key={name}>{name}</option>)}</select></label>
  </section>
  <section className={styles.pathways}><h2>Progression pathway</h2><div>{pathwayCards.map(entry=><Card key={entry.starter.key} className={styles.pathwayCard}><span className="focus-eyebrow">REFERENCE NOT CAPTURED</span><h3>{entry.starter.label}</h3><p>No agency requirement numbers are bundled. Capture a dated source snapshot before ZeusTek claims readiness.</p><button className="focus-secondary" onClick={()=>setEditingReference(null)}>Capture reference snapshot</button></Card>)}</div></section>
  <div className={styles.dashboard}>
   <Card><h2>Current gas evidence · recorded</h2>{latestPlan?.cylinderAssignments?.map((gas,index)=>{const state=deriveCylinderCurrentState({},gasEvidence.fills.filter(fill=>fill.cylinderEquipmentId===gas.cylinderEquipmentId),gasEvidence.analyses.filter(analysis=>analysis.cylinderEquipmentId===gas.cylinderEquipmentId));return <article className={styles.gas} key={gas.id??index}><div><b>{gas.role||`Cylinder ${index+1}`}</b><span>Current analysis: {state.analysisState}</span><span>{gas.analysisId&&gas.analysisId!==state.currentAnalysis?.entityId?'Selected historical analysis is not current for the latest fill.':state.analysedMixLabel}</span></div></article>;})}<p>Declared Plan gases above are not a substitute for current fill-linked analysis. Historical evidence is retained.</p></Card>
   {readiness.map(row=><PathwayCard key={`history-${row.set.entityId}`} row={row} onEdit={()=>setEditingReference(row.set)}/>)}
   <Card><header><h2>Tec drills due</h2><button className="focus-link" onClick={()=>go?.('Skills & Currency')}>Skills &amp; Currency</button></header>{drills.length?drills.slice(0,7).map((row)=><article className={styles.row} key={row.skill.entityId}><div><b>{skillRecordName(row.skill)}</b><span>{row.projection.assessedAt?`Last evidence ${date(row.projection.assessedAt)}`:'No qualifying evidence'}</span></div><em data-state={row.projection.status}>{row.projection.status.replace('-',' ')}</em></article>):<p>No technical drill Skills were found. Use the canonical Skill catalogue; common drill names/groups are detected automatically.</p>}</Card>
   <Card><header><h2>Configurations</h2><button className="focus-link" onClick={()=>go?.('Loadouts & Gas')}>Loadouts</button></header>{configs.length?configs.map((row)=><article className={styles.config} key={row.loadout.entityId}><Settings2/><div><b>{row.loadout.name}</b><span>{row.evidenceCount} technical evidence occurrence{row.evidenceCount===1?'':'s'}</span></div><em>{row.latestEvidence?date(row.latestEvidence.performedAt):'No evidence'}</em></article>):<p>No technical loadouts detected yet. Mark intended use/tags such as technical, twinset, sidemount, stage or deco in T05 loadouts.</p>}</Card>
   <Card><header><h2>Planned gases</h2><button className="focus-link" onClick={()=>go?.('Dive Plans')}>Planner</button></header>{latestPlan?.cylinderAssignments?.length?latestPlan.cylinderAssignments.map((gas,index)=><article className={styles.gas} key={gas.id??index}><Cylinder/><div><b>{gas.role||`Cylinder ${index+1}`}</b><span>{gas.gasLabel||'Gas not labelled'}{gas.switchDepthM!=null?` · switch ${gas.switchDepthM} m`:''}</span></div><strong>{gas.startPressureBar??'—'} bar</strong></article>):<p>No current Plan exposes canonical cylinder assignments yet. The workspace will surface them when Plan data contains them; it does not invent gas from cylinder history.</p>}</Card>
   <Card><header><h2>Gas &amp; deco planning</h2><button className="focus-link" onClick={()=>go?.('Dive Plans')}>Open planner</button></header>{latestPlan?<div className={styles.metrics}><span><small>Plan</small><b>{latestPlan.name}</b></span><span><small>Max depth</small><b>{latestPlan.maxDepthM??'—'} m</b></span><span><small>Bottom time</small><b>{latestPlan.bottomTimeMin??'—'} min</b></span><span><small>Planned runtime</small><b>{latestPlan.plannedRuntimeMin??'—'} min</b></span><span><small>Deco schedule</small><b>{latestPlan.decoSchedule?.length??0} stops</b></span></div>:<p>No technical Plan data available. ZeusTek stores user-entered/imported plan evidence only; this workspace does not run an unvalidated decompression engine.</p>}</Card>
   <Card><header><h2>Common skills</h2><button className="focus-link" onClick={()=>go?.('Skills & Currency')}>All skills</button></header>{skills.filter(skill=>!skill.archived&&(group?skillRecordGroup(skill)===group:isTechnicalSkill(skill))).slice(0,8).map((skill)=>{const row=currency.find((candidate)=>candidate.skill.entityId===skill.entityId);return <article className={styles.row} key={skill.entityId}><div><b>{skillRecordName(skill)}</b><span>{row?.projection.reason??'No currency projection'}</span></div><em data-state={row?.projection.status??'not-assessed'}>{row?.projection.status.replace('-',' ')??'not assessed'}</em></article>})}</Card>
   <Card><header><h2>Recent technical practice</h2><span>{metrics.technicalDives} technical · {metrics.decoDives} deco</span></header>{practice.length?practice.map((dive)=><a className={styles.practice} key={dive.entityId} href={`/?section=Logbook&diveId=${encodeURIComponent(dive.entityId)}`}><div><b>{dive.site||'Technical Dive'}</b><span>{dive.date} · {dive.maxDepthM??'—'} m · {dive.bottomTimeMin??'—'} min</span><span>{[dive.gradientFactorLow!=null&&dive.gradientFactorHigh!=null?`Recorded GF ${dive.gradientFactorLow}/${dive.gradientFactorHigh}`:null,dive.cnsPercent!=null?`CNS ${dive.cnsPercent}%`:null,dive.otu!=null?`OTU ${dive.otu}`:null,dive.decoStops?.length?`${dive.decoStops.length} recorded stops`:null].filter(Boolean).join(' · ')}</span></div><Gauge/></a>):<p>No Dives are currently marked technical/decompression.</p>}</Card>
  </div>
  <footer className={styles.actions}><button className="focus-secondary" onClick={()=>setEditingReference(null)}><ClipboardCheck size={16}/>Capture requirement snapshot</button><button className="focus-secondary" onClick={()=>go?.('Logbook')}>Record drill evidence on a Dive</button><button className="focus-primary" onClick={()=>go?.('Dive Plans')}>Start tec plan</button></footer>
  {editingReference!==undefined&&<RequirementSetEditor existing={editingReference} close={()=>setEditingReference(undefined)} saved={refresh}/>}
 </>;
}

function PathwayCard({row,onEdit}:{row:ReturnType<typeof evaluatePathwayReadiness>;onEdit:()=>void}){
 return <Card className={styles.pathwayCard}><div className={styles.pathwayHead}><div><span className="focus-eyebrow">{row.set.agency} · {row.set.versionLabel}</span><h3>{row.set.pathwayLabel||row.set.pathwayKey}</h3></div><em data-state={row.state}>{row.total ? stateLabel[row.state] : 'Unknown / unconfigured'}</em></div>
 <progress max="100" value={row.percent} aria-label={`${row.percent}% captured requirements satisfied`}/><p>{row.satisfied}/{row.total} captured requirements satisfied · source: {row.set.sourceCitation||'not recorded'} · captured {row.set.capturedAt.slice(0,10)}</p>
 <details><summary>All requirements and canonical evidence</summary><ul>{row.requirements.map(item=><li key={item.requirement.key}><span><b>{item.requirement.label} · {stateLabel[item.state]}</b><small>{item.detail}</small>{item.evidence.map((evidence,index)=>evidence.id?<a key={index} className="focus-link" href={`/?${new URLSearchParams({section:evidence.kind==='dive'?'Logbook':evidence.kind==='certification'?'Training':'Skills & Currency',[evidence.kind==='dive'?'diveId':evidence.kind==='certification'?'certificationId':'evidenceId']:evidence.id})}`}>{evidence.label}</a>:<small key={index}>{evidence.label}</small>)}</span></li>)}</ul></details>
 {row.set.sourceUrl&&<a className="focus-link" href={row.set.sourceUrl} target="_blank" rel="noopener noreferrer">Open captured source</a>}<button className="focus-secondary" onClick={onEdit}>Capture new version from this snapshot</button><small>Historical snapshots are never overwritten. Readiness does not authorise diving.</small></Card>;
}

function RequirementSetEditor({existing,close,saved}:{existing:Stored<ReferenceRequirementSetRecord>|null;close:()=>void;saved:()=>Promise<void>|void}){
 const [sourceUrl,setSourceUrl] = useState(existing?.sourceUrl ?? '');const [notes,setNotes] = useState(existing?.notes ?? '');
 const base=existing??emptyRequirementSet('tec40','Tec 40');const [agency,setAgency]=useState(base.agency);const [pathwayKey,setPathwayKey]=useState(base.pathwayKey);const [pathwayLabel,setPathwayLabel]=useState(base.pathwayLabel??'');const [versionLabel,setVersionLabel]=useState(existing ? `${base.versionLabel}-new` : base.versionLabel);const [effectiveFrom,setEffectiveFrom]=useState(base.effectiveFrom??'');const [sourceCitation,setSourceCitation]=useState(base.sourceCitation??'');const [requirementsText,setRequirementsText]=useState(JSON.stringify(base.requirements,null,2));const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(event:React.SyntheticEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{const parsed=JSON.parse(requirementsText) as TechnicalRequirementDefinition[];if(!Array.isArray(parsed))throw new Error('Requirements JSON must be an array.');await saveReferenceRequirementSet({agency,pathwayKey,pathwayLabel,versionLabel,effectiveFrom:effectiveFrom||null,effectiveTo:base.effectiveTo??null,sourceCitation:sourceCitation||null,sourceUrl:sourceUrl||null,notes,requirements:parsed,capturedAt:new Date().toISOString()});await saved();close();}catch(reason){setError(reason instanceof Error?reason.message:'Reference snapshot could not be saved.');}finally{setBusy(false);}}
 return <div className="focus-modal-bg"><AccessibleDialog editable containDismiss label="Technical pathway reference snapshot" className={`focus-modal ${styles.referenceEditor}`} close={()=>{if(!busy)close();}}><form onSubmit={(event)=>void submit(event)}>
 <header><div><span className="focus-eyebrow">VERSIONED REFERENCE DATA</span><h2>{existing?'Capture new pathway version':'Capture pathway snapshot'}</h2><p>Use a source you actually checked. Historical snapshots are immutable; no current agency numbers are bundled.</p></div><button type="button" className="focus-icon" data-dialog-close disabled={busy} aria-label="Close reference editor" onClick={close}><X/></button></header>
 <fieldset disabled={busy} className={styles.referenceFields}>
 <label>Agency<input required value={agency} onChange={event=>setAgency(event.target.value)}/></label><label>Pathway key<input required value={pathwayKey} onChange={event=>setPathwayKey(event.target.value)}/></label>
 <label>Display label<input value={pathwayLabel} onChange={event=>setPathwayLabel(event.target.value)}/></label><label>Version label<input required value={versionLabel} onChange={event=>setVersionLabel(event.target.value)}/></label>
 <label>Effective from<input type="date" value={effectiveFrom} onChange={event=>setEffectiveFrom(event.target.value)}/></label><label>Source citation<input required value={sourceCitation} onChange={event=>setSourceCitation(event.target.value)}/></label>
 <label>Source URL (HTTP / HTTPS)<input type="url" value={sourceUrl} onChange={event=>setSourceUrl(event.target.value)}/></label><label>Reference notes<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label>
 <label className={styles.span2}>Requirements JSON<textarea rows={12} value={requirementsText} onChange={event=>setRequirementsText(event.target.value)} spellCheck={false}/><small>Supported kinds: certification, count, recency, assessment, document, manual. Empty/incomplete rules remain Unknown / Manual review.</small></label></fieldset>
 {error&&<p role="alert">{error}</p>}<footer><button type="button" className="focus-secondary" data-dialog-close disabled={busy} onClick={close}>Cancel</button><button className="focus-primary" disabled={busy}>{busy?'Saving…':'Save captured snapshot'}</button></footer></form></AccessibleDialog></div>;
}
