// Read-only release history. package.json remains the current-version authority.
export const appChangelog = [
  {
    version: '1.0.28',
    date: '2026-09-15',
    title: 'Synthetic data cleanup & record controls',
    changes: [
      'Expanded Site Configuration data tools to scan every canonical record kind and identify explicitly labelled acceptance fixtures in common and nested fields.',
      'Added dependency-aware recommendations for safe deletion, archival/suppression, relationship unlinking or manual review, with no automatic or preselected removal.',
      'Added searchable all-user-data controls with record details, owning-page links and conservative edit, delete, archive or unlink actions through the existing local-first history and sync path.',
      'Protected Dives, evidence, requirement versions and other historical records from destructive generic edits; record identities and canonical relationships remain unchanged.',
      'Added exact typed confirmation, optional safe-child inclusion, compact lists and accessible desktop, tablet and phone/PWA dialogs with no horizontal overflow.',
      'Preserved all T03–T10 features, existing record kinds, offline event/outbox behaviour, backups and canonical Dive records without a database migration or parallel store.',
    ],
  },
  {
    version: '1.0.27',
    date: '2026-09-15',
    title: 'Workflow, navigation & page density',
    changes: [
      'Grouped navigation into Overview, Gear, Dive Data, Planning, Diving CPD and Admin while preserving legacy section deep links through compatibility aliases.',
      'Clarified display labels for Certifications, Planned Training, Dive Skills, Dive Bibliography, Site Configuration and the Dive Planning Centre without migrating canonical record kinds or IDs.',
      'Added reusable accessible minimise/restore, show more/show less and open-detail controls, with warnings and status retained while content is minimised.',
      'Shortened Site Configuration into directly linked compact sections and added an owner-confirmed review for clearly labelled synthetic acceptance fixtures using the normal history and sync deletion path.',
      'Added workflow links across Trips, Dive Planning Centre, Logbook, Sites, People, loadouts, gas, skills and media, plus honest placeholders for future Dive Knowledge and Dive Computer Imports work.',
      'Preserved T09 Insights, T10 Plan-to-Dive provenance, offline local-first writes, responsive PWA navigation and all existing Dive records.',
    ],
  },
  {
    version: '1.0.26',
    date: '2026-09-15',
    title: 'Dive Planning Centre',
    changes: [
      'Rebuilt Dive Plans as a responsive Planning Centre while preserving every existing Plan ID, deep link, offline event and immutable Plan-to-Dive revision.',
      'Added Site and recorded-condition snapshots, team roles, human-factor risks and mitigations, emergency arrangements, readiness checks, checklists, notes and canonical Skill references.',
      'Reusable loadouts are applied as stable Equipment IDs and slot snapshots; later Equipment edits do not rewrite the Plan, and technical gas controls reuse canonical cylinders, fills and analyses.',
      'Technical planning remains progressive and advisory: ordinary recreational Plans do not require technical fields, while technical readiness requires recorded depth/runtime and current canonical gas evidence.',
      'Plans can link to an existing Trip or expedition by stable ID, with the Trip back-reference updated without copying or replacing either record.',
      'Save draft, Mark ready and Start dive retain the established local-first store, with Start dive carrying the exact immutable originating Plan revision into the existing Dive editor.',
    ],
  },
  {
    version: '1.0.25',
    date: '2026-09-15',
    title: 'Experience & Analytics',
    changes: [
      'Added a responsive Insights dashboard with seven interactive KPIs plus depth, environment, SAC/RMV, Equipment Set, Site, qualifying-Dive and readiness analysis.',
      'Analysis Scope filters dates, Pool and Training activity, dive mode, water type, Site and Equipment Set as derived presentation state without changing canonical Dive records.',
      'Every headline metric explains its denominator, exclusions, unknown values, calculation basis and source record IDs; missing depth or gas evidence is never converted to zero.',
      'Kept water type separate from dive environment/activity and reports L/min only where qualifying surface-volume/RMV evidence exists, never by relabelling pressure SAC.',
      'Readiness reuses captured Skill currency, Technical and Professional requirement evidence; unconfigured requirements remain Not configured or Unknown rather than fabricated failures.',
      'Export Insights creates a derived, timestamped report with scope, metrics, denominators, readiness and provenance while preserving the existing local-first Dive, Site, Equipment and evidence stores.',
    ],
  },
  {
    version: '1.0.24',
    date: '2026-09-15',
    title: 'Professional Development — phone-safe pathways',
    changes: [
      'Restored the preserved Professional Development workspace alongside the verified Equipment servicing and history corrections.',
      'Pathway and requirement-snapshot selectors stay inside their phone/PWA containers, including the pathway editor, without dropping or shortening saved labels.',
      'Professional pathways and repeatable experience link canonical Dives, Skills, People, Sites and private files; readiness remains advisory and Unknown is not inferred.',
      'Captured standards versions remain immutable; later evaluations create new links without rewriting historical evidence or original Dive records.',
      'Retained generic local-first events, sync, backups and completed T03–T07 functionality without a database migration or duplicate store.',
    ],
  },
  {
    version: '1.0.23',
    date: '2026-09-14',
    title: 'Equipment — servicing and owner history',
    changes: [
      'Overview servicing includes only service-required, non-retired Equipment with a recorded or computable service due date, ordered by servicing urgency.',
      'Equipment editing groups identity, servicing, status and notes, with attached keyboard- and touch-friendly checkbox labels.',
      'Equipment history retains dated issues, faults, damage, inspections, maintenance, services, repairs and notes; Monitoring and resolution update the same canonical event.',
      'Only an explicit Service action updates the scheduled-service baseline, including existing time- and Dive-use intervals; the history retains an applied-baseline marker.',
      'History uses existing local-first event/outbox saves, generic sync, backups and shared-gear permissions without replacing Equipment IDs, loadouts or historical Dive usage.',
      'Professional Development remains the preserved, blocked 1.0.22 work; this corrective release extends the verified 1.0.21 production source only.',
    ],
  },
  {
    version: '1.0.22',
    date: '2026-09-14',
    title: 'Professional Development — rolled-back candidate',
    changes: [
      'Production phone smoke found a pathway-selector overflow; this candidate was restored to the preceding verified app1.0.21/Sites88 release.',
      'Professional Development implementation and test evidence remain preserved on their original source branch; no recovery is included in the Equipment corrective pass.',
    ],
  },
  {
    version: '1.0.21',
    date: '2026-09-14',
    title: 'Trips — compact sections & selected files',
    changes: [
      'Trips show the first four linked Dive Sites, with a keyboard- and touch-friendly … more / … less disclosure for the rest.',
      'All existing canonical Site references and deep links remain intact; this is a display-only change.',
      'Trip photos marked Photo / video have clickable thumbnails and image browsing, while document categories remain compact.',
      'Shared media galleries support stable-ID multi-selection, shared caption/category editing and confirmed per-file deletion with retained filename-specific failures.',
      'Trip sections collapse without losing drafts. Long notes initially show five lines with Show more / Show less, and the old Trip upload banner is removed.',
      'Retained the Technical Workspace, private Trip/itinerary resources and additive multi-file uploads introduced in 1.0.20.',
    ],
  },
  {
    version: '1.0.20',
    date: '2026-09-14',
    title: 'Technical Workspace & Trip resources',
    changes: [
      'Added a Technical Workspace using canonical Skills, recorded configuration and gas evidence, and immutable captured pathway/reference versions; readiness is advisory, never diving authorisation.',
      'Technical planning extends the existing Dive Plan editor with recorded cylinder references, runtime and manual stop notes, without a decompression engine or replacement Plan model.',
      'Trips and individual itinerary events now retain separate private documents, media and safe links, with compact explicit document opening and stable original attachment IDs.',
      'Existing collection uploaders support additive selections, staged removal, independent per-file results and retry without losing successful uploads; Wishlist cover selection remains supported.',
      'Preserved canonical Dive, Site, Person, Equipment, Plan and Trip identities, offline event/outbox saves, backups and historical evidence.',
    ],
  },
  {
    version: '1.0.19',
    date: '2026-09-14',
    title: 'Skills & Currency — shared catalogue groups',
    changes: [
      'Skills & Currency now uses the same live Skill Catalogue groups as Settings, including custom, archived-only and future groups rather than a fixed shortlist.',
      'Retained canonical evidence, editable currency policies, offline persistence and all existing personal Dive history.',
      'Corrected the group-filter acceptance failure from the rolled-back 1.0.18 candidate without changing Skill identities or stored evidence.',
    ],
  },
  {
    version: '1.0.18',
    date: '2026-09-14',
    title: 'Skills & Currency — rolled-back candidate',
    changes: [
      'Added a responsive Skills & Currency development centre using the existing canonical Skill Catalogue and Dive evidence.',
      'Current, Due soon, Needs practice and Not assessed are derived from recorded practice and editable currency policies, never certification expiry or authorisation.',
      'Evidence history retains competence, confidence, evaluator, environment and original Dive, equipment and attachment references.',
      'Currency policies save offline through existing events, sync and backups; unknown references require review rather than name-based remapping.',
      'Preserved catalogue editing, CSV tools, protected cleanup, Plans, Sites, Trips, Loadouts and historical Logbook records.',
    ],
  },
  {
    version: '1.0.17',
    date: '2026-09-14',
    title: 'Reusable Loadouts & Gas',
    changes: [
      'Extended existing Equipment Sets with semantic slots, clone, validation and per-Dive or Plan application overrides.',
      'Applied equipment references and slot snapshots remain historical; creating a Dive from a Plan retains its loadout references and immutable Plan provenance.',
      'Physical cylinders remain Equipment; fill and analysis histories save offline through existing events, sync and backups.',
      'A newer fill visibly makes an older analysis stale until an analysis explicitly links to the new fill; partial gas readings are never displayed as a fully known mix.',
      'Added phone-safe cylinder profiles, fill/analysis forms and common private evidence attachments while preserving existing Sites, Trips and Logbook behaviour.',
    ],
  },
  {
    version: '1.0.16',
    date: '2026-09-13',
    title: 'Trip owner corrections',
    changes: [
      'Made Team, Site, Dive Plan and reusable-loadout choices readable at phone, tablet and desktop widths without character-by-character wrapping.',
      'Added Me (this account) as an organiser using the signed-in account reference, while keeping saved-Person organisers and avoiding duplicate People records.',
      'Added Trip-local non-diving participants with roles and notes; blank rows are discarded and guests remain separate from canonical Dive People.',
      'Added Meal, Activity / excursion, Training, Meeting and Rest / free time itinerary events while preserving every existing event type.',
    ],
  },
  {
    version: '1.0.15',
    date: '2026-09-13',
    title: 'Trips & Expeditions',
    changes: [
      'Added trips with itinerary, bookings, accommodation, team, packing, gas logistics and private documents.',
      'Link existing Dive Plans, Sites, People and reusable Equipment Sets without copying or changing their records.',
      'Trip details save offline through existing events, sync and backups; readiness is advisory and similar trips are never automatically merged.',
      'Added responsive, searchable reference choices and protected editors while preserving Wreck & Overhead dialog behaviour.',
    ],
  },
  {
    version: '1.0.14',
    date: '2026-09-13',
    title: 'Wreck & Overhead profiles with contained editor Escape',
    changes: [
      'Released optional canonical Site wreck/overhead profiles, dated observations, original media references and read-only Planner summaries.',
      'Escape closes only the topmost wreck editor, restores its launcher and leaves the Site card open; unsaved edits retain the existing confirmation protection.',
      'Exterior facts remain separate from disclosed trained-overhead notes; no readiness, competence or authorisation is inferred.',
    ],
  },
  {
    version: '1.0.13',
    date: '2026-09-13',
    title: 'Wreck & Overhead Site profiles — rolled-back candidate',
    changes: [
      'Added an optional wreck/overhead profile to the existing canonical Site with recorded depths, access, structured hazards, egress and route notes.',
      'Kept exterior/open-water facts separate from disclosed trained-overhead notes; recorded information never implies competence, readiness or authorisation.',
      'Added dated observations and original Dive/media references through existing offline-first events, sync and backup without duplicating Sites or historical records.',
      'Planner Site selection and detail show a read-only summary/link; route sketches use a focus-managed full-size viewer with phone-safe controls.',
    ],
  },
  {
    version: '1.0.12',
    date: '2026-09-13',
    title: 'Human-readable Skill CSV matching',
    changes: [
      'CSV import previews now show the matched canonical Skill name and group without exposing its internal ID during ordinary review.',
      'Exact Skill ID matching, updates, archive/restore actions, unresolved-ID diagnostics and exported skill_id values remain unchanged.',
    ],
  },
  {
    version: '1.0.11',
    date: '2026-09-13',
    title: 'Protected editors and visible competence guidance',
    changes: [
      'Editable overlays no longer dismiss from backdrop clicks or Escape; explicit Cancel and Close actions now protect changed form values with a discard confirmation.',
      'Skill Evidence keeps the compact competence selector while displaying the selected canonical Skill definition immediately beneath it and through accessible mouse, keyboard and touch help.',
      'Stable competence levels, legacy assessments, canonical Skill IDs and CSV behaviour remain unchanged.',
    ],
  },
  {
    version: '1.0.10',
    date: '2026-09-13',
    title: 'Skill evidence and catalogue UI correction',
    changes: [
      'Skill Evidence now records a stable Foundation, Developing, Competent, Advanced or Mastered level and shows the selected canonical Skill’s own definition while logging or editing.',
      'Legacy numeric competence and free-text assessment values remain intact and readable; changing a Skill definition does not rewrite saved evidence levels.',
      'Made logged Skill Evidence cards compact with accessible Edit, Unlink and Delete icon controls while retaining the existing delete confirmation and full evidence disclosure.',
      'Separated the Skill Catalogue heading from its naturally wrapping action toolbar and preserved responsive search, filtering and CSV actions.',
      'Made Skill Group filtering an explicit searchable multi-select with zero groups selected by default and 75-Skill incremental result batches for large catalogues.',
    ],
  },
  {
    version: '1.0.9',
    date: '2026-09-13',
    title: 'Rich Skill definitions and CSV management',
    changes: [
      'Extended each canonical Skill with a group, description and Skill-specific Foundation, Developing, Competent, Advanced and Mastered definitions without changing existing IDs or evidence references.',
      'Added local CSV preview, selective create/update/archive/restore, exact-ID matching, conservative duplicate checks and a re-importable canonical export.',
      'Added protected cleanup for unused archived Skills; any referenced historical Skill remains readable and cannot be removed by this maintenance action.',
      'Updated Dive → Add skill to search by group, name or description and display Group — Skill name while excluding archived Skills from new evidence choices.',
    ],
  },
  {
    version: '1.0.8',
    date: '2026-09-13',
    title: 'Canonical Skill Catalogue',
    changes: [
      'Resolved Skill Evidence references to human-readable canonical Skill names while preserving every Skill and evidence ID.',
      'Added Settings → Diving Data → Skill Catalogue with search, single add/edit, safe archive/restore and evidence usage counts.',
      'Added reviewed bulk entry with one Skill per line, blank-line handling and case/whitespace duplicate prevention through the same offline-first canonical Skill service.',
      'Made Dive → Add skill searchable and kept catalogue-created and Dive-created Skills immediately available through the same canonical records.',
    ],
  },
  {
    version: '1.0.7',
    date: '2026-09-13',
    title: 'Shared surface palette alignment',
    changes: [
      'Continued SNAG-UI-001 by moving shared navigation, hero, metric-chip, weather, form, technical and notice surfaces from brown/bronze fills to charcoal neutrals.',
      'Kept ZeusTek orange as the primary action/active accent and cyan for weather or other informational data.',
      'The broader page-specific design-system review remains partial and is not marked closed.',
    ],
  },
  {
    version: '1.0.6',
    date: '2026-09-13',
    title: 'Dive skills evidence workflow',
    changes: [
      'Added a visible Add skill flow to Dive Debrief using the shared canonical Skill and dive.skill_evidence records.',
      'Evidence can be created, reopened offline, edited, linked, unlinked without deleting its Skill, or explicitly deleted as a separate action.',
      'The Dive reference and evidence diveId are updated through one domain service, with duplicate Skill definitions prevented by canonical identity.',
    ],
  },
  {
    version: '1.0.5',
    date: '2026-09-13',
    title: 'Conservation reference correction',
    changes: [
      'Fixed existing Dive links so the exact selected canonical record—including legacy IDs and the latest Dive—passes strict existence and entity-type validation.',
      'Replaced duplicate Dive and Site inputs with one oldest-first Dive selector and one offline existing-Site search control.',
      'Added accessible example help and a wider, phone-safe scrolling layout to both Log and Edit conservation activity forms.',
    ],
  },
  {
    version: '1.0.4',
    date: '2026-09-12',
    title: 'Neutral dark workspace',
    changes: [
      'Replaced the warm brown page-level glow with a black and charcoal background that matches the navigation surfaces.',
      'Kept orange as an intentional accent on controls, status details and highlighted content.',
    ],
  },
  {
    version: '1.0.3',
    date: '2026-09-12',
    title: 'Conservation & AWARE',
    changes: [
      'Record conservation observations, debris surveys/removals and learning evidence using existing Dive, Site and Person references.',
      'Calculated totals distinguish surveyed debris from actual removals and retain unknown measurements.',
      'Capture sourced programme requirement versions without claiming certification or remote submission.',
      'Link private uploaded photos, videos and evidence files; local activity edits and saved references remain available without a connection.',
    ],
  },
  {
    version: '1.0.2',
    date: '2026-09-12',
    title: 'One Dive: Overview, Debrief and Story',
    changes: [
      'Added three labelled views to the existing Dive detail, with shared facts and locally saved reflections.',
      'Debrief links shared skill evidence; Story features existing media without copying or deleting originals.',
      'Plan-derived logs retain an immutable originating Plan revision for comparison with actual Dive facts.',
      'Saved media references remain available offline, and failed local saves prevent accidental navigation loss.',
    ],
  },
  {
    version: '1.0.1',
    date: '2026-09-12',
    title: 'Version and changelog baseline',
    changes: [
      'Added the current app version to the navigation footer with a link to this changelog.',
      'Recorded the existing pages and release rollback point before expansion work.',
      'Existing dive records, sharing, sync, backups and features are unchanged.',
    ],
  },
] as const;
