// Read-only release history. package.json remains the current-version authority.
export const appChangelog = [
  {
    version: '1.0.57',
    date: '2026-09-24',
    title: 'Highest award summaries use canonical evidence',
    changes: [
      'Overview and Insights now show the highest ranked recreational display award from current Certification records, including recognised Master Scuba Diver ratings stored as Other or Experience.',
      'The older owner-entered Person summary remains unchanged; display rank does not grant depth permissions or professional capability.',
    ],
  },
  {
    version: '1.0.56',
    date: '2026-09-24',
    title: 'Owner qualification display corrected',
    changes: [
      'The Dive Team shows the owner once as Me and selects the highest evidenced qualification even when an award is stored in a broad course category.',
      'People, Dive Entity relationships, profile-photo cropping and all 31 owner-supplied navigation artworks remain included.',
    ],
  },
  {
    version: '1.0.55',
    date: '2026-09-24',
    title: 'People, Dive Entities and navigation candidate (rolled back)',
    changes: [
      'Separated human People from non-human Dive Entities while preserving canonical records and historical links; added explicit many-to-many relationships and circular profile-photo cropping.',
      'Displayed the owner once as Me in Dive Teams, using the canonical Person and certification evidence without rewriting old Dive records.',
      'Added all 31 supplied ZeusTek navigation artworks as optimized transparent icons while retaining unchanged masters outside the PWA asset directory.',
    ],
  },
  {
    version: '1.0.54',
    date: '2026-09-24',
    title: 'T14 scoped release through Stage 8; Gmail sync deferred',
    changes: [
      'Released the completed Stage 0–8 work, including Weather & Conditions, Dive Centres, Insights, planning, CPD, Admin diagnostics and privacy-aware exports.',
      'Temporarily disabled live Gmail mailbox sync by owner-approved exception after one failed upstream-provider acceptance run. Cached newsletter stories and public News feeds remain available; the connection is retained.',
      'Excluded encrypted connection records from cloud and local backups. Protected diving calculations and canonical owner records remain unchanged.',
    ],
  },
  {
    version: '1.0.53',
    date: '2026-09-23',
    title: 'T14 scoped release candidate (rolled back)',
    changes: [
      'Added the Dive Centres workspace, analysis workbench, in-route planning editors and plan-first gas allocation while preserving the protected calculation engines.',
      'Added weather and marine conditions with explicit retrieval and truthful provider access status, plus guided professional development and manual Dive News mailbox sync.',
      'Reorganised Site Configuration, added redacted application diagnostics, repaired Diver Summary downloads and excluded connection secrets from backups.',
    ],
  },
  {
    version: '1.0.52',
    date: '2026-09-23',
    title: 'Equipment media centring correction',
    changes: [
      'Centred the accessible full-resolution Equipment photo viewer on desktop while retaining contained, phone-safe image sizing and the existing media records.',
      'Kept the T14A icon, awards, dialog, Overview, Wishlist, Cylinders and brand-focus changes unchanged, with no Gas Planner calculation or canonical data changes.',
    ],
  },
  {
    version: '1.0.51',
    date: '2026-09-23',
    title: 'Brand icon foundation and must-fix display corrections',
    changes: [
      'Added a manifest-backed ZeusTek domain icon registry for 131 supplied brand assets, with accessible labels and a safe vector fallback while retaining vector icons for core controls.',
      'Corrected Insights awards so Site Configuration selections are the inclusion list, the 4/8/12/16/20 setting is only a layout cap, empty selections stay empty and incomplete rows remain centred.',
      'Strengthened shared editor dismissal so Cancel and Escape use a viewport-centred discard confirmation, Escape returns to editing, and focus is restored without leaving the app blurred.',
      'Compacted Overview, centred Equipment media, removed the inactive Wishlist price-search controls, and added a compact configurable Cylinders & Gas table layout.',
      'Replaced the remaining non-brand focus treatment with the shared cyan focus ring without changing records, cylinder identity, or Gas Planner calculations.',
    ],
  },
  {
    version: '1.0.50',
    date: '2026-09-22',
    title: 'Whole-site design ethos and accessibility convergence',
    changes: [
      'Introduced shared ZeusTek surface, colour, focus, status, warning, form, table and dialog patterns so established and newer pages read as one coherent product family.',
      'Aligned Overview, Insights, Gear, People, Admin, Dive Planning, Gas Planning and Technical Diving presentation without redesigning routes or replacing page-specific workflows.',
      'Kept warnings and status visible in minimised cards, strengthened accessible dialog semantics and standardised 44 px Site Configuration form and action targets.',
      'Verified desktop, 1024 px, 820 px and 390 px layouts without page-level horizontal overflow and retained compact mobile navigation.',
      'Left all canonical records, schemas and Gas Planner NDL, MOD, PPO₂, gas-time and reserve calculations unchanged.',
    ],
  },
  {
    version: '1.0.49',
    date: '2026-09-22',
    title: 'Stable numeric cylinder identifiers',
    changes: [
      'Standardised cylinder IDs as permanent two-digit numeric labels such as 01, 02 and 03, separate from the editable manufacturer serial number.',
      'Assigned and persisted missing legacy cylinder IDs without changing canonical record identities, and prevented later edits or retirement from regenerating or reusing an ID.',
      'Updated the Cylinders & Gas table, editor and detail views to use the ID # label with no Cylinder, Tank or other text prefix.',
      'Updated owned-cylinder Gas Planning selectors and provenance summaries to begin with the stable numeric ID while retaining volume, mix, pressure, analysis and inspection evidence.',
    ],
  },
  {
    version: '1.0.48',
    date: '2026-09-22',
    title: 'Recreational no-stop gas planning workbench',
    changes: [
      'Completed the recreational no-stop planner with selectable ZH-L16B or ZH-L16C, preserved Gradient Factors, controlling-compartment evidence and explicit unavailable reasons without generating decompression schedules.',
      'Separated NDL, gas-limited time, owner maximum duration and planned working time in one readiness summary with MOD, PPO₂, EAD, reserve and limiting-factor evidence.',
      'Connected canonical owned-cylinder and rental-snapshot volume, pressure, fill, analysis, valve and inspection provenance to the saved Gas Plan without changing cylinder or Dive records.',
      'Added best and conservative mix comparisons while allowing lower-oxygen actual gas, plus explicit analysis, MOD/PPO₂, gas sufficiency and recreational-scope warnings.',
      'Added calculated emergency reserve phases, rule-of-thirds comparison and route/checkpoint gas and pressure evidence for return, shore, wreck and multilevel recreational plans.',
    ],
  },
  {
    version: '1.0.47',
    date: '2026-09-21',
    title: 'Rental and temporary cylinder planning',
    changes: [
      'Added an explicit rental or temporary cylinder source for holiday, boat, resort and liveaboard Gas Plans without requiring an owned-cylinder record.',
      'Stored rental label, material, volume, pressure, valve, gas, analysis, operator and notes evidence inside the Gas Plan snapshot for reliable save and reopen.',
      'Connected rental evidence to total and usable gas, reserve, gas-limited time, MOD, PPO₂, NDL and route-checkpoint calculations while keeping decompression scheduling out of scope.',
      'Added missing-evidence, analysis, MOD/PPO₂ and gas-sufficiency warnings plus the rental service-history advisory without applying owned-cylinder inspection requirements.',
      'Kept owned-cylinder selection and provenance unchanged; creating an owned cylinder from a rental snapshot now requires an explicit confirmation action.',
    ],
  },
  {
    version: '1.0.46',
    date: '2026-09-21',
    title: 'Cylinder to Gas Planning evidence integration',
    changes: [
      'Loaded the canonical Cylinders & Gas inventory directly into Gas Planning, including newly created cylinders, stable IDs, serials, water volumes, valves and inspection evidence.',
      'Separated current pressure, selected fill, plan snapshot and owner override sources without changing the canonical cylinder state.',
      'Kept root-fill gas analysis current across usage-only pressure events while staling it for composition-changing fills or explicit owner review.',
      'Added readable fill, analysis and pressure-event provenance plus context-sensitive hydro, visual, valve and oxygen-clean readiness warnings.',
      'Preserved existing cylinder, Gas Plan and Dive identities, local-first history and all Plan-to-Dive provenance without a new store or migration.',
    ],
  },
  {
    version: '1.0.45',
    date: '2026-09-19',
    title: 'Cylinder identity and inspection cycle correction',
    changes: [
      'Separated the automatic two-digit cylinder inventory ID from the manufacturer serial number and reused the shared Equipment manufacturer catalogue.',
      'Restricted valve type to DIN or A-CLAMP and changed manufacture, inspection and O₂-clean dates to month/year entry.',
      'Replaced competing Hydro and Visual date fields with one latest-test type/date: Hydro includes Visual, Hydro is due after 60 months and Visual after 30 months.',
      'Added manual pressure-used and remaining-pressure entries while retaining the originating fill mix and gas-analysis provenance.',
      'Preserved existing cylinder, fill, analysis, People and Dive records through the same canonical local-first path.',
    ],
  },
  {
    version: '1.0.44',
    date: '2026-09-19',
    title: 'Legacy Person evidence compatibility',
    changes: [
      'Carried explicit legacy Person qualification evidence into new Dive Plan team snapshots, including a recorded Rescue Diver status, without inferring an unsupported depth limit.',
      'Retained the app1.0.43 People & Operators foundation, privacy defaults, dedicated cylinder inventory and all existing canonical records unchanged.',
    ],
  },
  {
    version: '1.0.43',
    date: '2026-09-19',
    title: 'People, operators and My Profile foundation',
    changes: [
      'Promoted People & Operators into the canonical profile source for My Profile, buddies, instructors, dive centres, charter operators, guides and emergency contacts without creating a second people store.',
      'Added additive identity, role, certification, depth, contact, instructor and operator fields plus an explicit, privacy-aware derived-stat refresh from canonical Logbook and Certification evidence.',
      'Connected Overview My Profile and Top Buddy cards to Person profiles while defaulting legacy contact visibility to private.',
      'Kept Dive Planning search-and-add controls and now snapshots recorded rescue, depth, qualification and specialty evidence when a Person is added to a team.',
      'Preserved all existing Person and Dive IDs, local-first event/outbox sync, Plan-to-Dive provenance, the dedicated cylinder inventory and all 66 Dive logs.',
    ],
  },
  {
    version: '1.0.42',
    date: '2026-09-19',
    title: 'Dedicated cylinder inventory',
    changes: [
      'Moved physical-cylinder creation and management out of Equipment and into the existing Cylinders & Gas table while keeping non-cylinder gear in Equipment.',
      'Added cylinder identity, stamped construction, PW/PT pressure, manufacture, hydro-stamp and visual-sticker evidence fields alongside existing fill, analysis, service and media history.',
      'Preserved legacy cylinder IDs, loadout references, fills and analyses; older Equipment-backed cylinders remain compatible while new cylinders use the additive local-first cylinder record kind.',
      'Added dependency-aware cylinder deletion that never removes canonical Dive records or linked fill and analysis evidence.',
    ],
  },
  {
    version: '1.0.41',
    date: '2026-09-19',
    title: 'Workflow, Insights and Gear refinement',
    changes: [
      'Separated Trip / Event Planning from Dive Preparation in navigation and kept Technical Diving with Diving CPD while preserving existing route aliases.',
      'Simplified Overview to Next Dive, My Profile, Top Dive Buddy, kit status and weather instead of duplicating the analytics award dashboard.',
      'Added Site Configuration choices for 4, 8, 12, 16 or 20 Insights awards, centred them in responsive eight- or four-wide rows, and expanded filters and source-data-point exclusions without changing canonical Dive records.',
      'Separated pressure SAC in bar/min from surface-volume RMV in L/min and added a distinct RMV trend; deferred qualifying-progress and readiness cards remain off Insights.',
      'Separated reusable Loadouts from a dedicated Cylinders & Gas table with keyboard-openable details, service intervals, fill/analysis history and common media handling.',
      'Preserved Equipment as the canonical individual-gear inventory and retained all local-first history, event, outbox and Plan-to-Dive provenance behaviour.',
    ],
  },
  {
    version: '1.0.40',
    date: '2026-09-18',
    title: 'T12.6R recreational gas planner and planning navigation',
    changes: [
      'Added explicit ZH-L16B and ZH-L16C nitrogen no-stop NDL with gradient factors, separate gas-limited time and salt/fresh water pressure calculations.',
      'Added gas candidate comparison, owner emergency reserve phases, rule of thirds and route checkpoint reserves with unavailable reasons.',
      'Saved an additive recreational snapshot on existing Gas Plans and left Dive records and technical decompression scheduling unchanged.',
      'Separated Trip / Event Planning from Dive Preparation, moved Technical Diving to Diving CPD, and retained old route aliases and compact phone navigation.',
      'Preserved the accepted Sites108 Plan editor, dated weather context, Gas Plan links, team and skill search controls.',
    ],
  },
  {
    version: '1.0.38',
    date: '2026-09-17',
    title: 'Dive Plan and Gas Planning acceptance completion',
    changes: [
      'Disambiguated duplicate Site names by canonical ID, retained Site location provenance, and hid map links when no usable location exists.',
      'Made Plan-side Gas Plan selection, creation, live quantities and accessible warning details available without copying gas evidence into Dive Plans.',
      'Named limiting divers and unknown team capability, with separate owner-entered user, team and Site depth-limit advisories.',
      'Added structured hyperbaric facility contact, access, source and last-checked fields while preserving older emergency notes.',
      'Kept multi-cylinder gas-needed totals unavailable until assignments support a trustworthy estimate; per-cylinder segment estimates and missing evidence remain explicit.',
      'Improved keyboard, touch and hover help for planning terms, and consumed one-time Gas Plan creation links after use.',
      'Corrected Plan-editor spacing and compact help controls; Site depth, water and entry facts now appear as labelled canonical references.',
      'Added search-first People and Dive Skills pickers, with roles and capabilities edited only after a team member is added.',
      'Added an on-demand dated Site forecast or regional-history check, with separate provider throttles, visible rate-limit status and non-blocking owner-entered manual or seasonal fallbacks; unknown marine conditions remain unknown.',
    ],
  },
  {
    version: '1.0.37',
    date: '2026-09-17',
    title: 'Dive Plan editor and gas-planning foundation',
    changes: [
      'Expanded the existing Dive Plan editor with dated dive objectives, Site and team checks, equipment readiness, emergency resources and an optional linked Gas Plan while preserving Plan-to-Dive history.',
      'Added evidence-led gas-mix, MOD, PPO₂, EAD and basic gas-volume estimates with current-fill analysis checks, explicit unknown states and no calculated decompression schedule.',
      'Flagged recorded same-day prior dives and pressure groups without inferring residual nitrogen, plus linked-Trip flights inside a 24-hour advisory window without presenting flight clearance.',
      'Added distinct owner-recorded PADI air, PADI EANx32, SSI Air/EANx and US Navy table references, and external Bühlmann ZH-L16C implementation/gradient-factor provenance; agency groups are never interchanged.',
      'Made Gas Planning warnings available through a hoverable, keyboard- and touch-accessible icon, including while the summary is minimised.',
      'Preserved canonical local-first records, IDs, event/outbox sync and existing Dive logs without a new record kind or database migration.',
    ],
  },
  {
    version: '1.0.36',
    date: '2026-09-16',
    title: 'Synthetic cleanup detection safety correction',
    changes: [
      'Limited fixture detection to explicit synthetic, acceptance, production or task-test contexts, so ordinary wreck fixtures and fittings are not treated as test data.',
      'Removed generic service and medical test wording from synthetic candidates; bare task markers remain review-only rather than bulk-delete eligible.',
      'Separated high-confidence cleanup from possible-synthetic owner review, while preserving recursive scanning, dependency checks and explicit action confirmation.',
      'Preserved owner Sites, all 66 Dive logs and the local-first history/outbox path; no owner record was changed by the release.',
    ],
  },
  {
    version: '1.0.35',
    date: '2026-09-16',
    title: 'Synthetic data cleanup safety and review',
    changes: [
      'Expanded synthetic/test-marker review to every nested string field across all canonical record kinds, with matched field/value and high-confidence versus possible/ordinary classification.',
      'Added review destinations for imported computer evidence, gas plans and Dive Knowledge advice/review records, with inbound/outbound dependency detail and owner-versus-synthetic reference indicators.',
      'Added owner-confirmed safe group deletion, protected-record archival, individual unlink-then-delete review, clear blocked reasons and a post-cleanup count report. No destructive action is selected by default.',
      'Excluded records explicitly marked suppressedFromUse from ordinary local-first lists and derived analytics/readiness while retaining them in history, backups and the owner review tool.',
      'Kept immutable Dive provenance and other historical evidence protected, and preserved the existing event/outbox/sync path without new record kinds or database migration.',
    ],
  },
  {
    version: '1.0.34',
    date: '2026-09-15',
    title: 'Diving calendar, bookings & gas planning',
    changes: [
      'Replaced the two remaining Planning roadmap placeholders with dedicated Diving Calendar & Bookings and Gas Planning workspaces across desktop, tablet and phone/PWA layouts.',
      'Added calendar, list and bookings views with event-type filters, upcoming-event details and additive create, edit, complete, cancel and archive actions through the existing local-first history/outbox path.',
      'Connected bookings to existing Trips, Dive Plans, Gas Planning and Planned Training without creating a second planning system or duplicating canonical records.',
      'Added lightweight gas planning linked to canonical Dive Plans, cylinders, fills and analyses, with real Logbook RMV provenance, manual overrides, basic gas-needed/available estimates and explicit incomplete-evidence warnings.',
      'Saved gas-plan records through the generic sync architecture and optional stable Plan references without overwriting Dive fields, changing existing Plan IDs or adding a database table.',
      'Preserved the compact ZeusTek workflow controls, old section aliases, transparent icon language and all existing T09–T12.2 behaviour.',
    ],
  },
  {
    version: '1.0.33',
    date: '2026-09-15',
    title: 'Transparent diving icon system',
    changes: [
      'Added the supplied 131 transparent ZeusTek diving icons as individually addressable PWA assets, with corrected semantic filename assignments where the original automatic crop names pointed to the wrong pictured icon.',
      'Added one typed, fail-safe icon registry and reusable responsive component; missing or unknown mappings fall back safely without affecting the surrounding text or interaction.',
      'Applied the icon language to high-value Overview, Logbook, Sites, Trips, Dive Planning Centre, Loadouts & Gas, Certifications, Planned Training, Dive Skills, Technical Diving, Professional Development, Conservation, Dive Knowledge, Insights and Dive Computer Imports surfaces.',
      'Kept icons decorative beside existing visible labels, retained keyboard and screen-reader names, and constrained artwork at phone, tablet and desktop sizes without horizontal overflow.',
      'Kept the ten large source sheets out of the runtime bundle; the application loads only the individual transparent PNG needed for each visible item.',
      'No Dive, Site, Equipment, certification, Plan, import, question, evidence or other canonical record was changed, migrated or duplicated.',
    ],
  },
  {
    version: '1.0.32',
    date: '2026-09-15',
    title: 'Dive computer import workflow correction',
    changes: [
      'Changed Dive Computer Imports to import every new valid profile before linking, so an import can finish with zero assigned Dive logs and never overwrites a canonical Dive during import.',
      'Added a complete Imported Profiles review area with search plus linked, unlinked, excluded, date, source-file and possible-Dive filters.',
      'Moved Dive linking after import, with same-date and nearest-time candidates first, explainable Site, duration and depth reasons, safe unlink/change actions and optional owner-approved field decisions.',
      'Strengthened repeated-import handling so identical profiles are not duplicated, prior links and decisions are retained, and reviewed source updates keep profile identity with versioned evidence.',
      'Added dependency-aware removal for imports and unlinked profiles with typed confirmation, linked-profile blocking and a guarantee that canonical Dive logs are never deleted.',
      'Preserved the existing computer-import, computer-profile and import-resolution kinds, generic local-first history/outbox/sync architecture and private evidence storage without a database migration.',
    ],
  },
  {
    version: '1.0.31',
    date: '2026-09-15',
    title: 'Dive computer data & profile import',
    changes: [
      'Added Dive Computer Imports as a standalone Dive Data workspace with local UDDF staging, explicit match decisions and a review-before-commit workflow.',
      'Added Oceanic+ UDDF parsing with strict XML safety, source fingerprinting, preserved raw timestamps and auditable timestamp normalisation without treating missing values as zero.',
      'Added explicit field-level import decisions, conservative duplicate handling, multi-segment linking and revision-aware rebasing that requires changed owner fields to be confirmed again.',
      'Stored source and profile evidence privately with SHA-256 integrity checks, offline backup/restore coverage and cleanup when an atomic import fails.',
      'Added accessible imported computer-profile summaries and expandable sample tables while preserving canonical Dive identities and existing manual field provenance.',
      'Reused the canonical local-first entity/event/outbox and generic sync architecture; no parallel Dive store, dedicated database table or destructive migration was introduced.',
    ],
  },
  {
    version: '1.0.30',
    date: '2026-09-15',
    title: 'Dive Knowledge review & study workflow',
    changes: [
      'Added Dive Knowledge as a standalone Diving CPD page for question banks, diagnostic tests, question-quality management and evidence-led study.',
      'Question suppression is reversible and affects future test selection only; immutable historical attempt snapshots, scores, wording and provenance remain reproducible.',
      'Added Needs review-first management with reasoned review states plus topic, subtopic and objective diagnostics that explain Strength, Weakness and Insufficient evidence denominators.',
      'Added incremental AI review export with previous-advice continuity and a checkpoint that advances only after the derived artifact is successfully created.',
      'Added portable study-pack ZIP import/export with manifest and SHA-256 verification, strict limits, full preflight validation and atomic no-partial-write commit behaviour.',
      'Reused the canonical local-first event/outbox/sync architecture and existing question/test stores; no parallel bank, attempt store, analytics table or data migration was introduced.',
    ],
  },
  {
    version: '1.0.29',
    date: '2026-09-15',
    title: 'Workflow and user-data controls refinement',
    changes: [
      'Replaced the large always-visible workflow strip with a compact, closed-by-default disclosure that still exposes the same journey links when requested.',
      'Standardised card density controls on clear + and − symbols with accessible Expand/Collapse names, visible focus and phone-friendly touch targets.',
      'Removed generic Open detail button clutter: supported card headings and complete user-data rows now act as the accessible primary detail control.',
      'Expanded fixture review evidence so every candidate states its matched field, dependency status, available safe action and the reason deletion is allowed or blocked.',
      'Kept Edit, Delete, Archive/suppress, Unlink and manual dependency review inside each record detail, with no default selection and exact destructive confirmation unchanged.',
      'Preserved immutable Dive/history/provenance records, all canonical IDs, local-first events/outbox, backups and completed T03–T10 functionality without a migration or parallel store.',
    ],
  },
  {
    version: '1.0.28',
    date: '2026-09-15',
    title: 'Synthetic data cleanup & record controls',
    changes: [
      'Expanded Site Configuration data tools to scan every canonical record kind and identify explicitly labelled acceptance fixtures in common and nested fields.',
      'Added dependency-aware recommendations for safe deletion, archival/suppression, relationship unlinking or manual review, with no automatic or preselected removal.',
      'Added searchable all-user-data controls with record details, owning-page links and conservative edit, delete, archive or unlink actions through the existing local-first history and sync path.',
      'Protected Dives, evidence, requirement versions and other historical records from destructive generic edits; record identities and canonical relationships remain unchanged.',
      'Added exact typed confirmation, optional safe-child inclusion, compact lists and accessible desktop, tablet and phone/PWA dialogs with no horizontal overflow.',
      'Preserved all T03–T10 features, existing record kinds, offline event/outbox behaviour, backups and canonical Dive records without a database migration or parallel store.',
    ],
  },
  {
    version: '1.0.27',
    date: '2026-09-15',
    title: 'Workflow, navigation & page density',
    changes: [
      'Grouped navigation into Overview, Gear, Dive Data, Planning, Diving CPD and Admin while preserving legacy section deep links through compatibility aliases.',
      'Clarified display labels for Certifications, Planned Training, Dive Skills, Dive Bibliography, Site Configuration and the Dive Planning Centre without migrating canonical record kinds or IDs.',
      'Added reusable accessible minimise/restore, show more/show less and open-detail controls, with warnings and status retained while content is minimised.',
      'Shortened Site Configuration into directly linked compact sections and added an owner-confirmed review for clearly labelled synthetic acceptance fixtures using the normal history and sync deletion path.',
      'Added workflow links across Trips, Dive Planning Centre, Logbook, Sites, People, loadouts, gas, skills and media, plus honest placeholders for future Dive Knowledge and Dive Computer Imports work.',
      'Preserved T09 Insights, T10 Plan-to-Dive provenance, offline local-first writes, responsive PWA navigation and all existing Dive records.',
    ],
  },
  {
    version: '1.0.26',
    date: '2026-09-15',
    title: 'Dive Planning Centre',
    changes: [
      'Rebuilt Dive Plans as a responsive Planning Centre while preserving every existing Plan ID, deep link, offline event and immutable Plan-to-Dive revision.',
      'Added Site and recorded-condition snapshots, team roles, human-factor risks and mitigations, emergency arrangements, readiness checks, checklists, notes and canonical Skill references.',
      'Reusable loadouts are applied as stable Equipment IDs and slot snapshots; later Equipment edits do not rewrite the Plan, and technical gas controls reuse canonical cylinders, fills and analyses.',
      'Technical planning remains progressive and advisory: ordinary recreational Plans do not require technical fields, while technical readiness requires recorded depth/runtime and current canonical gas evidence.',
      'Plans can link to an existing Trip or expedition by stable ID, with the Trip back-reference updated without copying or replacing either record.',
      'Save draft, Mark ready and Start dive retain the established local-first store, with Start dive carrying the exact immutable originating Plan revision into the existing Dive editor.',
    ],
  },
  {
    version: '1.0.25',
    date: '2026-09-15',
    title: 'Experience & Analytics',
    changes: [
      'Added a responsive Insights dashboard with seven interactive KPIs plus depth, environment, SAC/RMV, Equipment Set, Site, qualifying-Dive and readiness analysis.',
      'Analysis Scope filters dates, Pool and Training activity, dive mode, water type, Site and Equipment Set as derived presentation state without changing canonical Dive records.',
      'Every headline metric explains its denominator, exclusions, unknown values, calculation basis and source record IDs; missing depth or gas evidence is never converted to zero.',
      'Kept water type separate from dive environment/activity and reports L/min only where qualifying surface-volume/RMV evidence exists, never by relabelling pressure SAC.',
      'Readiness reuses captured Skill currency, Technical and Professional requirement evidence; unconfigured requirements remain Not configured or Unknown rather than fabricated failures.',
      'Export Insights creates a derived, timestamped report with scope, metrics, denominators, readiness and provenance while preserving the existing local-first Dive, Site, Equipment and evidence stores.',
    ],
  },
  {
    version: '1.0.24',
    date: '2026-09-15',
    title: 'Professional Development — phone-safe pathways',
    changes: [
      'Restored the preserved Professional Development workspace alongside the verified Equipment servicing and history corrections.',
      'Pathway and requirement-snapshot selectors stay inside their phone/PWA containers, including the pathway editor, without dropping or shortening saved labels.',
      'Professional pathways and repeatable experience link canonical Dives, Skills, People, Sites and private files; readiness remains advisory and Unknown is not inferred.',
      'Captured standards versions remain immutable; later evaluations create new links without rewriting historical evidence or original Dive records.',
      'Retained generic local-first events, sync, backups and completed T03–T07 functionality without a database migration or duplicate store.',
    ],
  },
  {
    version: '1.0.23',
    date: '2026-09-14',
    title: 'Equipment — servicing and owner history',
    changes: [
      'Overview servicing includes only service-required, non-retired Equipment with a recorded or computable service due date, ordered by servicing urgency.',
      'Equipment editing groups identity, servicing, status and notes, with attached keyboard- and touch-friendly checkbox labels.',
      'Equipment history retains dated issues, faults, damage, inspections, maintenance, services, repairs and notes; Monitoring and resolution update the same canonical event.',
      'Only an explicit Service action updates the scheduled-service baseline, including existing time- and Dive-use intervals; the history retains an applied-baseline marker.',
      'History uses existing local-first event/outbox saves, generic sync, backups and shared-gear permissions without replacing Equipment IDs, loadouts or historical Dive usage.',
      'Professional Development remains the preserved, blocked 1.0.22 work; this corrective release extends the verified 1.0.21 production source only.',
    ],
  },
  {
    version: '1.0.22',
    date: '2026-09-14',
    title: 'Professional Development — rolled-back candidate',
    changes: [
      'Production phone smoke found a pathway-selector overflow; this candidate was restored to the preceding verified app1.0.21/Sites88 release.',
      'Professional Development implementation and test evidence remain preserved on their original source branch; no recovery is included in the Equipment corrective pass.',
    ],
  },
  {
    version: '1.0.21',
    date: '2026-09-14',
    title: 'Trips — compact sections & selected files',
    changes: [
      'Trips show the first four linked Dive Sites, with a keyboard- and touch-friendly … more / … less disclosure for the rest.',
      'All existing canonical Site references and deep links remain intact; this is a display-only change.',
      'Trip photos marked Photo / video have clickable thumbnails and image browsing, while document categories remain compact.',
      'Shared media galleries support stable-ID multi-selection, shared caption/category editing and confirmed per-file deletion with retained filename-specific failures.',
      'Trip sections collapse without losing drafts. Long notes initially show five lines with Show more / Show less, and the old Trip upload banner is removed.',
      'Retained the Technical Workspace, private Trip/itinerary resources and additive multi-file uploads introduced in 1.0.20.',
    ],
  },
  {
    version: '1.0.20',
    date: '2026-09-14',
    title: 'Technical Workspace & Trip resources',
    changes: [
      'Added a Technical Workspace using canonical Skills, recorded configuration and gas evidence, and immutable captured pathway/reference versions; readiness is advisory, never diving authorisation.',
      'Technical planning extends the existing Dive Plan editor with recorded cylinder references, runtime and manual stop notes, without a decompression engine or replacement Plan model.',
      'Trips and individual itinerary events now retain separate private documents, media and safe links, with compact explicit document opening and stable original attachment IDs.',
      'Existing collection uploaders support additive selections, staged removal, independent per-file results and retry without losing successful uploads; Wishlist cover selection remains supported.',
      'Preserved canonical Dive, Site, Person, Equipment, Plan and Trip identities, offline event/outbox saves, backups and historical evidence.',
    ],
  },
  {
    version: '1.0.19',
    date: '2026-09-14',
    title: 'Skills & Currency — shared catalogue groups',
    changes: [
      'Skills & Currency now uses the same live Skill Catalogue groups as Settings, including custom, archived-only and future groups rather than a fixed shortlist.',
      'Retained canonical evidence, editable currency policies, offline persistence and all existing personal Dive history.',
      'Corrected the group-filter acceptance failure from the rolled-back 1.0.18 candidate without changing Skill identities or stored evidence.',
    ],
  },
  {
    version: '1.0.18',
    date: '2026-09-14',
    title: 'Skills & Currency — rolled-back candidate',
    changes: [
      'Added a responsive Skills & Currency development centre using the existing canonical Skill Catalogue and Dive evidence.',
      'Current, Due soon, Needs practice and Not assessed are derived from recorded practice and editable currency policies, never certification expiry or authorisation.',
      'Evidence history retains competence, confidence, evaluator, environment and original Dive, equipment and attachment references.',
      'Currency policies save offline through existing events, sync and backups; unknown references require review rather than name-based remapping.',
      'Preserved catalogue editing, CSV tools, protected cleanup, Plans, Sites, Trips, Loadouts and historical Logbook records.',
    ],
  },
  {
    version: '1.0.17',
    date: '2026-09-14',
    title: 'Reusable Loadouts & Gas',
    changes: [
      'Extended existing Equipment Sets with semantic slots, clone, validation and per-Dive or Plan application overrides.',
      'Applied equipment references and slot snapshots remain historical; creating a Dive from a Plan retains its loadout references and immutable Plan provenance.',
      'Physical cylinders remain Equipment; fill and analysis histories save offline through existing events, sync and backups.',
      'A newer fill visibly makes an older analysis stale until an analysis explicitly links to the new fill; partial gas readings are never displayed as a fully known mix.',
      'Added phone-safe cylinder profiles, fill/analysis forms and common private evidence attachments while preserving existing Sites, Trips and Logbook behaviour.',
    ],
  },
  {
    version: '1.0.16',
    date: '2026-09-13',
    title: 'Trip owner corrections',
    changes: [
      'Made Team, Site, Dive Plan and reusable-loadout choices readable at phone, tablet and desktop widths without character-by-character wrapping.',
      'Added Me (this account) as an organiser using the signed-in account reference, while keeping saved-Person organisers and avoiding duplicate People records.',
      'Added Trip-local non-diving participants with roles and notes; blank rows are discarded and guests remain separate from canonical Dive People.',
      'Added Meal, Activity / excursion, Training, Meeting and Rest / free time itinerary events while preserving every existing event type.',
    ],
  },
  {
    version: '1.0.15',
    date: '2026-09-13',
    title: 'Trips & Expeditions',
    changes: [
      'Added trips with itinerary, bookings, accommodation, team, packing, gas logistics and private documents.',
      'Link existing Dive Plans, Sites, People and reusable Equipment Sets without copying or changing their records.',
      'Trip details save offline through existing events, sync and backups; readiness is advisory and similar trips are never automatically merged.',
      'Added responsive, searchable reference choices and protected editors while preserving Wreck & Overhead dialog behaviour.',
    ],
  },
  {
    version: '1.0.14',
    date: '2026-09-13',
    title: 'Wreck & Overhead profiles with contained editor Escape',
    changes: [
      'Released optional canonical Site wreck/overhead profiles, dated observations, original media references and read-only Planner summaries.',
      'Escape closes only the topmost wreck editor, restores its launcher and leaves the Site card open; unsaved edits retain the existing confirmation protection.',
      'Exterior facts remain separate from disclosed trained-overhead notes; no readiness, competence or authorisation is inferred.',
    ],
  },
  {
    version: '1.0.13',
    date: '2026-09-13',
    title: 'Wreck & Overhead Site profiles — rolled-back candidate',
    changes: [
      'Added an optional wreck/overhead profile to the existing canonical Site with recorded depths, access, structured hazards, egress and route notes.',
      'Kept exterior/open-water facts separate from disclosed trained-overhead notes; recorded information never implies competence, readiness or authorisation.',
      'Added dated observations and original Dive/media references through existing offline-first events, sync and backup without duplicating Sites or historical records.',
      'Planner Site selection and detail show a read-only summary/link; route sketches use a focus-managed full-size viewer with phone-safe controls.',
    ],
  },
  {
    version: '1.0.12',
    date: '2026-09-13',
    title: 'Human-readable Skill CSV matching',
    changes: [
      'CSV import previews now show the matched canonical Skill name and group without exposing its internal ID during ordinary review.',
      'Exact Skill ID matching, updates, archive/restore actions, unresolved-ID diagnostics and exported skill_id values remain unchanged.',
    ],
  },
  {
    version: '1.0.11',
    date: '2026-09-13',
    title: 'Protected editors and visible competence guidance',
    changes: [
      'Editable overlays no longer dismiss from backdrop clicks or Escape; explicit Cancel and Close actions now protect changed form values with a discard confirmation.',
      'Skill Evidence keeps the compact competence selector while displaying the selected canonical Skill definition immediately beneath it and through accessible mouse, keyboard and touch help.',
      'Stable competence levels, legacy assessments, canonical Skill IDs and CSV behaviour remain unchanged.',
    ],
  },
  {
    version: '1.0.10',
    date: '2026-09-13',
    title: 'Skill evidence and catalogue UI correction',
    changes: [
      'Skill Evidence now records a stable Foundation, Developing, Competent, Advanced or Mastered level and shows the selected canonical Skill’s own definition while logging or editing.',
      'Legacy numeric competence and free-text assessment values remain intact and readable; changing a Skill definition does not rewrite saved evidence levels.',
      'Made logged Skill Evidence cards compact with accessible Edit, Unlink and Delete icon controls while retaining the existing delete confirmation and full evidence disclosure.',
      'Separated the Skill Catalogue heading from its naturally wrapping action toolbar and preserved responsive search, filtering and CSV actions.',
      'Made Skill Group filtering an explicit searchable multi-select with zero groups selected by default and 75-Skill incremental result batches for large catalogues.',
    ],
  },
  {
    version: '1.0.9',
    date: '2026-09-13',
    title: 'Rich Skill definitions and CSV management',
    changes: [
      'Extended each canonical Skill with a group, description and Skill-specific Foundation, Developing, Competent, Advanced and Mastered definitions without changing existing IDs or evidence references.',
      'Added local CSV preview, selective create/update/archive/restore, exact-ID matching, conservative duplicate checks and a re-importable canonical export.',
      'Added protected cleanup for unused archived Skills; any referenced historical Skill remains readable and cannot be removed by this maintenance action.',
      'Updated Dive → Add skill to search by group, name or description and display Group — Skill name while excluding archived Skills from new evidence choices.',
    ],
  },
  {
    version: '1.0.8',
    date: '2026-09-13',
    title: 'Canonical Skill Catalogue',
    changes: [
      'Resolved Skill Evidence references to human-readable canonical Skill names while preserving every Skill and evidence ID.',
      'Added Settings → Diving Data → Skill Catalogue with search, single add/edit, safe archive/restore and evidence usage counts.',
      'Added reviewed bulk entry with one Skill per line, blank-line handling and case/whitespace duplicate prevention through the same offline-first canonical Skill service.',
      'Made Dive → Add skill searchable and kept catalogue-created and Dive-created Skills immediately available through the same canonical records.',
    ],
  },
  {
    version: '1.0.7',
    date: '2026-09-13',
    title: 'Shared surface palette alignment',
    changes: [
      'Continued SNAG-UI-001 by moving shared navigation, hero, metric-chip, weather, form, technical and notice surfaces from brown/bronze fills to charcoal neutrals.',
      'Kept ZeusTek orange as the primary action/active accent and cyan for weather or other informational data.',
      'The broader page-specific design-system review remains partial and is not marked closed.',
    ],
  },
  {
    version: '1.0.6',
    date: '2026-09-13',
    title: 'Dive skills evidence workflow',
    changes: [
      'Added a visible Add skill flow to Dive Debrief using the shared canonical Skill and dive.skill_evidence records.',
      'Evidence can be created, reopened offline, edited, linked, unlinked without deleting its Skill, or explicitly deleted as a separate action.',
      'The Dive reference and evidence diveId are updated through one domain service, with duplicate Skill definitions prevented by canonical identity.',
    ],
  },
  {
    version: '1.0.5',
    date: '2026-09-13',
    title: 'Conservation reference correction',
    changes: [
      'Fixed existing Dive links so the exact selected canonical record—including legacy IDs and the latest Dive—passes strict existence and entity-type validation.',
      'Replaced duplicate Dive and Site inputs with one oldest-first Dive selector and one offline existing-Site search control.',
      'Added accessible example help and a wider, phone-safe scrolling layout to both Log and Edit conservation activity forms.',
    ],
  },
  {
    version: '1.0.4',
    date: '2026-09-12',
    title: 'Neutral dark workspace',
    changes: [
      'Replaced the warm brown page-level glow with a black and charcoal background that matches the navigation surfaces.',
      'Kept orange as an intentional accent on controls, status details and highlighted content.',
    ],
  },
  {
    version: '1.0.3',
    date: '2026-09-12',
    title: 'Conservation & AWARE',
    changes: [
      'Record conservation observations, debris surveys/removals and learning evidence using existing Dive, Site and Person references.',
      'Calculated totals distinguish surveyed debris from actual removals and retain unknown measurements.',
      'Capture sourced programme requirement versions without claiming certification or remote submission.',
      'Link private uploaded photos, videos and evidence files; local activity edits and saved references remain available without a connection.',
    ],
  },
  {
    version: '1.0.2',
    date: '2026-09-12',
    title: 'One Dive: Overview, Debrief and Story',
    changes: [
      'Added three labelled views to the existing Dive detail, with shared facts and locally saved reflections.',
      'Debrief links shared skill evidence; Story features existing media without copying or deleting originals.',
      'Plan-derived logs retain an immutable originating Plan revision for comparison with actual Dive facts.',
      'Saved media references remain available offline, and failed local saves prevent accidental navigation loss.',
    ],
  },
  {
    version: '1.0.1',
    date: '2026-09-12',
    title: 'Version and changelog baseline',
    changes: [
      'Added the current app version to the navigation footer with a link to this changelog.',
      'Recorded the existing pages and release rollback point before expansion work.',
      'Existing dive records, sharing, sync, backups and features are unchanged.',
    ],
  },
] as const;
