import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '../../chatgpt-auth';

async function ensureSchema(){await env.DB.batch([
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS journal_entries (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,occurred_at INTEGER NOT NULL,timezone TEXT NOT NULL,title TEXT,rating INTEGER,status TEXT NOT NULL DEFAULT 'published',created_at INTEGER NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS journal_revisions (id TEXT PRIMARY KEY,entry_id TEXT NOT NULL,revision_number INTEGER NOT NULL,base_revision_id TEXT,client_revision_id TEXT NOT NULL UNIQUE,origin TEXT NOT NULL,content_format TEXT NOT NULL,content TEXT NOT NULL,created_at INTEGER NOT NULL)`),
  env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_journal_entries_user_time ON journal_entries(user_id,occurred_at DESC)'),
  env.DB.prepare('CREATE UNIQUE INDEX IF NOT EXISTS idx_journal_revision_number ON journal_revisions(entry_id,revision_number)')
])}

export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:'Authentication required'},{status:401});await ensureSchema();const result=await env.DB.prepare(`SELECT e.id,e.occurred_at AS occurredAt,e.timezone,e.title,e.rating,e.status,r.id AS revisionId,r.revision_number AS revisionNumber,r.origin,r.content_format AS contentFormat,r.content FROM journal_entries e JOIN journal_revisions r ON r.entry_id=e.id WHERE e.user_id=? AND r.revision_number=(SELECT MAX(r2.revision_number) FROM journal_revisions r2 WHERE r2.entry_id=e.id) ORDER BY e.occurred_at DESC LIMIT 50`).bind(user.userId).all();return Response.json({items:result.results})}

export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Authentication required'},{status:401});const body=await request.json() as {title?:string;content?:string;contentFormat?:string;rating?:number|null;clientRevisionId?:string;occurredAt?:string};const content=body.content?.trim();if(!content||content.length>100000)return Response.json({error:'Journal content must be between 1 and 100,000 characters'},{status:400});const rating=body.rating==null?null:Math.max(1,Math.min(5,Math.trunc(body.rating)));const occurred=Date.parse(body.occurredAt||'');const now=Date.now();const entryId=crypto.randomUUID();const revisionId=crypto.randomUUID();const clientRevisionId=body.clientRevisionId||crypto.randomUUID();await ensureSchema();try{await env.DB.batch([env.DB.prepare('INSERT INTO journal_entries (id,user_id,occurred_at,timezone,title,rating,status,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(entryId,user.userId,Number.isFinite(occurred)?occurred:now,'Europe/London',(body.title||'').trim().slice(0,255)||null,rating,'published',now),env.DB.prepare('INSERT INTO journal_revisions (id,entry_id,revision_number,base_revision_id,client_revision_id,origin,content_format,content,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(revisionId,entryId,1,null,clientRevisionId,'manual',body.contentFormat==='plain_text'?'plain_text':'html',content,now)]);return Response.json({id:entryId,revisionId,revisionNumber:1},{status:201})}catch(error){const existing=await env.DB.prepare('SELECT entry_id AS id,id AS revisionId,revision_number AS revisionNumber FROM journal_revisions WHERE client_revision_id=?').bind(clientRevisionId).first();if(existing)return Response.json(existing);throw error}}
