'use client';

import type { RecreationalGasInput, RecreationalGasSnapshot } from '../../lib/offline/recreational-gas-planner';
import styles from './recreational-gas-planner.module.css';

type Props = { input: RecreationalGasInput; snapshot: RecreationalGasSnapshot | null; error: string | null; change: (patch: Partial<RecreationalGasInput>) => void };
const numeric = (value: string) => value === '' ? null : Number(value);
const display = (value: number | null | undefined, places = 1) => value == null || !Number.isFinite(value) ? '—' : value.toFixed(places);

export function RecreationalGasPlanner({ input, snapshot, error, change }: Props) {
  const selected = snapshot?.gasCandidates.find(row => row.selected);
  const reserve = snapshot?.reserve;
  return <section className={styles.planner} aria-label="Recreational gas planner">
    <header><span className="focus-eyebrow">T12.6R · RECREATIONAL</span><h3>Gas planner</h3><p>NDL is the no-decompression limit at depth. Gas-limited time is the reserve-limited breathing estimate. They are separate.</p></header>
    <details open><summary>− Mode &amp; NDL engine</summary><div className={styles.controls}>
      <label>Mode<select value={input.mode} onChange={event => change({ mode: event.target.value as RecreationalGasInput['mode'] })}><option value="direct-ascent">Direct ascent</option><option value="out-and-back">Out-and-back / return to exit</option><option value="reef-return">Reef / wall return</option><option value="multilevel">Recreational multilevel</option></select></label>
      <label>Bühlmann model<select value={input.selectedBuhlmannModel} onChange={event => change({ selectedBuhlmannModel: event.target.value as RecreationalGasInput['selectedBuhlmannModel'] })}><option value="ZH-L16B">ZH-L16B + GF</option><option value="ZH-L16C">ZH-L16C + GF</option></select></label>
      <label>GF Low (%)<input type="number" min="1" max="100" value={input.gfLow} onChange={event => change({ gfLow: Number(event.target.value) })}/></label>
      <label>GF High (%)<input type="number" min="1" max="100" value={input.gfHigh} onChange={event => change({ gfHigh: Number(event.target.value) })}/></label>
      <label className={styles.check}><input type="checkbox" checked={input.compareOtherModel} onChange={event => change({ compareOtherModel: event.target.checked })}/> Compare the other model</label>
      <p className={styles.note}>GF High controls the no-stop ascent check. GF Low is preserved for future engine compatibility. No decompression schedule is generated.</p>
    </div></details>
    <details open><summary>− Water / depth / gas</summary><div className={styles.controls}>
      <label>Water<select value={input.waterType} onChange={event => change({ waterType: event.target.value as RecreationalGasInput['waterType'] })}><option value="salt">Salt water · 10 m/bar</option><option value="fresh">Fresh water · 10.3 m/bar</option></select></label>
      <label>Surface pressure (bar)<input type="number" min="0.7" max="1.3" step="0.01" value={input.surfacePressureBar} onChange={event => change({ surfacePressureBar: Number(event.target.value) })}/></label>
      <label>Planned depth (m)<input type="number" min="1" max="60" step="0.5" value={input.plannedDepthM} onChange={event => change({ plannedDepthM: Number(event.target.value) })}/></label>
      <label>Conservatism depth (m)<input type="number" min="0" step="0.5" value={input.conservatismM} onChange={event => change({ conservatismM: Number(event.target.value) })}/></label>
      <label>Maximum PPO₂ (bar)<input type="number" min="0.5" max="1.6" step="0.05" value={input.maxPpo2} onChange={event => change({ maxPpo2: Number(event.target.value) })}/></label>
      <label>Selected / actual gas<select value={input.selectedGasLabel} onChange={event => change({ selectedGasLabel: event.target.value })}>{snapshot?.gasCandidates.map(row => <option key={row.label} value={row.label}>{row.label}</option>) ?? <option value="Air / EAN21">Air / EAN21</option>}</select></label>
      <label>Custom nitrox O₂ (%)<input type="number" min="16" max="99" step="0.1" value={input.customGas ? input.customGas.oxygenFraction * 100 : ''} onChange={event => { const percent = numeric(event.target.value); change({ customGas: percent == null ? null : { label: `Custom EAN${percent}`, oxygenFraction: percent / 100, source: 'custom', analysed: false } }); }}/></label>
      <p className={styles.note}>Best mix {display(snapshot?.bestOxygenFraction == null ? null : snapshot.bestOxygenFraction * 100)}% O₂ · conservative mix {display(snapshot?.conservativeOxygenFraction == null ? null : snapshot.conservativeOxygenFraction * 100)}% O₂. A lower-O₂ gas remains selectable.</p>
    </div></details>
    <details open><summary>− Cylinder / total gas &amp; emergency reserve</summary><div className={styles.controls}>
      <label>Cylinder water volume (L)<input type="number" min="1" step="0.1" value={input.cylinderWaterVolumeL ?? ''} onChange={event => change({ cylinderWaterVolumeL: numeric(event.target.value) })}/></label>
      <label>Start pressure (bar)<input type="number" min="1" value={input.startPressureBar ?? ''} onChange={event => change({ startPressureBar: numeric(event.target.value) })}/></label>
      <label>Own RMV (L/min)<input type="number" min="1" step="0.1" value={input.ownRmvLMin ?? ''} onChange={event => change({ ownRmvLMin: numeric(event.target.value) })}/></label>
      <label>Buddy RMV (L/min)<input type="number" min="1" step="0.1" value={input.buddyRmvLMin ?? ''} onChange={event => change({ buddyRmvLMin: numeric(event.target.value) })}/></label>
      <label>Ascent rate (m/min)<input type="number" min="1" step="0.5" value={input.ascentRateMMin} onChange={event => change({ ascentRateMMin: Number(event.target.value) })}/></label>
      <label>Reserve strategy<select value={input.reserveStrategy} onChange={event => change({ reserveStrategy: event.target.value as RecreationalGasInput['reserveStrategy'] })}><option value="calculated">Calculated emergency reserve</option><option value="thirds">Rule of thirds</option><option value="most-conservative">Most conservative of both</option></select></label>
      <label>Owner maximum duration (min, optional)<input type="number" min="1" value={input.ownerMaxDurationMin ?? ''} onChange={event => change({ ownerMaxDurationMin: numeric(event.target.value) })}/></label>
    </div><div className={styles.metrics}><span>Total gas <strong>{display(snapshot?.totalGasLitres, 0)} L</strong></span><span>Emergency reserve <strong>{display(reserve?.totalLitres, 0)} L</strong></span><span>Thirds reserve <strong>{display(reserve?.thirdsLitres, 0)} L</strong></span><span>Selected reserve <strong>{display(reserve?.selectedLitres, 0)} L · {display(reserve?.selectedBar, 0)} bar</strong></span></div>
      {reserve?.buddyFallback && <p role="alert" className={styles.warning}>Buddy RMV unknown; own RMV is used as fallback.</p>}
      {reserve?.state === 'unavailable' && <output>{reserve.reason}</output>}
      {!!reserve?.phases.length && <div className={styles.scroll}><table><thead><tr><th>Phase</th><th>Depth</th><th>Min</th><th>Both divers</th><th>Gas</th></tr></thead><tbody>{reserve.phases.map(phase => <tr key={phase.label}><td>{phase.label}</td><td>{display(phase.depthM)} m</td><td>{phase.minutes}</td><td>{phase.multiplier * 100}%</td><td>{display(phase.litres, 0)} L</td></tr>)}</tbody></table></div>}
    </details>
    <details open><summary>− Limit summary &amp; gas comparison</summary>
      <div className={styles.metrics}><span>Selected gas NDL <strong>{selected?.ndl.state === 'available' ? `${selected.ndl.minutes} min` : selected?.ndl.unavailableReason ?? '—'}</strong></span><span>Gas-limited time <strong>{display(selected?.gasLimitedTimeMin)} min</strong></span><span>Planned working time <strong>{display(snapshot?.plannedWorkingTimeMin)} min</strong></span><span>Limiting factor <strong>{snapshot?.limitingFactor ?? 'unavailable'}</strong></span></div>
      <div className={styles.scroll}><table><thead><tr><th>Gas / source</th><th>O₂ / N₂</th><th>MOD</th><th>PPO₂ planned / conservative</th><th>EAD</th><th>{input.selectedBuhlmannModel} NDL</th>{input.compareOtherModel && <th>Other model NDL</th>}<th>Table backup</th><th>Gas time</th><th>Warnings</th></tr></thead><tbody>{snapshot?.gasCandidates.map(row => <tr key={row.label} aria-selected={row.selected}><td><strong>{row.label}</strong><small>{row.source}{row.selected ? ' · actual' : ''}{row.analysed ? ` · analysed ${row.analysedEvidence ?? ''}` : ''}</small></td><td>{display(row.oxygenFraction * 100, 0)}% / {display(row.nitrogenFraction * 100, 0)}%</td><td>{display(row.modM)} m</td><td>{display(row.ppo2AtPlannedDepth, 2)} / {display(row.ppo2AtConservativeDepth, 2)}</td><td>{display(row.eadM)} m</td><td>{row.ndl.state === 'available' ? `${row.ndl.minutes} min` : row.ndl.unavailableReason ?? row.ndl.state}</td>{input.compareOtherModel && <td>{row.otherModelNdl?.state === 'available' ? `${row.otherModelNdl.minutes} min` : row.otherModelNdl?.unavailableReason ?? '—'}</td>}<td>{row.tableBackup.state === 'not-configured' ? 'No backup table configured.' : row.tableBackup.state === 'available' ? `${row.tableBackup.provider} ${row.tableBackup.minutes} min` : row.tableBackup.reason}</td><td>{display(row.gasLimitedTimeMin)} min</td><td>{row.warnings.join(' ') || 'OK'}</td></tr>)}</tbody></table></div>
    </details>
    <details open><summary>− Route / checkpoint reserve</summary>
      {input.mode !== 'direct-ascent' && <><p className={styles.note}>Enter ordered route legs, including the return. Required gas at each checkpoint includes every remaining leg plus final reserve.</p>{input.routeSegments.map(segment => <div className={styles.routeRow} key={segment.id}><label>Checkpoint<input value={segment.label} onChange={event => change({ routeSegments: input.routeSegments.map(row => row.id === segment.id ? { ...row, label: event.target.value } : row) })}/></label><label>Depth (m)<input type="number" min="0" value={segment.depthM ?? ''} onChange={event => change({ routeSegments: input.routeSegments.map(row => row.id === segment.id ? { ...row, depthM: numeric(event.target.value) } : row) })}/></label><label>Duration (min)<input type="number" min="1" value={segment.minutes ?? ''} onChange={event => change({ routeSegments: input.routeSegments.map(row => row.id === segment.id ? { ...row, minutes: numeric(event.target.value) } : row) })}/></label><button type="button" className="focus-secondary" onClick={() => change({ routeSegments: input.routeSegments.filter(row => row.id !== segment.id) })}>Remove</button></div>)}<button type="button" className="focus-secondary" onClick={() => change({ routeSegments: [...input.routeSegments, { id: crypto.randomUUID(), label: '', depthM: null, minutes: null }] })}>+ Add route leg / checkpoint</button></>}
      {snapshot?.routeCheckpoints.state === 'unavailable' ? <output>{snapshot.routeCheckpoints.reason}</output> : <div className={styles.scroll}><table><thead><tr><th>Checkpoint</th><th>Required remaining</th><th>Expected remaining</th><th>Status</th><th>Reason</th></tr></thead><tbody>{snapshot?.routeCheckpoints.checkpoints.map(row => <tr key={row.label}><td>{row.label}</td><td>{display(row.requiredLitres, 0)} L</td><td>{display(row.expectedLitres, 0)} L</td><td>{row.status}</td><td>{row.reason}</td></tr>)}</tbody></table></div>}
    </details>
    <details open><summary>− Warnings &amp; save snapshot</summary>{error && <p role="alert" className={styles.warning}>{error}</p>}{snapshot?.warnings.length ? <ul>{snapshot.warnings.map((warning, i) => <li key={`${warning}-${i}`}>{warning}</li>)}</ul> : <p>No current calculation warnings.</p>}<p className={styles.note}>Save gas comparison, model and tissue assumptions, reserve phases, route checkpoints and warnings to this existing Gas Plan. No Dive record is changed.</p></details>
  </section>;
}
